// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/
import CMigration
import Darwin

let version = "version 20260816"

let RECSIZE : UInt = (8 * 1024)  // sets limit on records, fields, etc., etc.

@main struct awk : ShellCommand {
  //  uint32_t val;
  //  int ch, fd, rval;
  //  off_t len;
  //  char *fn, *p;
  //  int (*cfncn)(int, uint32_t *, off_t *);
  //  void (*pfncn)(char *, uint32_t, off_t);

  struct CommandOptions {
    var safe : Bool = false
    var pfile : [String] = []
    var fs : String = ""
    var dbg : Int = 0
    var lexprog : String? = nil
    var programName : String = ""
    var args : [String] = []
  }

  var options : CommandOptions!

  var runtime = RuntimeState.shared




  /*
   if ((p = strrchr(argv[0], '/')) == NULL)
   p = argv[0];
   else
   ++p;
   */

    func parseOptions() async throws(CmdErr) -> CommandOptions {

    setlocale(LC_CTYPE, "");
//    setlocale(LC_COLLATE, "");
//    setlocale(LC_NUMERIC, "C"); /* for parsing cmdline & prog */
//    cmdname = argv[0];


    // FIXME: split the command
/*    if (!strcmp(p, "sum")) {
     cfncn = csum1;
     pfncn = psum1;
     ++argv;
     } else {
     */
    var options = CommandOptions()
      options.programName = programName
      // for DPRINTF

    let go = BSDGetopt("f:F:v:d::s::")
  loop:
    while let (k,v) = try go.getopt() {
      switch k {
      case "-":
        break loop
      case "V":
        print("awk \(version)")
        exit(0)
      case "s":
        if v == "afe" {
          options.safe = true
        }

      case "f":  // next argument is program filename
          do {
            options.lexprog = try readFileAsString(at: v)
          } catch(let e) {
            throw CmdErr(1, "unable to read program file \(v): \(e.localizedDescription)")
          }

      case "F":  /* set field separator */
        options.fs = v

      case "v":  /* -v a=1 to be done NOW.  one -v for each */
        let vn = v
          if (isclvar(vn)) {
          await setclvar(vn)
        }
        else {
          throw CmdErr(2, "invalid -v option argument: \(vn)")
        }

      case "d":
          if v.isEmpty {
            options.dbg += 1
          } else {
            options.dbg = Int(v) ?? 1
          }
          // FIXME: for DPRINTF -- need the dbg flag -- and options doesn't get it in time.
          await runtime.setDebug(options.dbg)
        print("awk \(version)")
      default:
        throw CmdErr(1)
      }

    }

    options.args = go.remaining

      var sa = sigaction.init()
      sa.__sigaction_u.__sa_sigaction = fpecatch;
      sa.sa_flags = SA_SIGINFO;
      sigemptyset(&sa.sa_mask);
      sigaction(SIGFPE, &sa, nil)


    /*signal(SIGSEGV, segvcatch); experiment */

    await srand48(runtime.srand_seed)

 //   runtime.yyin = nil
 //   symtab = makesymtab(NSYMTAB/NSYMTAB);

    if options.lexprog == nil {  // no -f; first argument is program
      if (options.args.count < 1) {
        if options.dbg != 0 {
          exit(0);
        }
        throw CmdErr(2, "no program given")
      }
      let vv = options.args.removeFirst()
      DPRINTF("program = |\(vv)|\n")
      options.lexprog = vv;
    }

      return options
  }


  func runCommand() async throws(CmdErr) {
    await runtime.setOptions(options)

    if (!options.safe) {
      await runtime.envinit()
    }

    await runtime.syminit()

    do {

      // Step 1: Lex
      var lexer = AWKLexer(options.lexprog ?? "")
      let tokens = try lexer.tokenize()          // → [AWKToken]

      // Step 2: Parse
      let ast = try AWKParser.parse(tokens)      // → AWKProgram


      setlocale(LC_NUMERIC, ""); /* back to whatever it is locally */

        // Step 3: Execute
        // From files:
      try await runtime.run(ast, inputPaths: options.args)
        // From stdin (no inputPaths):

    } catch(let e) {
      throw CmdErr(2, "\(e)")
    }
  }

  var usage : String { "usage: \(programName) [-F fs] [-v var=value] [-f progfile | 'prog'] [file ...]" }


  func DPRINTF(_ s : String) {
    // FIXME: ugly in the extreme -- problem with DPRINTF being called by parseOptions before options are set
    Task {
      if  await runtime.dbg > 0 {
        print(s)
      }
    }
  }

  func isclvar(_ s : String) -> Bool { // is s of form var=something ?
    guard let sf = s.first else { return false }
    guard sf.isLetter || sf == "_" else { return false }
    let k = s.split(separator: "=")
    guard k.count == 2 else { return false }
    guard (k[0].allSatisfy { $0.isLetter || $0.isWholeNumber || $0 == "_" }) else { return false }
    return true
  }

  func setclvar(_ ss : String) async { // set var=value from s
    let k = ss.split(separator: "=")
    let p = String(k[1])
    let s = String(k[0])
    await runtime.setsym(s, ValueCell(string: p))
    DPRINTF("command line set \(s) to |\(p)|\n")
  }


}

// May return now, if kill(2)-delivered in conformance mode.
  func fpecatch(_ n : Int32, _ six : UnsafeMutablePointer<siginfo_t>?, _ uc : UnsafeMutableRawPointer?) {


let si = six!

  let emsg = [
    0 : "Unknown error",
    FPE_INTDIV : "Integer divide by zero",
    FPE_INTOVF : "Integer overflow",
    FPE_FLTDIV : "Floating point divide by zero",
    FPE_FLTOVF : "Floating point overflow",
    FPE_FLTUND : "Floating point underflow",
    FPE_FLTRES : "Floating point inexact result",
    FPE_FLTINV : "Invalid Floating point operation",
    FPE_FLTSUB : "Subscript out of range",
  ]



  if (si.pointee.si_code == 0) {

     // 0 == FPE_NOOP, used when delivered by kill(2).  We just
     // reset the disposition and re-deliver SIGFPE for conformance
     // purposes.

    signal(SIGFPE, SIG_DFL);
    raise(SIGFPE);
    return;
  }


let fx = si.pointee.si_code < emsg.count && emsg[si.pointee.si_code] != nil
    ? emsg[si.pointee.si_code] : emsg[0]
    // was FATAL(...)
    var se = FileDescriptor.standardError
    print("floating point exception: \(fx ?? "??")", to: &se)
    exit(2)
}

