// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/

// AST-walking interpreter for AWK.
// Corresponds to run.c from one-true-awk, but operates on the Swift AST
// (AWKProgram / Statement / Expression) rather than the C Node* tree.

import CMigration
import Darwin
import Dispatch
import Synchronization

// MARK: - Call frame

// MARK: - AWK Executor

extension RuntimeState {

// this function was copied from sed (process.swift) where it is caslled mf_gets
  /// this function gets the next line for processing from a list of files read sequentially
  /// it is also the awk function GETLINE
  func awkGets() throws -> String? {

    /*
     var inFile = FileDescriptor.standardInput.bytes.lines.makeAsyncIterator()
     while let l = try await inFile.next() {

     }
     */

    while !quit {
      if nil != self.inp {
        do {
          if let got = self.inp!.next() {
//            self.linenum += 1
            return got
          }
          // reached EOF
          mf_close_file()
          continue
        }
        // FIXME: handle the 'inplace' option
      } else {
        // This is where the next file is opened
        if self.filelist.isEmpty { return nil }
        if let i = try mf_next_file() {
          self.inp = i
        } else {
          break
        }
      }
    }
    mf_close_file()
    return nil
  }

  // close the current file so I can move to the next one
  // FIXME: does nothing?
  func mf_close_file() {
    self.inp = nil
  }
  // copied from sed (process.swift)
  /// advances to the next input file in the list
  func mf_next_file() throws(CmdErr) -> SyncRecordReader.Iterator? {
    if self.filelist.isEmpty {
      return nil
    }

    // get the first file and use it up
    let fnam = self.filelist.removeFirst()
    // open file
    if fnam == "-"  || fnam == "/dev/stdin" {
      FILENAME = "stdin"
      FNR = 0
      let k = FileDescriptor.standardInput.syncBytes
      let j = k.records(rs: RS.first!)
      return j.makeIterator()
    } else {
      do {
        FILENAME = fnam
        FNR = 0
        return try FileDescriptor(forReading: fnam).syncBytes.records(rs: RS.first!).makeIterator()
      } catch {
        throw CmdErr(1, "\(fnam): \(error)")
      }
    }
  }

/*

  func awkReadline() {
      let paths = inputPaths.isEmpty ? ["-"] : inputPaths
      outer: for path in paths {
        let file: AWKFile
        if path == "-" {
          file = AWKFile(name: "-", mode: .read, handle: .standardInput)
        } else {
          guard let fh = FileHandle(forReadingAtPath: path) else {
            fputs("awk: can't open \(path)\n", stderr)
            continue
          }
          file = AWKFile(name: path, mode: .read, handle: fh)
        }
        FILENAME = path
        FNR = 0

        while let rec = file.readRecord(rs: RS) {
          NR += 1; FNR += 1
          record = rec

          for (idx, rule) in program.rules.enumerated() {
            do {
              if try matchesPattern(rule.pattern, ruleIndex: idx) {
                if rule.body.isEmpty {
                  // no body → print $0
                  try print_([.field(.number(0))], dest: nil)
                } else {
                  try execBlock(rule.body)
                }
              }
            } catch AWKSignal.next { continue outer }
            catch AWKSignal.nextFile { break }
            catch AWKSignal.exit_(let code) {
              exitCode = code
              file.close()
              try runEndBlocks(program)
              return
            }
          }
        }
        file.close()
      }
    }
*/

  // MARK: - Main entry point
  
  /// Run a parsed AWK program over the provided input files (or stdin if empty).
  // C: run() + getrec() loop — run.c / lib.c
  func run(_ program: AWKProgram, inputPaths: [String] = []) async throws {
    // Populate function table
    filelist = inputPaths
    
    for fn in program.functions { functions[fn.name] = fn }
    
    // Set up ARGV / ARGC
    let argc = self.options.args.count + 1
    var argv : [Cell] = [ValueCell(string: CommandLine.arguments[0])]
    for (_, a) in options.args.enumerated() {
      argv.append(ValueCell(string: a))
    }
    setsym("ARGV", Dictionary(array: argv))
    setsym("ARGC", ValueCell(number: argc))
    
    // Range-pattern pairstack
    pairstack = Array(repeating: false, count: program.rules.count)
    
    // --- BEGIN blocks ---
    do {
      for stmts in program.beginRules {
        try execBlock(stmts)
      }
    } catch AWKSignal.exit_(let code) {
      exitCode = code
      try runEndBlocks(program)
      return
    }
    
    // --- Per-record body ---
    if !program.rules.isEmpty || !program.endRules.isEmpty {
      /*
      let paths = inputPaths.isEmpty ? ["-"] : inputPaths
      outer: for path in paths {
        let file: AWKFile
        if path == "-" {
          file = AWKFile(name: "-", mode: .read, handle: .standardInput)
        } else {
          guard let fh = FileHandle(forReadingAtPath: path) else {
            fputs("awk: can't open \(path)\n", stderr)
            continue
          }
          file = AWKFile(name: path, mode: .read, handle: fh)
        }
        FILENAME = path
        FNR = 0
        */
    getr:
      while let rec = try? awkGets() {

//        while let rec = file.readRecord(rs: RS) {
          NR += 1; FNR += 1
          record = rec
          
          for (idx, rule) in program.rules.enumerated() {
            do {
              if try matchesPattern(rule.pattern, ruleIndex: idx) {
                if rule.body.isEmpty {
                  // no body → print $0
                  try print_([.field(.number(0))], dest: nil)
                } else {
                  try execBlock(rule.body)
                }
              }
              // FIXME: why is AWKSignal.next different than nextFile?
            } catch AWKSignal.next { continue getr }
            catch AWKSignal.nextFile { mf_close_file();  break }
            catch AWKSignal.exit_(let code) {
              exitCode = code
              mf_close_file()
              try runEndBlocks(program)
              return
            }
          }
        }
 //       file.close()
      }
    
    // --- END blocks ---
    try runEndBlocks(program)
  }
  
  // C: program() END-block handling — run.c
  func runEndBlocks(_ program: AWKProgram) throws {
    inEndBlock = true
    do {
      for stmts in program.endRules {
        try execBlock(stmts)
      }
    } catch AWKSignal.exit_(let code) {
      exitCode = code
    }
    inEndBlock = false
    closeAll()
  }
  
  // MARK: - Pattern matching
  
  // C: pastat() + dopa2() — run.c
  func matchesPattern(_ pattern: PatternKind, ruleIndex: Int) throws -> Bool {
    switch pattern {
      case .always:
        return true
      case .expression(let e):
        return try eval(e).isTrue
      case .range(let p1, let p2):
        if pairstack[ruleIndex] {
          let done = try eval(p2).isTrue
          if done { pairstack[ruleIndex] = false }
          return true
        } else {
          let start = try eval(p1).isTrue
          if start { pairstack[ruleIndex] = true }
          return start
        }
    }
  }
  
  
  
  
  // MARK: - LValue resolution (returns the cell itself for mutation)
  
  // C: field() / array() / indirect() — run.c
  func evalLValue(_ lv: LValue, _ store : ((Cell) throws ->Cell)? = nil ) throws -> Cell { // value, fldnum
    switch lv {
      case .variable(let name):
        return try resolveVar(name, store)

/*      case .argument(let i):
        guard var frame = callStack.last, i < frame.cells.count else {
          throw AWKRuntimeError("function argument \(i) out of range")
        }
        let val = frame.cells[i]
        if let store {
          let res = try store(val)
          frame.cells[i]=res
          callStack[callStack.endIndex-1]=frame
          return res
        }
        return val
 */
/*
      case .varnf:
        // Assign to NF specially through a proxy cell that triggers setNF on write.
        // For simplicity, we handle NF assignment in execAssign.
        let c = symtab["NF"]!;
        if let store {

          return (c, nil, nil)
        }
*/
        
      case .field(let e):
        // Field lvalue — we can't return a reference to an element of env.fields.
        // Instead, return a proxy: a cell whose value changes are applied via setField.
        // We wrap this in a FieldProxy approach: return a cell and post-assign it.
        // This is handled per-case in execAssign and incr/decr.
        // For the incr/decr case, we need the actual stored cell; use a field cell.
        let n = Int(try eval(e).getNumber())
        let val = makeFieldCell(n)
        if let store {
          let res = try store(val)
          setFieldCell(n, res)
          return res
        }
        return val

      case .element(let name, let keys):
        return try resolveElement(name: name, keys: keys, store)

      case .indirect(let e):
        let n = Int(try eval(e).getNumber())
        let val = makeFieldCell(n)
        if let store {
          let res = try store(val)
          setFieldCell(n, res)
          return res
        }
        return val
    }
  }



  // FIXME: can I make the evalLValue / storeLValue pair a single function (with a closure arg?)
/*  func storeLValue(_ lv: LValue, _ c : Cell, _ fldnum : Int?, _ key : String?) throws  {
    switch lv {
      case .variable(let name):
        return storeVar(name, c)
        
      case .argument(let i):
        guard var frame = callStack.last, i < frame.cells.count else {
          throw AWKRuntimeError("function argument \(i) out of range")
        }
        frame.cells[i]=c
        
      case .varnf:
        // Assign to NF specially through a proxy cell that triggers setNF on write.
        // For simplicity, we handle NF assignment in execAssign.
        setsym("NF", c)
        
      case .field(let e):
        // Field lvalue — we can't return a reference to an element of env.fields.
        // Instead, return a proxy: a cell whose value changes are applied via setField.
        // We wrap this in a FieldProxy approach: return a cell and post-assign it.
        // This is handled per-case in execAssign and incr/decr.
        // For the incr/decr case, we need the actual stored cell; use a field cell.
        setFieldCell(fldnum!, c)

      case .element(let name, let keys):
        try storeElement(name: name, c, key!)

      case .indirect(let e):
        setFieldCell(fldnum!, c)
    }
  }
  */


  // MARK: - Variable / element resolution
  func storeVar(_ name : String, _ c : Cell) throws {
    // Check built-in variables first
    // Check current call frame
    if var frame = callStack.last {
      if let i = frame.paramNames.firstIndex(of: name) {
        frame.cells[i]=c
        callStack[callStack.endIndex-1] = frame
        // FIXME: this is broken if the function callers uses a field or element value with a non-reentrant index
        if i < frame.callLVals.count, let lv = frame.callLVals[i] {
          try evalLValue(lv) { r in c }
        }
        return
      }
    }
    setsym(name, c)
  }

  // C: setsymtab() + lookup() — tran.c
  func resolveVar(_ name: String, _ store : ((Cell) throws ->Cell)? ) throws -> Cell {
    // Check built-in variables first
    // Check current call frame
    if var frame = callStack.last {
      if let i = frame.paramNames.firstIndex(of: name) {
        if let store {
          let res = try store(frame.cells[i])
          frame.cells[i]=res
          callStack[callStack.endIndex-1] = frame
        }
        return frame.cells[i] // either the read, or the post update value
      }
    }

    let old = symtab[name] ?? EmptyCell()
    if let store {
      let res = try store(old)
      setsym(name, res)
      return res
    }
    return old
  }
  
  // C: array() — run.c
  func resolveElement(name: String, keys: [Expression], _ store: ((Cell) throws->Cell)?) throws -> Cell {
    let parts = try keys.map { try eval($0).asString() }
    let key = subscriptKey(parts)
    var elres : Cell = EmptyCell()
    let _ = try resolveVar(name) { arr in
      if arr is Dictionary {
        var ee = (arr as! Dictionary).dict
        elres = ee[key] ?? EmptyCell()
        if let store {
          let res = try store(elres)
          ee[key]=res
          elres = res
          return Dictionary(dict: ee)
        }
      } else {
        if let store {
          elres = try store(EmptyCell())
          var ee = [String:Cell]()
          ee[key]=elres
          return Dictionary(dict: ee)
        }
        return EmptyCell()
      }
      return arr
    }
    return elres
  }
  
  // MARK: - Field proxy cells
  
  /// A pseudo-cell backed by field slot n.  Changes are written back via setField.
  //    var fieldCells: [Int: Cell] = [:]
  
  // C: fieldadr() — lib.c
  func makeFieldCell(_ n: Int) -> Cell {
    //        if let existing = fieldCells[n] { return existing }
    let s = getField(n)
    let c = ValueCell(string: s)
    return c
  }
  
  // C: fieldadr() — lib.c
  func setFieldCell(_ n: Int, _ c : Cell) {
    // do I need to do "ensureFields" ?
    ensureFields()
    if n == 0 { ensureRecord(); record = c.asString() ; return}
    fldtab[n-1]=c.asString()
  }
  
  /*
   // C: (no direct equivalent; field proxy write-back)
   func flushFieldCells() {
   for (n, c) in fieldCells {
   setField(n, c.asString())
   }
   fieldCells = [:]
   }
   */
  
  // MARK: - Assignment
  
  // C: assign() — run.c
  func execAssign(op: AssignOp, lv: LValue, rhs: Expression) throws -> Cell {
    var rhsVal = try eval(rhs)
    // FIXME: bury this in Cell
    // Gymnastics, because otherwise  x = NR (say) makes x the builtin, not the value of the builtin.
    if rhsVal is BuiltInNumber {
      rhsVal = ValueCell(number: rhsVal.getNumber())
    } else if rhsVal is BuiltInString {
      rhsVal = ValueCell(string: rhsVal.asString())
    }

    // NF assignment requires special handling
/*    if case .varnf = lv {
      let n = Int(rhsVal.getNumber())
      setNF(n)
      
      return ValueCell(number: n)
    }
*/
    
    // Field assignment writes through to env.fields / env.record
    if case .field(let fe) = lv {
      let n = Int(try eval(fe).getNumber())
      let cur = ValueCell(number: getField(n) == "" ? 0 : 0)
      let curStr = getField(n)
      let curNum = AWKRuntime.parseNum(curStr)
      let newVal = applyOp(op, lhsNum: curNum, lhsStr: curStr, rhs: rhsVal)
      setField(n, newVal.asString())
      // FIXME: why the reference to donefld here?
      if n == 0 { donefld = false }
      _ = cur  // suppress warning
      return newVal
    }
    
    return try evalLValue(lv) { target in
      return self.applyOp(op, lhsNum: target.getNumber(), lhsStr: target.asString(), rhs: rhsVal)
    }
  }
  
  // C: assign() operator switch — run.c
  func applyOp(_ op: AssignOp, lhsNum: Double, lhsStr: String, rhs: Cell) -> Cell {
    switch op {
      case .set:    return rhs
      case .addSet: return ValueCell(number: lhsNum + rhs.getNumber())
      case .subSet: return ValueCell(number: lhsNum - rhs.getNumber())
      case .mulSet: return ValueCell(number: lhsNum * rhs.getNumber())
      case .divSet:
        let d = rhs.getNumber()
        return ValueCell(number: d == 0 ? 0 : lhsNum / d)   // real code throws
      case .modSet:
        let d = rhs.getNumber()
        var i = 0.0; modf(lhsNum / d, &i)
        return ValueCell(number: lhsNum - d * i)
      case .powSet:
        return ValueCell(number: ipow(lhsNum, rhs.getNumber()))
    }
  }
  
  // MARK: - Power helper (matches C ipow for integer exponents)
  
  // C: ipow() — run.c
  func ipow(_ x: Double, _ exp: Double) -> Double {
    var intPart = 0.0
    if exp >= 0 && modf(exp, &intPart) == 0.0 {
      var result = 1.0; var n = Int(exp); var base = x
      while n > 0 { if n & 1 == 1 { result *= base }; base *= base; n >>= 1 }
      return result
    }
    return pow(x, exp)
  }
  
  // MARK: - Regex helper (extracts pattern string from an expression)
  
  // C: (no direct equivalent; extracts pattern string from an expression node)
  func regexPattern(_ e: Expression) throws -> String {
    if case .regexMatch(let s) = e { return s }
    return try eval(e).asString()
  }
  
  // MARK: - Print statement
  
  // C: printstat() — run.c
  func execPrint(kind: PrintKind, args: [Expression], dest: PrintDest?) throws {
    let output: AWKFile
    switch dest {
      case .none:
        output = AWKFile(name: "/dev/stdout", mode: .write, handle: .standardOutput)
      case .redirect(let e):
        let path = try eval(e).asString()
        output = try fileFor(name: path, mode: .write)
      case .append(let e):
        let path = try eval(e).asString()
        output = try fileFor(name: path, mode: .append)
      case .pipe(let e):
        let cmd = try eval(e).asString()
        output = try fileFor(name: cmd, mode: .outputPipe)
    }
//    defer {
//      output.close() }

    switch kind {
      case .print:
        try print_(args, dest: dest, to: output)
      case .printf:
        guard !args.isEmpty else { return }
        let fmtStr = try eval(args[0]).asString()
        let result = try format(fmtStr, args: Array(args.dropFirst()))
        try output.write(result)
    }
  }
  
  // C: printstat() output loop — run.c
  func print_(_ args: [Expression], dest: PrintDest?, to output: AWKFile? = nil) throws {
    let out = output ?? AWKFile(name: "/dev/stdout", mode: .write, handle: .standardOutput)
    if args.isEmpty {
      ensureRecord()
      try out.write(record! + ORS)
      return
    }
    var first = true
    for arg in args {
      if !first { try out.write(OFS) }
      let val = try eval(arg)
      try out.write(val.asString(fmt: OFMT))
      first = false
    }
    try out.write(ORS)
  }
  
  // MARK: - Delete statement
  
  // C: awkdelete() — run.c
  func execDelete(_ lv: LValue) throws {
    switch lv {
      case .variable(let name):
        let _ = try resolveVar(name) { _ in EmptyCell() }

      case .element(let name, let keys):
        let parts = try keys.map { try eval($0).asString() }
        let key = subscriptKey(parts)
        let _ = try resolveVar(name) {ee in
          if ee is Dictionary {
            var aa = (ee as! Dictionary).dict
            // FIXME: aa has to be stored back?
            aa.removeValue(forKey: key)
            return Dictionary(dict: aa)
          }
          return ee
        }
      default:
        throw AWKRuntimeError("delete requires a variable or array element")
    }
  }
  
  // MARK: - User-defined function call
  
  // C: call() — run.c
  func execUserCall(name: String, argExprs: [Expression]) throws -> Cell {
    guard let fn = functions[name] else {
      throw AWKRuntimeError("calling undefined function '\(name)'")
    }
    // Evaluate actual arguments
    var cells: [Cell] = []
    var lvals: [LValue?] = []
    for argExpr in argExprs {
      let k = argExpr.asLValue()
      lvals.append(k)
      let c = try eval(argExpr)
      // FIXME: did I muck this up?
      cells.append(c)
    }
    // Pad with empty cells for any unspecified parameters
    while cells.count < fn.params.count { cells.append(EmptyCell()) }
    // Extra locals beyond defined params
    // (one-true-awk uses extra params as local variables)
    
    let frame = CallFrame(funcName: name, paramNames: fn.params, cells: cells, callLVals: lvals)
    callStack.append(frame)
    defer { callStack.removeLast() }

    var retval : Cell
    do {
      try execBlock(fn.body)
      retval = callStack.last?.retval ?? EmptyCell()
    } catch AWKSignal.`return`(let val) {
      retval = val
    }
    // Before returning, if any of the args are variables, then if the corresponding frame values have
    // been updated, the variable argumnet must be updated
    // Alternatively, the call frame can handle the update when it happens
//    for (lv, c) in zip(lvals, callStack.last!.cells) {

    return retval
  }

  // MARK: - Builtin function call
  
  // C: bltin() — run.c
  func execBuiltin(id: AWKBuiltinID, args: [Expression]) throws -> Cell {
    switch id {
      case .length:
        if args.isEmpty {
          ensureFields()
          return ValueCell(number: record!.count)
        }
        let c = try eval(args[0])
        return ValueCell(number: c.length() )
        
      case .sqrt:
        return ValueCell(number: sqrt(try eval(args[0]).getNumber()))
        
      case .exp:
        return ValueCell(number: exp(try eval(args[0]).getNumber()))
        
      case .log:
        let v = try eval(args[0]).getNumber()
        if v <= 0 { throw AWKRuntimeError("log: argument must be positive") }
        return ValueCell(number: log(v))
        
      case .int_:
        var intPart = 0.0; modf(try eval(args[0]).getNumber(), &intPart)
        return ValueCell(number: intPart)
        
      case .system:
        let cmd = try eval(args[0]).asString()
        fflush(stdout)
        let sem = DispatchSemaphore(value: 0)
        let result = Mutex<Int>(-1)
        Task {
          let p = DarwinProcess()
          if let r = try? await p.run("/bin/sh", args: "-c", cmd, output: (nil, nil)) {
            result.withLock { $0 = Int(r.code) }
          }
          sem.signal()
        }
        sem.wait()
        return ValueCell(number: Double(result.withLock { $0 }))

      case .rand:
        let r = arc4random()
//        let r2 = Darwin.random()
        return ValueCell(number: Double(r) / Double(UInt32.max) )

      case .srand:
        let old = srand_seed
        let seed: Double
        if args.isEmpty { seed = Double(DateTime().timeInterval) }
        else            { seed = try eval(args[0]).getNumber() }
        srand_seed = UInt32(seed)
        srand48(Int(seed))
        return ValueCell(number: Double(old))
        
      case .sin:
        return ValueCell(number: sin(try eval(args[0]).getNumber()))
        
      case .cos:
        return ValueCell(number: cos(try eval(args[0]).getNumber()))
        
      case .atan2:
        let y = try eval(args[0]).getNumber()
        let x = args.count > 1 ? try eval(args[1]).getNumber() : 1.0
        return ValueCell(number: atan2(y, x))
        
      case .toupper:
        return ValueCell(string: try eval(args[0]).asString().uppercased())
        
      case .tolower:
        return ValueCell(string: try eval(args[0]).asString().lowercased())
        
      case .fflush:
        if args.isEmpty {
          flushAll()
        } else {
          let name = try eval(args[0]).asString()
          if name.isEmpty { flushAll() }
          else if let f = openFiles.first(where: { $0.name == name }) {
//            try? f.handle.synchronize()
          }
        }
        return ValueCell(number: 0)
    }
  }
  
  // MARK: - Getline
  
  // C: awkgetline() — run.c
  func execGetline(lv: LValue?)  throws -> Cell {
    // Bare getline — read next record from current input (stdin)
    // For simplicity, read from stdin
    guard let line = try awkGets() else {
//    guard let line = readln(from: .standardInput) else {
      return ValueCell(number: 0)
    }
    if let lv {
      let _ = try evalLValue(lv) {_ in
        return ValueCell(string: line)
      }
    } else {
      NR += 1; FNR += 1
      record = line
    }
    return ValueCell(number: 1)
  }

  // C: awkgetline() file-variant — run.c
  func readLineInto(lv: LValue?, from file: AWKFile, updates0: Bool) throws -> Cell {
    guard let line = try file.readRecord(rs: RS) else { return ValueCell(number: 0) }
    if let lv {
      return try evalLValue(lv) { _ in
        return ValueCell(string: line)
      }
    } else if updates0 {
      record = line
    }
    return ValueCell(number: 1)
  }
  
  // C: readrec() — lib.c
  func readln(from fh: FileDescriptor) throws -> String? {
    // Inefficient but simple: read byte-by-byte until RS
    var line = ""
    let sep: UInt8 = RS.first.map { $0.asciiValue ?? 10 } ?? 10
    while true {
      let data = try fh.readAvailableBytes()
      guard !data.isEmpty else { return line.isEmpty ? nil : line }
      for byte in data {
        if byte == sep { return line }
        line.append(Character(Unicode.Scalar(byte)))
      }
    }
  }
  
  // MARK: - String operations
  
  // C: sub() — run.c
  func execSub(kind: SubKind, reExpr: Expression, replExpr: Expression, target: LValue) throws -> Cell {
    let pat = try regexPattern(reExpr)
    let repl = try eval(replExpr).asString()
    var count = 0
    try evalLValue(target) { targetCell in
      let str = targetCell.asString()

      var result : String = str   // default: no match leaves target unchanged

      let re = try AWKRuntime.makeRegex(pat)
      let ns = str
      let range = str.startIndex ..< str.endIndex

      switch kind {
        case .sub:
          // FIXME: do I need the range?
          if let m = try re.firstMatch(in: str[range]) {
            let matched = ns[m.range]
            let replacement = AWKRuntime.applyReplacement(repl, matched: Substring(matched))
            result = ns.replacingCharacters(in: m.range, with: replacement)
            // FIXME: if the cell is a symbol, then a didSet could deal with updating the symbol value
            count = 1
          }
        case .gsub:
          result = ""
          var lastEnd = str.startIndex
          for m in str[range].matches(of: re) {
//            guard let r = Range(m.range, in: str) else { continue }
            let r = m.range
            result += str[lastEnd..<r.lowerBound]
            let matched = str[r]
            result += AWKRuntime.applyReplacement(repl, matched: matched)
            lastEnd = r.upperBound
            count += 1
          }
          result += str[lastEnd...]
      }

      return ValueCell(string: result)
    }
    //    try storeLValue(target, targetCell, n, x)
    return ValueCell(number: count)
  }

  // C: substr() — run.c
  func execSubstr(str: Expression, start: Expression, len: Expression?) throws -> Cell {
    let s = try eval(str).asString()
    let k = s.count
    if k == 0 { return EmptyCell() }
    
    var m = Int(try eval(start).getNumber())
    if m <= 0 { m = 1 }
    else if m > k + 1 { return EmptyCell() }
    
    let n: Int
    if let lenExpr = len {
      n = max(0, min(Int(try eval(lenExpr).getNumber()), k - m + 1))
    } else {
      n = k - m + 1
    }
    
    let startIdx = s.index(s.startIndex, offsetBy: m - 1, limitedBy: s.endIndex) ?? s.endIndex
    let endIdx   = s.index(startIdx, offsetBy: n, limitedBy: s.endIndex) ?? s.endIndex
    return ValueCell(string: String(s[startIdx..<endIdx]))
  }
  
  // C: split() — run.c
  func execSplit(str: Expression, arrName: String, sep: Expression?) throws -> Cell {
    let s = try eval(str).asString()
    //    var arr = resolveVar(arrName)
    
    var ee = [String:Cell]()
    
    let fs: String
    if let sepExpr = sep {
      if case .regexMatch(let pat) = sepExpr { fs = pat }
      else { fs = try eval(sepExpr).asString() }
    } else {
      fs = FS
    }
    
    let parts: [String]
    if s.isEmpty { parts = [] } else {
      if fs == " " {
        parts = s.components(separatedBy: .whitespaces).filter { !$0.isEmpty }
      } else if fs.count == 1 && fs != "" {
        let sep = Character(fs)
        parts = s.split(separator: sep, omittingEmptySubsequences: false).map(String.init)
      } else if fs.isEmpty {
        parts = s.map { String($0) }
      } else {
        if let re = try? Regex<Substring>(fixre(fs)) {
          //          parts = awkSplit(s, by: re).map { String($0) }
          parts = substringsBetweenMatches(in: s, matching: re).map { String($0) }
        } else {
          print("not a valid regex: \(fs)")
          parts = []
        }
      }

      for (i, p) in parts.enumerated() {
        let key = String(i + 1)
        // FIXME: can cache the convertability of strings to numbers for performance
        let c = ValueCell(string: p)
        ee[key] = c
      }
    }

    // FIXME: does this need to reset whatever the "resolved" value is?
    try storeVar(arrName, Dictionary(dict: ee))
    
    return ValueCell(number: parts.count)
  }
  
}

func substringsBetweenMatches(
    in s: String,
    matching re: Regex<Substring>
) -> [Substring] {
    var result: [Substring] = []

    var start = s.startIndex

    for match in s.matches(of: re) {
        let range = match.range
        result.append(s[start..<range.lowerBound])
        start = range.upperBound
    }

    // Text after the final match
  // FIXME: depending on the test, sometimes I want this test (start < s.endIndex)
  // and sometimes I don't : there are some weird split edge cases
  if start < s.endIndex || true { result.append(s[start..<s.endIndex]) }

    return result
}

// Walk an arbitrary regex string, find every bracket expression [...], and
// pass each one through cleanAWKCharacterClass so that invalid descending
// ranges (e.g. r-U) are stripped.  Everything outside bracket expressions —
// including escape sequences — is passed through unchanged.
func fixre(_ s: String) -> String {
    var result = ""
    var i = s.startIndex

    while i < s.endIndex {
        let ch = s[i]

        // Escape sequence: pass both characters through unchanged.
        if ch == "\\" {
            result.append(ch)
            let ni = s.index(after: i)
            if ni < s.endIndex {
                result.append(s[ni])
                i = s.index(after: ni)
            } else {
                i = ni
            }
            continue
        }

        // Start of a bracket expression.
        if ch == "[" {
            var classStr = "["
            var j = s.index(after: i)

            // Optional negation caret.
            if j < s.endIndex && s[j] == "^" {
                classStr.append("^")
                j = s.index(after: j)
            }

            // Collect the contents, remembering that the very first character
            // after "[" or "[^" may be "]" and is treated as a literal member,
            // not as the closing bracket.
            var firstInClass = true
            while j < s.endIndex {
                let c = s[j]
                if c == "]" && !firstInClass {
                    classStr.append("]")
                    j = s.index(after: j)
                    break
                }
                if c == "\\" {
                    classStr.append(c)
                    let nj = s.index(after: j)
                    if nj < s.endIndex {
                        classStr.append(s[nj])
                        j = s.index(after: nj)
                    } else {
                        j = nj
                    }
                    firstInClass = false
                    continue
                }
                classStr.append(c)
                j = s.index(after: j)
                firstInClass = false
            }

            result.append(contentsOf: cleanAWKCharacterClass(classStr))
            i = j
            continue
        }

        result.append(ch)
        i = s.index(after: i)
    }

    return result
}

func cleanAWKCharacterClass(_ s: String) -> String {
    let chars = Array(s)
    var out: [Character] = []

    var i = 0
    while i < chars.count {
        if i + 2 < chars.count,
           chars[i + 1] == "-",
           chars[i] != "[",
           chars[i + 2] != "]"
        {
            let a = chars[i]
            let b = chars[i + 2]

            let av = a.unicodeScalars.first!.value
            let bv = b.unicodeScalars.first!.value

            if av > bv {
                // invalid range: discard both endpoints and '-'
                i += 3
                continue
            }
        }

        out.append(chars[i])
        i += 1
    }

    return String(out)
}
