// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/

// AST-walking interpreter for AWK.
// Corresponds to run.c from one-true-awk, but operates on the Swift AST
// (AWKProgram / Statement / Expression) rather than the C Node* tree.

import CMigration
import Darwin
import Dispatch
import Synchronization

// MARK: - Call frame

// MARK: - AWK Executor

extension RuntimeState {

  func isclvar(_ s : String) -> Bool { // is s of form var=something ?
    guard let sf = s.first else { return false }
    guard sf.isLetter || sf == "_" else { return false }
    let k = s.split(separator: "=")
    guard k.count == 2 else { return false }
    guard (k[0].allSatisfy { $0.isLetter || $0.isWholeNumber || $0 == "_" }) else { return false }
    return true
  }

  func setclvar(_ ss : String) async throws { // set var=value from s
    let k = ss.split(separator: "=")
    let s = String(k[0])
    let p = try AWKRuntime.qstringDecode(String(k[1]))
    await setsym(s, ValueCell(string: p))
    DPRINTF("command line set \(s) to |\(p)|\n")
  }



// this function was copied from sed (process.swift) where it is caslled mf_gets
  /// this function gets the next line for processing from a list of files read sequentially
  /// it is also the awk function GETLINE
  func awkGets() async throws -> String? {
    while !quit {
      if nil != self.inp {
        // FIXME: should NR and FNR be incremented here or in the callers?
        do {
          if let got = self.inp!.next() {
//            self.linenum += 1
            return got
          }
          mf_close_file()
          continue
        }
      } else {
        // This is where the next file is opened
        if self.fileNdx >= ARGV.count {
          if hadAnInputFile {
            break
          }
 //          self.inp = FileDescriptor.standardInput.syncBytes.records(rs: RS).makeIterator()
        }
        if fileNdx < ARGC,
            let z = ARGV[String(fileNdx)],
           isclvar(z.asString()) {
          try await setclvar(z.asString())
          fileNdx += 1
          continue
        }
        
        if let i = try mf_next_file() {
          hadAnInputFile = true
          self.inp = i
        } else {
          break
        }
      }
    }
    mf_close_file()
    return nil
  }

  // close the current file so I can move to the next one
  func mf_close_file() {
    self.inp = nil
  }

  // copied from sed (process.swift)
  /// advances to the next input file in the list
  func mf_next_file() throws -> SyncRecordReader.Iterator? {
    repeat {
      if self.fileNdx >= ARGV.count {
        if hadAnInputFile {
          return nil
        }
        let z = FileDescriptor.standardInput.syncBytes.records(rs: RS).makeIterator()
        hadAnInputFile = true
        FILENAME = "stdin"
        FNR = 0
        return z
      }

      // get the first file and use it up
      guard let fnam = self.ARGV[String(fileNdx)]?.asString() else { fileNdx += 1; continue }
      fileNdx +=  1
      if fnam.isEmpty { continue}

      // open file
      if fnam == "-"  || fnam == "/dev/stdin" {
        FILENAME = "stdin"
        FNR = 0
        let k = FileDescriptor.standardInput.syncBytes
        let j = k.records(rs: RS)
        return j.makeIterator()
      } else {
        do {
          FILENAME = fnam
          FNR = 0
          return try FileDescriptor(forReading: fnam).syncBytes.records(rs: RS).makeIterator()
        } catch {
          // C: can't open file — main.c. A nonexistent/unreadable input filename is
          // fatal, not skippable; the getrec loop must propagate this (not swallow it
          // as ordinary EOF) so the process exits non-zero with this message.
          throw AWKRuntimeError("can't open file \(fnam)")
        }
      }
    } while true
    fatalError("cannot get here?")
  }

  // MARK: - Main entry point
  
  /// Run a parsed AWK program over the provided input files (or stdin if empty).
  // C: run() + getrec() loop — run.c / lib.c
  func run(_ program: AWKProgram, inputPaths: [String] = []) async throws {
    // Populate function table
    self.ARGC = 1+inputPaths.count
    self.ARGV["0"]=ValueCell(string: options.programName)
    for (i, x) in inputPaths.enumerated() {
      self.ARGV[String(i+1)] = ValueCell(string: x)
    }

    for fn in program.functions {
      // C: defn() — awkgram.y — redefining a function is a fatal, not a silent overwrite.
      if functions[fn.name] != nil {
        throw AWKRuntimeError("you can't define function \(fn.name) more than once")
      }
      functions[fn.name] = fn
    }
    
    // Range-pattern pairstack
    pairstack = Array(repeating: false, count: program.rules.count)
    
    // --- BEGIN blocks ---
    do {
      for stmts in program.beginRules {
        try await execBlock(stmts)
      }
    } catch AWKSignal.exit_(let code) {
      exitCode = code
      try await runEndBlocks(program)
      return
    } catch AWKSignal.next, AWKSignal.nextFile, AWKSignal.break_, AWKSignal.continue_ {
      // C: program() — run.c — there's no enclosing record loop in BEGIN to catch
      // these, so they're fatal here rather than silently doing nothing.
      throw AWKRuntimeError("illegal break, continue, next or nextfile from BEGIN")
    }

    // --- Per-record body ---
    if !program.rules.isEmpty || !program.endRules.isEmpty {
    getr:
      while let rec = try await awkGets() {
          NR += 1; FNR += 1
          setField(0, rec)
          
          for (idx, rule) in program.rules.enumerated() {
            do {
              if try await matchesPattern(rule.pattern, ruleIndex: idx) {
                if rule.body.isEmpty {
                  // no body → print $0
                  try await print_([.field(.number(0))], dest: nil)
                } else {
                  try await execBlock(rule.body)
                }
              }
            } catch AWKSignal.next { continue getr }
            catch AWKSignal.nextFile { mf_close_file();  break }
            catch AWKSignal.exit_(let code) {
              exitCode = code
              mf_close_file()
              try await runEndBlocks(program)
              return
            }
          }
        }
    }

    // --- END blocks ---
    try await runEndBlocks(program)
  }
  
  // C: program() END-block handling — run.c
  func runEndBlocks(_ program: AWKProgram) async throws {
    inEndBlock = true
    do {
      for stmts in program.endRules {
        try await execBlock(stmts)
      }
    } catch AWKSignal.exit_(let code) {
      exitCode = code
    } catch AWKSignal.next, AWKSignal.nextFile, AWKSignal.break_, AWKSignal.continue_ {
      throw AWKRuntimeError("illegal break, continue, next or nextfile from END")
    }
    inEndBlock = false
    await closeAll()
  }
  
  // MARK: - Pattern matching
  
  // C: pastat() + dopa2() — run.c
  func matchesPattern(_ pattern: PatternKind, ruleIndex: Int) async throws -> Bool {
    switch pattern {
      case .always:
        return true
      case .expression(let e):
        return try await eval(e).isTrue
        // dopa2() below
      case .range(let p1, let p2):
        if !pairstack[ruleIndex] {
          let start = try await eval(p1).isTrue
          if start { pairstack[ruleIndex] = true }
        }
        if pairstack[ruleIndex] {
          let done = try await eval(p2).isTrue
          if done { pairstack[ruleIndex] = false }
          return true
        }
        return false
    }
  }

  
  
  
  // MARK: - LValue resolution (returns the cell itself for mutation)
  
  // C: field() / array() / indirect() — run.c
  @discardableResult func evalLValue(_ lv: LValue, _ store : ((Cell) throws ->Cell)? = nil ) async throws -> Cell { // value, fldnum
    switch lv {
      case .variable(let name):
        // C: setfval() on NF — lib.c rejects negative NF before setlastfld() ever touches
        // fldtab, which otherwise underflows trying to build a negative-length array slice.
        if name == "NF", let store {
          let checkedStore: (Cell) throws -> Cell = { cell in
            let result = try store(cell)
            if result.getNumber() < 0 {
              throw AWKRuntimeError("cannot set NF to a negative value")
            }
            return result
          }
          return try resolveVar(name, checkedStore)
        }
        // Functions and variables share one namespace in awk — a declared function's own
        // name can never be read or assigned as a plain variable (checked centrally in
        // resolveVar, since plain reads reach it directly without going through evalLValue).
        // A name used as an array anywhere in the program (see staticArrayVariableNames())
        // can't also be assigned as a plain scalar — matches awk's own type checking,
        // e.g. `j = 4` when `j` is later used via `"x" in j` fails at the assignment,
        // not the `in` check. Function-local parameters are exempt (they're independent
        // of any global of the same name), and this must not reject the array-by-reference
        // write-back in execUserCall (which legitimately re-stores a Dictionary here) —
        // only an actual scalar result is disallowed.
        if let store, declaredArrayNames.contains(name),
           !(callStack.last?.paramNames.contains(name) ?? false) {
          let checkedStore: (Cell) throws -> Cell = { cell in
            let result = try store(cell)
            if !(result is Dictionary) {
              throw AWKRuntimeError("can't assign to \(name); it's an array name.")
            }
            return result
          }
          return try resolveVar(name, checkedStore)
        }
        // Dynamic complement to the static check above: a function parameter currently
        // bound to an array (Dictionary) — because an array was passed into this call,
        // possibly forwarded through a chain of pass-through calls — can't be overwritten
        // with a scalar either, even though pure textual scanning can't see that the
        // parameter aliases an array (that only becomes known at this specific call site).
        if let store, let frame = callStack.last, let i = frame.paramNames.firstIndex(of: name),
           frame.cells[i] is Dictionary {
          let checkedStore: (Cell) throws -> Cell = { cell in
            let result = try store(cell)
            if !(result is Dictionary) {
              throw AWKRuntimeError("can't assign to \(name); it's an array name.")
            }
            return result
          }
          return try resolveVar(name, checkedStore)
        }
        return try resolveVar(name, store)

      case .field(let e):
        // Field lvalue — we can't return a reference to an element of env.fields.
        // Instead, return a proxy: a cell whose value changes are applied via setField.
        // We wrap this in a FieldProxy approach: return a cell and post-assign it.
        // This is handled per-case in execAssign and incr/decr.
        // For the incr/decr case, we need the actual stored cell; use a field cell.
        let n = try fieldIndex(try await eval(e).getNumber())
        let val = makeFieldCell(n)
        if let store {
          let res = try store(val)
          setFieldCell(n, res)
          return res
        }
        return val

      case .element(let name, let keys):
        return try await resolveElement(name: name, keys: keys, store)

      case .indirect(let e):
        let n = try fieldIndex(try await eval(e).getNumber())
        let val = makeFieldCell(n)
        if let store {
          let res = try store(val)
          setFieldCell(n, res)
          return res
        }
        return val
    }
  }

  // MARK: - Variable / element resolution
  func storeVar(_ name : String, _ c : Cell) async throws {
    // Check built-in variables first
    // Check current call frame
    if var frame = callStack.last {
      if let i = frame.paramNames.firstIndex(of: name) {
        frame.cells[i]=c
        callStack[callStack.endIndex-1] = frame
        // FIXME: this is broken if the function callers uses a field or element value with a non-reentrant index
        if i < frame.callLVals.count, let lv = frame.callLVals[i] {
          try await evalLValue(lv) { r in c }
        }
        return
      }
    }
    setsym(name, c)
  }

  // C: setsymtab() + lookup() — tran.c
  func resolveVar(_ name: String, _ store : ((Cell) throws ->Cell)? ) throws -> Cell {
    // Functions and variables share one namespace in awk — a declared function's own
    // name can never be read or assigned as a plain variable, even from within its own
    // body (e.g. `function ShowMe() { ShowMe = 1 }`, or `dummy (1)` where the missing
    // call-parenthesis whitespace makes `dummy` a bareword variable reference rather
    // than a call). Function-local parameters are exempt.
    if functions[name] != nil,
       !(callStack.last?.paramNames.contains(name) ?? false) {
      if store != nil {
        throw AWKRuntimeError("can't assign to \(name); it's a function.")
      } else {
        throw AWKRuntimeError("can't read value of \(name); it's a function.")
      }
    }
    // Check built-in variables first
    // Check current call frame
    if var frame = callStack.last {
      if let i = frame.paramNames.firstIndex(of: name) {
        if let store {
          let res = try store(frame.cells[i])
          frame.cells[i]=res
          callStack[callStack.endIndex-1] = frame
        }
        return frame.cells[i] // either the read, or the post update value
      }
    }

    let old = symtab[name] ?? EmptyCell()
    if let store {
      let res = try store(old)
      setsym(name, res)
      return res
    }
    return old
  }
  
  // C: array() — run.c
  func resolveElement(name: String, keys: [Expression], _ store: ((Cell) throws->Cell)?) async throws -> Cell {
    // Functions and variables/arrays share one namespace in awk — a declared function name
    // can never be subscripted as an array (e.g. `foo[c]` when `foo` is `function foo(...)`).
    guard functions[name] == nil else {
      throw AWKRuntimeError("\(name) is a function, not an array")
    }
    let key = try await buildSubscriptKey(keys)
    var elres : Cell = EmptyCell()
    let _ = try resolveVar(name) { arr in
      if arr is Keyed {
        var ee = arr as! Keyed
        elres = ee[key] ?? EmptyCell()
        if let store {
          let res = try store(elres)
          ee[key]=res
          elres = res
          return ee as! any Cell
        }
      } else {
        if let store {
          elres = try store(EmptyCell())
          let ee = AwkDictionary()
          ee[key]=elres
          return Dictionary(dict: ee)
        }
        return EmptyCell()
      }
      return arr
    }
    return elres
  }
  
  // MARK: - Field proxy cells

  // C: fieldadr() — lib.c — real awk FATALs rather than silently growing fldtab (or
  // returning empty) for a field number that couldn't have come from a real record,
  // since a value like $40000000000000 would otherwise try to allocate a fields
  // array with tens of trillions of entries.
  func fieldIndex(_ raw: Double) throws -> Int {
    guard raw >= 0, raw <= Double(Int32.max) else {
      throw AWKRuntimeError("trying to access out of range field \(Int64(raw))")
    }
    return Int(raw)
  }

  // C: fieldadr() — lib.c
  func makeFieldCell(_ n: Int) -> Cell {
    //        if let existing = fieldCells[n] { return existing }
    let s = getField(n)
    let c = ValueCell(field: s)
    return c
  }
  
  // C: fieldadr() — lib.c
  func setFieldCell(_ n: Int, _ c : Cell) {
    setField(n, c.asString())
  }

  // MARK: - Assignment
  
  // C: assign() — run.c
  func execAssign(op: AssignOp, lv: LValue, rhs: Expression) async throws -> Cell {
    var rhsVal = try await eval(rhs)
    // FIXME: bury this in Cell
    // Gymnastics, because otherwise  x = NR (say) makes x the builtin, not the value of the builtin.
    if rhsVal is BuiltInNumber {
      rhsVal = ValueCell(number: rhsVal.getNumber())
    } else if rhsVal is BuiltInString {
      rhsVal = ValueCell(string: rhsVal.asString())
    }

    // Field assignment writes through to env.fields / env.record
    if case .field(let fe) = lv {
      let n = Int(try await eval(fe).getNumber())
      let cur = ValueCell(number: getField(n) == "" ? 0 : 0)
      let curStr = getField(n)
      let curNum = AWKRuntime.parseNum(curStr)
      let newVal = applyOp(op, lhsNum: curNum, lhsStr: curStr, rhs: rhsVal)
      setField(n, newVal.asString())
      _ = cur  // suppress warning
      return newVal
    }
    
    return try await evalLValue(lv) { target in
      return self.applyOp(op, lhsNum: target.getNumber(), lhsStr: target.asString(), rhs: rhsVal)
    }
  }
  
  // C: assign() operator switch — run.c
  func applyOp(_ op: AssignOp, lhsNum: Double, lhsStr: String, rhs: Cell) -> Cell {
    switch op {
      case .set:    return rhs
      case .addSet: return ValueCell(number: lhsNum + rhs.getNumber())
      case .subSet: return ValueCell(number: lhsNum - rhs.getNumber())
      case .mulSet: return ValueCell(number: lhsNum * rhs.getNumber())
      case .divSet:
        let d = rhs.getNumber()
        return ValueCell(number: d == 0 ? 0 : lhsNum / d)   // real code throws
      case .modSet:
        let d = rhs.getNumber()
        var i = 0.0; modf(lhsNum / d, &i)
        return ValueCell(number: lhsNum - d * i)
      case .powSet:
        return ValueCell(number: ipow(lhsNum, rhs.getNumber()))
    }
  }
  
  // MARK: - Power helper (matches C ipow for integer exponents)
  
  // C: ipow() — run.c
  func ipow(_ x: Double, _ exp: Double) -> Double {
    var intPart = 0.0
    if exp >= 0 && modf(exp, &intPart) == 0.0 {
      var result = 1.0; var n = Int(exp); var base = x
      while n > 0 { if n & 1 == 1 { result *= base }; base *= base; n >>= 1 }
      return result
    }
    return pow(x, exp)
  }
  
  // MARK: - Regex helper (extracts pattern string from an expression)
  
  // C: (no direct equivalent; extracts pattern string from an expression node)
  func regexPattern(_ e: Expression) async throws -> String {
    if case .regexMatch(let s) = e { return s }
    return try await eval(e).asString()
  }
  
  // MARK: - Print statement
  
  // C: printstat() — run.c
  func execPrint(kind: PrintKind, args: [Expression], dest: PrintDest?) async throws {
    let output: AWKFile
    switch dest {
      case .none:
        output = AWKFile(name: "/dev/stdout", mode: .write, handle: .standardOutput)
      case .redirect(let e):
        if options.safe { throw AWKRuntimeError("print > is unsafe") }
        let path = try await eval(e).asString()
        // C: openfile() — lib.c — an empty target (e.g. an uninitialized variable
        // used as the filename) is fatal, not silently treated as a real filename.
        if path.isEmpty { throw AWKRuntimeError("null file name in print or getline") }
        output = try await fileFor(name: path, mode: .write)
      case .append(let e):
        if options.safe { throw AWKRuntimeError("print >> is unsafe") }
        let path = try await eval(e).asString()
        if path.isEmpty { throw AWKRuntimeError("null file name in print or getline") }
        output = try await fileFor(name: path, mode: .append)
      case .pipe(let e):
        if options.safe { throw AWKRuntimeError("print | is unsafe") }
        let cmd = try await eval(e).asString()
        if cmd.isEmpty { throw AWKRuntimeError("null file name in print or getline") }
        output = try await fileFor(name: cmd, mode: .outputPipe)
    }

    switch kind {
      case .print:
        try await print_(args, dest: dest, to: output)
      case .printf:
        guard !args.isEmpty else { return }
        let fmtStr = try await eval(args[0]).asString()
        let result = try await format(fmtStr, args: Array(args.dropFirst()))
        try output.write(result)
    }
  }
  
  // C: printstat() output loop — run.c
  func print_(_ args: [Expression], dest: PrintDest?, to output: AWKFile? = nil) async throws {
    let out = output ?? AWKFile(name: "/dev/stdout", mode: .write, handle: .standardOutput)
    if args.isEmpty {
      ensureRecord()
      // $0 is "" until the first record is read (e.g. a bare `print` in BEGIN),
      // not an error condition — matches real awk, which just prints a blank line.
      try out.write((record ?? "") + ORS)
      return
    }
    var first = true
    for arg in args {
      if !first { try out.write(OFS) }
      let val = try await eval(arg)
      try out.write(val.asString(fmt: OFMT))
      first = false
    }
    try out.write(ORS)
  }
  
  // MARK: - Delete statement
  
  // C: awkdelete() — run.c
  func execDelete(_ lv: LValue) async throws {
    switch lv {
      case .variable(let name):
        // Whole-array delete must clear the existing Dictionary's keys in place rather than
        // replacing the cell with a fresh EmptyCell: if this array was passed into a function
        // by reference, the caller's variable shares the same underlying AwkDictionary, and
        // only an in-place clear (not a rebind) is visible on the caller's side too.
        let _ = try resolveVar(name) { ee in
          guard var keyed = ee as? Keyed else { return EmptyCell() }
          for k in keyed.keys { keyed[k] = nil }
          return ee
        }

      case .element(let name, let keys):
        let key = try await buildSubscriptKey(keys)
        let _ = try resolveVar(name) {ee in
          if ee is Keyed {
            var aa = ee as! Keyed
            aa[key]=nil
            return aa as! any Cell
          }
          return ee
        }
      default:
        throw AWKRuntimeError("delete requires a variable or array element")
    }
  }
  
  // MARK: - User-defined function call
  
  // C: call() — run.c
  func execUserCall(name: String, argExprs: [Expression]) async throws -> Cell {
    guard let fn = functions[name] else {
      throw AWKRuntimeError("calling undefined function '\(name)'")
    }
    // C: call() — run.c — calling with more arguments than declared is a non-fatal
    // warning; the call still proceeds, using only the declared parameters.
    if argExprs.count > fn.params.count {
      WARNING("function \(name) called with \(argExprs.count) args, uses only \(fn.params.count)")
    }
    // Evaluate actual arguments
    var cells: [Cell] = []
    var lvals: [LValue?] = []
    for argExpr in argExprs {
      let k = argExpr.asLValue()
      lvals.append(k)
      let c = try await eval(argExpr)
      // FIXME: did I muck this up?
      cells.append(c)
    }
    // Pad with empty cells for any unspecified parameters
    while cells.count < fn.params.count { cells.append(EmptyCell()) }
    // Extra locals beyond defined params
    // (one-true-awk uses extra params as local variables)
    
    let frame = CallFrame(funcName: name, paramNames: fn.params, cells: cells, callLVals: lvals)
    callStack.append(frame)

    var retval : Cell
    do {
      do {
        try await execBlock(fn.body)
        retval = callStack.last?.retval ?? EmptyCell()
      } catch AWKSignal.`return` {
        retval = self.retval
      }
    } catch {
      callStack.removeLast()
      throw error
    }

    // Arrays are passed by reference in awk. If an argument was a bare variable (or array
    // element) and the corresponding parameter turned into/held an array inside the function,
    // write that array back to the caller's storage so the two stay aliased. This matters
    // most the first time an uninitialized global is passed into a function to be filled in
    // (e.g. `function set(a, s) {...}; set(dc, "...")`) — until now the array built inside
    // the call was thrown away when the frame popped, leaving the caller's array empty.
    let finalCells = callStack.last!.cells
    callStack.removeLast()
    for (lv, cell) in zip(lvals, finalCells) {
      guard let lv, cell is Keyed else { continue }
      _ = try await evalLValue(lv) { _ in cell }
    }

    return retval
  }

  // MARK: - Builtin function call
  
  // C: bltin() — run.c
  func execBuiltin(id: AWKBuiltinID, args: [Expression]) async throws -> Cell {
    switch id {
      case .length:
        if args.isEmpty {
          ensureFields()
          return ValueCell(number: (record ?? "").count)
        }
        // C: bltin() — run.c — extra length() arguments are a non-fatal warning;
        // execution continues using just the first argument.
        if args.count > 1 {
          WARNING("function has too many arguments")
        }
        let c = try await eval(args[0])
        return ValueCell(number: c.length() )
        
      case .sqrt:
        return ValueCell(number: sqrt(try await eval(args[0]).getNumber()))

      case .exp:
        return ValueCell(number: exp(try await eval(args[0]).getNumber()))

      case .log:
        return ValueCell(number: log(try await eval(args[0]).getNumber()))
        
      case .int_:
        var intPart = 0.0; modf(try await eval(args[0]).getNumber(), &intPart)
        return ValueCell(number: intPart)
        
      case .system:
        if options.safe { throw AWKRuntimeError("system is unsafe") }
        let cmd = try await eval(args[0]).asString()
        fflush(stdout)
        var result = -1


          let p = DarwinProcess()
          if let r = try? await p.run("/bin/sh", args: "-c", cmd, output: (nil, nil)) {
            result = Int(awkSystemStatus(r.rawStatus))
          }

        return ValueCell(number: Double(result))

      case .rand:
//        let r = arc4random()
        let r = drand48()
//        let r2 = Darwin.random()
        return ValueCell(number: r )

      case .srand:
        let old = srand_seed
        let seed: Double
        if args.isEmpty { seed = Double(DateTime().timeInterval) }
        else            { seed = try await eval(args[0]).getNumber() }
        srand_seed = Int(seed)
        srand48(srand_seed)
        return ValueCell(number: Double(old))
        
      case .sin:
        return ValueCell(number: sin(try await eval(args[0]).getNumber()))

      case .cos:
        return ValueCell(number: cos(try await eval(args[0]).getNumber()))

      case .atan2:
        let y = try await eval(args[0]).getNumber()
        let x = args.count > 1 ? try await eval(args[1]).getNumber() : 1.0
        return ValueCell(number: atan2(y, x))
        
      case .toupper:
        return ValueCell(string: try await eval(args[0]).asString().uppercased())

      case .tolower:
        return ValueCell(string: try await eval(args[0]).asString().lowercased())

      case .fflush:
        if args.isEmpty {
          flushAll()
        } else {
          let name = try await eval(args[0]).asString()
          if name.isEmpty { flushAll() }
          else if let _ = openFiles.first(where: { $0.name == name }) {
            // FIXME: is there anything to do here?
//            try? f.handle.synchronize()
          }
        }
        return ValueCell(number: 0)
    }
  }
  
  // MARK: - Getline
  
  // C: awkgetline() — run.c
  func execGetline(lv: LValue?)  async throws -> Cell {
    // Bare getline — read next record from current input (stdin)
    // For simplicity, read from stdin
    guard let line = try await awkGets() else {
      return ValueCell(number: 0)
    }
    if let lv {
      // Like a field, a getline-assigned variable is a "numeric string" (strnum) if it
      // looks like a number — ValueCell(field:) sets that sticky flag; a plain
      // ValueCell(string:) would not, making later numeric comparisons wrongly fall back
      // to string comparison for data that's genuinely numeric input.
      let _ = try await evalLValue(lv) {_ in
        return ValueCell(field: line)
      }
    } else {
      NR += 1; FNR += 1
      setField(0, line)
    }
    return ValueCell(number: 1)
  }

  // C: awkgetline() file-variant — run.c
  func readLineInto(lv: LValue?, from file: AWKFile, updates0: Bool) async throws -> Cell {
    guard let line = try file.readRecord(rs: RS) else { return ValueCell(number: 0) }
    if let lv {
      // getline's own result must always be the numeric success indicator (1), never the
      // assigned value itself — returning the target's new Cell here would make `> 0`
      // comparisons coerce the read line to a number/string instead of testing success,
      // e.g. a line starting with a space would compare as less than "0" and wrongly look
      // like failure, ending the read loop after just one (or zero) lines.
      // ValueCell(field:) (not ValueCell(string:)) so the read line gets numeric-string
      // (strnum) treatment when it looks like a number, matching real awk's getline.
      _ = try await evalLValue(lv) { _ in ValueCell(field: line) }
    } else if updates0 {
      setField(0, line)
    }
    return ValueCell(number: 1)
  }
  
  // C: readrec() — lib.c
  func readln(from fh: FileDescriptor) throws -> String? {
    // Inefficient but simple: read byte-by-byte until RS
    var line = ""
    let sep: UInt8 = RS.first.map { $0.asciiValue ?? 10 } ?? 10
    while true {
      let data = try fh.readAvailableBytes()
      guard !data.isEmpty else { return line.isEmpty ? nil : line }
      for byte in data {
        if byte == sep { return line }
        line.append(Character(Unicode.Scalar(byte)))
      }
    }
  }
  
  // MARK: - String operations
  
  // C: sub() — run.c
  func execSub(kind: SubKind, reExpr: Expression, replExpr: Expression, target: LValue) async throws -> Cell {
    let pat = try await regexPattern(reExpr)
    let repl = try await eval(replExpr).asString()
    var count = 0
    try await evalLValue(target) { targetCell in
      let str = targetCell.asString()

      var result : String = str   // default: no match leaves target unchanged

      let re = try AWKRuntime.makeRegex(pat)
      let ns = str
      let range = str.startIndex ..< str.endIndex

      switch kind {
        case .sub:
          // FIXME: do I need the range?
          if let m = try re.firstMatch(in: str[range]) {
            let matched = ns[m.range]
            let replacement = AWKRuntime.applyReplacement(repl, matched: Substring(matched))
            result = ns.replacingCharacters(in: m.range, with: replacement)
            // FIXME: if the cell is a symbol, then a didSet could deal with updating the symbol value
            count = 1
          }
        case .gsub:
          // Matches AWK's gsub semantics for nullable patterns (e.g. /a*/): a zero-length
          // match sitting exactly at the end of the previous applied match is suppressed
          // (its character is left for the next match's gap-copy, or the trailing copy,
          // to carry through untouched) rather than triggering another replacement, which
          // is what real awk does but Swift's matches(of:) does not. Matches are computed
          // once over the whole string here (rather than via repeated substring searches)
          // so that anchors like ^ keep referring to the true start of the string.
          result = ""
          var lastEnd = str.startIndex
          var lastMatchEnd: String.Index? = nil
          for m in str.matches(of: re) {
            let r = m.range
            if r.isEmpty && lastMatchEnd == r.lowerBound { continue }
            result += str[lastEnd..<r.lowerBound]
            result += AWKRuntime.applyReplacement(repl, matched: str[r])
            count += 1
            lastEnd = r.upperBound
            lastMatchEnd = r.upperBound
          }
          result += str[lastEnd...]
      }

      return ValueCell(string: result)
    }
    //    try storeLValue(target, targetCell, n, x)
    return ValueCell(number: count)
  }

  // C: substr() — run.c
  func execSubstr(str: Expression, start: Expression, len: Expression?) async throws -> Cell {
    let s = try await eval(str).asString()
    let k = s.count
    if k == 0 { return EmptyCell() }
    
    var m = Int(try await eval(start).getNumber())
    if m <= 0 { m = 1 }
    else if m > k + 1 { return EmptyCell() }
    
    let n: Int
    if let lenExpr = len {
      n = max(0, min(Int(try await eval(lenExpr).getNumber()), k - m + 1))
    } else {
      n = k - m + 1
    }
    
    let startIdx = s.index(s.startIndex, offsetBy: m - 1, limitedBy: s.endIndex) ?? s.endIndex
    let endIdx   = s.index(startIdx, offsetBy: n, limitedBy: s.endIndex) ?? s.endIndex
    return ValueCell(string: String(s[startIdx..<endIdx]))
  }
  
  // C: split() — run.c
  func execSplit(str: Expression, arrName: String, sep: Expression?) async throws -> Cell {
    let s = try await eval(str).asString()
    let ee = AwkDictionary()

    let fs: String
    let isRegexLiteral: Bool
    if let sepExpr = sep {
      if case .regexMatch(let pat) = sepExpr { fs = pat; isRegexLiteral = true }
      else { fs = try await eval(sepExpr).asString(); isRegexLiteral = false }
    } else {
      fs = FS
      isRegexLiteral = false
    }

    let parts: [String]
    if s.isEmpty { parts = [] } else {
      // Only the bare string " " gets awk's special "collapse runs of whitespace" treatment.
      // A regex literal that happens to match a single space (e.g. / /) must split on each
      // literal space character individually, producing empty fields between consecutive ones.
      if fs == " " && !isRegexLiteral {
        parts = s.components(separatedBy: .whitespaces).filter { !$0.isEmpty }
      } else if fs.count == 1 && fs != "" {
        let sep = Character(fs)
        parts = s.split(separator: sep, omittingEmptySubsequences: false).map(String.init)
      } else if fs.isEmpty {
        parts = s.map { String($0) }
      } else {
        if let re = try? Regex<Substring>(fixre(fs)) {
          //          parts = awkSplit(s, by: re).map { String($0) }
          parts = substringsBetweenMatches(in: s, matching: re).map { String($0) }
        } else {
          print("not a valid regex: \(fs)")
          parts = []
        }
      }

      for (i, p) in parts.enumerated() {
        let key = String(i + 1)
        // FIXME: can cache the convertability of strings to numbers for performance
        let c = ValueCell(string: p)
        ee[key] = c
      }
    }

    try await storeVar(arrName, Dictionary(dict: ee))
    return ValueCell(number: parts.count)
  }


  /// The exit status using the convention awk's `system()` uses: `WEXITSTATUS()` for a
  /// normal exit, or `WTERMSIG() + 256` for death by signal (plus another `256` if the
  /// process also dumped core). This differs from `code`'s shell `128 + signal` convention.
  public func awkSystemStatus(_ rawStatus : Int32) -> Int32 {
    if WIFEXITED(rawStatus) { return WEXITSTATUS(rawStatus) }
    if WIFSIGNALED(rawStatus) {
      var s = WTERMSIG(rawStatus) + 256
      if rawStatus & 0o200 != 0 { s += 256 }  // WCOREDUMP
      return s
    }
    return rawStatus
  }

}

func substringsBetweenMatches(
    in s: String,
    matching re: Regex<Substring>
) -> [Substring] {
    var result: [Substring] = []

    var start = s.startIndex

    for match in s.matches(of: re) {
        let range = match.range
        result.append(s[start..<range.lowerBound])
        start = range.upperBound
    }

    // Text after the final match
  // FIXME: depending on the test, sometimes I want this test (start < s.endIndex)
  // and sometimes I don't : there are some weird split edge cases
  if start < s.endIndex || true { result.append(s[start..<s.endIndex]) }

    return result
}

// Walk an arbitrary regex string, find every bracket expression [...], and
// pass each one through cleanAWKCharacterClass so that invalid descending
// ranges (e.g. r-U) are stripped.  Everything outside bracket expressions —
// including escape sequences — is passed through unchanged.
func fixre(_ s: String) -> String {
    var result: [Character] = []
    // Index into `result` where the most recently completed atom begins —
    // i.e. what a following quantifier (*, +, ?, {n,m}) would apply to.
    var atomStart = 0
    var i = s.startIndex

    while i < s.endIndex {
        let ch = s[i]

        // Escape sequence.
        if ch == "\\" {
            atomStart = result.count
            let ni = s.index(after: i)
            // Octal escape (\d, \dd, \ddd, 1-3 octal digits) — matches
            // one-true-awk's quoted() in b.c, which treats *any* leading
            // octal digit (0-7) this way. Swift's Regex only recognizes
            // \0dd as octal and treats \1-\9 as backreferences, so \141
            // (='a') and \60 (='0') would otherwise fail to match.
            if ni < s.endIndex, let d0 = s[ni].wholeNumberValue, (0...7).contains(d0) {
                var n = d0
                var j = s.index(after: ni)
                var digits = 1
                while digits < 3, j < s.endIndex, let d = s[j].wholeNumberValue, (0...7).contains(d) {
                    n = n * 8 + d
                    j = s.index(after: j)
                    digits += 1
                }
                if let scalar = Unicode.Scalar(n) {
                    result.append(contentsOf: regexEscapeLiteral(Character(scalar)))
                }
                i = j
                continue
            }
            // Otherwise pass both characters through unchanged.
            result.append(ch)
            if ni < s.endIndex {
                result.append(s[ni])
                i = s.index(after: ni)
            } else {
                i = ni
            }
            continue
        }

        // Start of a bracket expression.
        if ch == "[" {
            atomStart = result.count
            var classStr = "["
            var j = s.index(after: i)

            // Optional negation caret.
            if j < s.endIndex && s[j] == "^" {
                classStr.append("^")
                j = s.index(after: j)
            }

            // Collect the contents, remembering that the very first character
            // after "[" or "[^" may be "]" and is treated as a literal member,
            // not as the closing bracket.
            var firstInClass = true
            while j < s.endIndex {
                let c = s[j]
                if c == "]" && !firstInClass {
                    classStr.append("]")
                    j = s.index(after: j)
                    break
                }
                // POSIX equivalence class [=x=] inside a bracket expression — expand to
                // the base character plus its precomposed accented Latin-1 variants.
                // Swift's Regex treats [=x=] as a literal set of just '=' and 'x' (no real
                // collation equivalence), so without this a class like [[=a=][=A=]...]
                // never matches ä, Ä, etc. as one-true-awk's locale-aware version would.
                if c == "[", s.index(after: j) < s.endIndex, s[s.index(after: j)] == "=" {
                    let afterEq = s.index(j, offsetBy: 2)
                    let afterBase = afterEq < s.endIndex ? s.index(after: afterEq) : nil
                    if let afterBase, afterBase < s.endIndex, s[afterBase] == "=",
                       s.index(after: afterBase) < s.endIndex, s[s.index(after: afterBase)] == "]" {
                        for lit in equivalenceClassVariants(s[afterEq]) {
                            if "]^-\\".contains(lit) { classStr.append("\\") }
                            classStr.append(lit)
                        }
                        j = s.index(after: s.index(after: afterBase))
                        firstInClass = false
                        continue
                    }
                }
                if c == "\\" {
                    let nj = s.index(after: j)
                    // Octal escape (\d, \dd, \ddd) inside a bracket expression — same
                    // one-true-awk quoted() semantics applied outside brackets above.
                    // Swift's Regex only recognizes \0dd as octal even inside a class,
                    // so \300 would otherwise fail to parse; convert to the literal
                    // character instead (escaping it if it would be class-special).
                    if nj < s.endIndex, let d0 = s[nj].wholeNumberValue, (0...7).contains(d0) {
                        var n = d0
                        var k = s.index(after: nj)
                        var digits = 1
                        while digits < 3, k < s.endIndex, let d = s[k].wholeNumberValue, (0...7).contains(d) {
                            n = n * 8 + d
                            k = s.index(after: k)
                            digits += 1
                        }
                        if let scalar = Unicode.Scalar(n) {
                            let lit = Character(scalar)
                            if "]^-\\".contains(lit) { classStr.append("\\") }
                            classStr.append(lit)
                        }
                        j = k
                        firstInClass = false
                        continue
                    }
                    classStr.append(c)
                    if nj < s.endIndex {
                        classStr.append(s[nj])
                        j = s.index(after: nj)
                    } else {
                        j = nj
                    }
                    firstInClass = false
                    continue
                }
                classStr.append(c)
                j = s.index(after: j)
                firstInClass = false
            }

            result.append(contentsOf: cleanAWKCharacterClass(classStr))
            i = j
            continue
        }

        // Parenthesized group — track balanced depth (skipping escaped
        // parens) so the whole group counts as a single atom for a
        // following quantifier, matching how the {n}* fixup below decides
        // what to wrap.
        if ch == "(" {
            let groupStart = result.count
            result.append(ch)
            i = s.index(after: i)
            var depth = 1
            while i < s.endIndex, depth > 0 {
                let c2 = s[i]
                if c2 == "\\" {
                    result.append(c2)
                    i = s.index(after: i)
                    if i < s.endIndex { result.append(s[i]); i = s.index(after: i) }
                    continue
                }
                if c2 == "(" { depth += 1 }
                if c2 == ")" { depth -= 1 }
                result.append(c2)
                i = s.index(after: i)
            }
            atomStart = groupStart
            continue
        }

        // Interval bound: {n}, {n,}, or {n,m} — a "duplicated RE" per POSIX
        // ERE. Swift's Regex refuses to parse a *second* quantifier stacked
        // directly onto one of these (e.g. `b{0}*`), even though
        // one-true-awk's own hand-rolled regex engine accepts it leniently
        // ({0}* collapses to the atom's zero-width-only form; {0,}* to
        // plain `*`). Wrap the interval-quantified atom in a non-capturing
        // group so the following quantifier applies to the group instead
        // of re-quantifying an already-quantified atom.
        if ch == "{" {
            var j = s.index(after: i)
            var braceContent = ""
            while j < s.endIndex, s[j] != "}" {
                braceContent.append(s[j])
                j = s.index(after: j)
            }
            let isValidBound = !braceContent.isEmpty
                && braceContent.allSatisfy { $0.isNumber || $0 == "," }
                && braceContent.filter { $0 == "," }.count <= 1
            if j < s.endIndex, isValidBound {
                let afterBrace = s.index(after: j)
                result.append("{")
                result.append(contentsOf: braceContent)
                result.append("}")
                if afterBrace < s.endIndex, "*+?{".contains(s[afterBrace]) {
                    result.insert(contentsOf: "(?:", at: atomStart)
                    result.append(")")
                }
                i = afterBrace
                atomStart = result.count
                continue
            }
            // Not a valid interval (e.g. a literal '{' with no matching
            // bound) — fall through and treat '{' as an ordinary character.
        }

        atomStart = result.count
        result.append(ch)
        i = s.index(after: i)
    }

    return String(result)
}

// Escapes a decoded literal character (e.g. from an octal escape) so it's
// inserted into the regex pattern as itself, not as a metacharacter.
func regexEscapeLiteral(_ c: Character) -> String {
    ".^$|()[]{}*+?\\".contains(c) ? "\\\(c)" : String(c)
}

// Latin-1 accented variants sharing a base letter's primary collation weight —
// covers what a real locale's [=x=] equivalence class matches in practice for
// Western European text (see fixre's bracket-expression handling above).
private let latin1EquivalenceClasses: [Character: String] = [
    "a": "aàáâãäå", "A": "AÀÁÂÃÄÅ",
    "e": "eèéêë",   "E": "EÈÉÊË",
    "i": "iìíîï",   "I": "IÌÍÎÏ",
    "o": "oòóôõöø", "O": "OÒÓÔÕÖØ",
    "u": "uùúûü",   "U": "UÙÚÛÜ",
    "y": "yýÿ",     "Y": "YÝ",
    "c": "cç",      "C": "CÇ",
    "n": "nñ",      "N": "NÑ",
]

func equivalenceClassVariants(_ base: Character) -> String {
    latin1EquivalenceClasses[base] ?? String(base)
}

func cleanAWKCharacterClass(_ s: String) -> String {
    let chars = Array(s)
    var out: [Character] = []

    var i = 0
    while i < chars.count {
        if i + 2 < chars.count,
           chars[i + 1] == "-",
           chars[i] != "[",
           chars[i + 2] != "]"
        {
            let a = chars[i]
            let b = chars[i + 2]

            let av = a.unicodeScalars.first!.value
            let bv = b.unicodeScalars.first!.value

            if av > bv {
                // invalid range: discard both endpoints and '-'
                i += 3
                continue
            }
        }

        out.append(chars[i])
        i += 1
    }

    return String(out)
}
