// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/

import CMigration

extension RuntimeState {
  
  // MARK: - Statement execution
  
  // C: program() block loop — run.c
  func execBlock(_ stmts: [Statement]) throws {
    for stmt in stmts { try exec(stmt) }
  }
  
  // C: execute() — run.c  (ifstat / whilestat / dostat / forstat / instat / jump)
  func exec(_ stmt: Statement) throws {
    switch stmt {
      case .empty: break
        
      case .expression(let e):
        _ = try eval(e)
        
      case .block(let stmts):
        try execBlock(stmts)
        
      case .print_(let kind, let args, let dest):
        try execPrint(kind: kind, args: args, dest: dest)
        
      case .delete_(let lv):
        try execDelete(lv)
        
      case .if_(let cond, let then, let else_):
        if try eval(cond).isTrue {
          try exec(then)
        } else if let e = else_ {
          try exec(e)
        }
        
      case .while_(let cond, let body):
        while try eval(cond).isTrue {
          do { try exec(body) }
          catch AWKSignal.break_ { return }
          catch AWKSignal.continue_ { /* next iteration */ }
        }
        
      case .doWhile(let body, let cond):
        repeat {
          do { try exec(body) }
          catch AWKSignal.break_ { return }
          catch AWKSignal.continue_ { /* next iteration */ }
        } while try eval(cond).isTrue
        
      case .for_(let init_, let cond, let incr, let body):
        if let i = init_ { try exec(i) }
        while true {
          if let c = cond, !(try eval(c).isTrue) { break }
          do { try exec(body) }
          catch AWKSignal.break_ { return }
          catch AWKSignal.continue_ { /* fall through to increment */ }
          if let inc = incr { try exec(inc) }
        }
        
      case .forIn(let varName, let arrName, let body):
        let arrCell = resolveVar(arrName)
        guard arrCell is Dictionary else { return }
        
        // Snapshot keys to allow modification during iteration
        let aa = (arrCell as! Dictionary).dict
        let keys = Array(aa.keys)
        for key in keys {
          guard let _ = aa[key] else { continue }
          storeVar(varName, ValueCell(string: key))
          do { try exec(body) }
          catch AWKSignal.break_ { return }
          catch AWKSignal.continue_ { /* next key */ }
        }
        
      case .next:
        throw AWKSignal.next
        
      case .nextFile:
        throw AWKSignal.nextFile
        
      case .exit_(let e):
        if let e {
          let code = try eval(e).getNumber()
          throw AWKSignal.exit_(Int32(code))
        }
        throw AWKSignal.exit_(exitCode)
        
      case .return_(let e):
        let cell = e != nil ? (try eval(e!)) : EmptyCell()
        throw AWKSignal.`return`(cell)
        
      case .break_:
        throw AWKSignal.break_
        
      case .continue_:
        throw AWKSignal.continue_
    }
  }
  
  // MARK: - Expression evaluation
  
  // C: execute() — run.c  (arith / relop / boolop / matchop / condexpr / cat / incrdecr / etc.)
  func eval(_ expr: Expression) throws -> Cell {
    switch expr {
        
        // --- Literals ---
      case .number(let n):
        return ValueCell(number: n)
        
      case .string(let s):
        return ValueCell(string: s)
        
      case .regexMatch(let pat):
        // Bare /re/ → match against $0
        let s = getField(0)
        let matched = (try? AWKRuntime.match(pattern: pat, in: s)) != nil
        return ValueCell(number: matched ? 1 : 0)
        
        // --- Variables ---
      case .variable(let name):
        return resolveVar(name)
        
      case .argument(let i):
        if let frame = callStack.last, i < frame.cells.count { return frame.cells[i] }
        throw AWKRuntimeError("function argument \(i) out of range")
        
      case .varnf:
        // should be  fldbld()
        ensureFields()
        return symtab["NF"]!
        
      case .field(let e):
        let n = Int(try eval(e).getNumber())
        let s = getField(n)
        let c = ValueCell(string: s)
        //          if AWKRuntime.isNumber(s) { c.numVal = AWKRuntime.parseNum(s); c.hasNum = true }
        return c
        
      case .element(let name, let keys):
        return try resolveElement(name: name, keys: keys)
        
        // --- Assignment ---
      case .assign(let op, let lv, let rhs):
        return try execAssign(op: op, lv: lv, rhs: rhs)
        
        // --- Ternary ---
      case .ternary(let cond, let then, let else_):
        return try eval(cond).isTrue ? eval(then) : eval(else_)
        
        // --- Logical (short-circuit) ---
      case .logicalOr(let a, let b):
        return ValueCell(number: (try eval(a).isTrue || eval(b).isTrue) ? 1 : 0)
        
      case .logicalAnd(let a, let b):
        return ValueCell(number: (try eval(a).isTrue && eval(b).isTrue) ? 1 : 0)
        
        // --- Comparison ---
      case .equal(let a, let b):
        let x = try eval(a), y = try eval(b)
        return ValueCell(number: AWKRuntime.compare(x, y, convfmt: CONVFMT) == 0 ? 1 : 0)
        
      case .notEqual(let a, let b):
        let x = try eval(a)
        let y = try eval(b)
        return ValueCell(number: AWKRuntime.compare(x, y, convfmt: CONVFMT) != 0 ? 1 : 0)
        
      case .lessThan(let a, let b):
        let x = try eval(a), y = try eval(b)
        return ValueCell(number: AWKRuntime.compare(x, y, convfmt: CONVFMT) < 0 ? 1 : 0)
        
      case .lessEqual(let a, let b):
        let x = try eval(a), y = try eval(b)
        return ValueCell(number: AWKRuntime.compare(x, y, convfmt: CONVFMT) <= 0 ? 1 : 0)
        
      case .greaterThan(let a, let b):
        let x = try eval(a), y = try eval(b)
        return ValueCell(number: AWKRuntime.compare(x, y, convfmt: CONVFMT) > 0 ? 1 : 0)
        
      case .greaterEqual(let a, let b):
        let x = try eval(a), y = try eval(b)
        return ValueCell(number: AWKRuntime.compare(x, y, convfmt: CONVFMT) >= 0 ? 1 : 0)
        
      case .patternMatch(let e, let re):
        let s = try eval(e).asString()
        let pat = try regexPattern(re)
        let matched = (try? AWKRuntime.match(pattern: pat, in: s)) != nil
        return ValueCell(number: matched ? 1 : 0)
        
      case .patternNotMatch(let e, let re):
        let s = try eval(e).asString()
        let pat = try regexPattern(re)
        let matched = (try? AWKRuntime.match(pattern: pat, in: s)) != nil
        return ValueCell(number: matched ? 0 : 1)
        
      case .inArray(let e, let arrName):
        fatalError("unimplmented inArray")
        /*
         let key = try eval(e).asString()
         let arr = resolveVar(arrName)
         return Cell(number: arr.array?[key] != nil ? 1 : 0)
         */
        
      case .inArrayTuple(let exprs, let arrName):
        fatalError("unimplmented inArrayTuple")
        /*
         let parts = try exprs.map { try eval($0).asString() }
         let key = subscriptKey(parts)
         let arr = resolveVar(arrName)
         return Cell(number: arr.array?[key] != nil ? 1 : 0)
         */
        
        // --- Getline ---
      case .getline(let lv):
        return try execGetline(lv: lv)
        
      case .getlineFrom(let lv, let src):
        let path = try eval(src).asString()
        let file = try fileFor(name: path, mode: .read)
        return try readLineInto(lv: lv, from: file, updates0: true)
        
      case .getlinePipe(let lv, let cmd):
        let cmdStr = try eval(cmd).asString()
        let file = try fileFor(name: cmdStr, mode: .inputPipe)
        return try readLineInto(lv: lv, from: file, updates0: false)
        
        // --- Arithmetic ---
      case .concat(let a, let b):
        let sa = try eval(a).asString()
        let sb = try eval(b).asString()
        return ValueCell(string: sa + sb)
        
      case .add(let a, let b):
        return ValueCell(number: try eval(a).getNumber() + eval(b).getNumber())
        
      case .subtract(let a, let b):
        return ValueCell(number: try eval(a).getNumber() - eval(b).getNumber())
        
      case .multiply(let a, let b):
        return ValueCell(number: try eval(a).getNumber() * eval(b).getNumber())
        
      case .divide(let a, let b):
        let denom = try eval(b).getNumber()
        if denom == 0 { throw AWKRuntimeError("division by zero") }
        return ValueCell(number: try eval(a).getNumber() / denom)
        
      case .modulo(let a, let b):
        let denom = try eval(b).getNumber()
        if denom == 0 { throw AWKRuntimeError("division by zero in mod") }
        let num = try eval(a).getNumber()
        var intPart = 0.0; modf(num / denom, &intPart)
        return ValueCell(number: num - denom * intPart)
        
      case .power(let a, let b):
        let base = try eval(a).getNumber()
        let exp  = try eval(b).getNumber()
        return ValueCell(number: ipow(base, exp))
        
      case .negate(let e):
        return ValueCell(number: -(try eval(e).getNumber()))
        
      case .unaryPlus(let e):
        return ValueCell(number: try eval(e).getNumber())
        
      case .logicalNot(let e):
        return ValueCell(number: try eval(e).isTrue ? 0 : 1)
        
        // --- Increment / decrement ---
      case .preIncrement(let lv):
        let c = try evalLValue(lv)
        let k = ValueCell(number: c.getNumber() + 1)
        try storeLValue(lv, k)
        return k
        
      case .preDecrement(let lv):
        let c = try evalLValue(lv)
        let k = ValueCell(number: c.getNumber() - 1)
        try storeLValue(lv, k)
        return k
        
      case .postIncrement(let lv):
        let c = try evalLValue(lv)
        let old = c.getNumber()
        let k = ValueCell(number: old + 1)
        try storeLValue(lv, k)
        return c
        
      case .postDecrement(let lv):
        let c = try evalLValue(lv)
        let old = c.getNumber()
        let k = ValueCell(number: old - 1)
        try storeLValue(lv, k)
        return c
        
        // --- User-defined function call ---
      case .userCall(let name, let args):
        return try execUserCall(name: name, argExprs: args)
        
        // --- Builtin function call ---
      case .builtinCall(let id, let args):
        return try execBuiltin(id: id, args: args)
        
        // --- String operations ---
      case .sprintfExpr(let args):
        guard !args.isEmpty else { return EmptyCell() }
        let fmtStr = try eval(args[0]).asString()
        return ValueCell(string: try format(fmtStr, args: Array(args.dropFirst())))
        
      case .subExpr(let kind, let reExpr, let replExpr, let target):
        return try execSub(kind: kind, reExpr: reExpr, replExpr: replExpr, target: target)
        
      case .substrExpr(let str, let start, let len):
        return try execSubstr(str: str, start: start, len: len)
        
      case .splitExpr(let str, let arrName, let sep):
        return try execSplit(str: str, arrName: arrName, sep: sep)
        
      case .indexExpr(let hay, let needle):
        let h = try eval(hay).asString()
        let n = try eval(needle).asString()
        if n.isEmpty { return ValueCell(number: 0) }
        if let r = h.range(of: n) {
          let off = h.distance(from: h.startIndex, to: r.lowerBound)
          return ValueCell(number: Double(off + 1))   // 1-based
        }
        return ValueCell(number: 0)
        
      case .matchFuncExpr(let str, let reExpr):
        let s = try eval(str).asString()
        let pat = try regexPattern(reExpr)
        if let (_, nsRange) = try AWKRuntime.pmatch(pattern: pat, in: s) {
          let start = Double(nsRange.location + 1)
          let len   = Double(nsRange.length)
          RSTART  = start
          RLENGTH = len
          return ValueCell(number: start)
        }
        RSTART = 0
        RLENGTH = -1
        return ValueCell(number: 0)
        
      case .closeExpr(let e):
        let name = try eval(e).asString()
        closeFile(name: name)
        return ValueCell(number: 0)
        
      case .indirect(let e):
        // @expr or $$n — treat as field
        let n = Int(try eval(e).getNumber())
        let s = getField(n)
        return ValueCell(string: s)
    }
  }
  
  // MARK: - Printf formatting
  
  // C: format() — run.c
  func format(_ fmt: String, args: [Expression]) throws -> String {
    var result = ""
    var argIdx = 0
    var i = fmt.startIndex
    
    while i < fmt.endIndex {
      let c = fmt[i]
      guard c == "%" else { result.append(c); fmt.formIndex(after: &i); continue }
      fmt.formIndex(after: &i)
      guard i < fmt.endIndex else { result.append("%"); break }
      if fmt[i] == "%" { result.append("%"); fmt.formIndex(after: &i); continue }
      
      var spec = "%"
      // flags
      while i < fmt.endIndex && "-+0 #".contains(fmt[i]) {
        spec.append(fmt[i]); fmt.formIndex(after: &i)
      }
      // width (* or digits)
      if i < fmt.endIndex && fmt[i] == "*" {
        if argIdx < args.count { spec += String(Int(try eval(args[argIdx]).getNumber())); argIdx += 1 }
        fmt.formIndex(after: &i)
      } else { while i < fmt.endIndex && fmt[i] >= "0" && fmt[i] <= "9" { spec.append(fmt[i]); fmt.formIndex(after: &i) } }
      // precision
      if i < fmt.endIndex && fmt[i] == "." {
        spec.append("."); fmt.formIndex(after: &i)
        if i < fmt.endIndex && fmt[i] == "*" {
          if argIdx < args.count { spec += String(Int(try eval(args[argIdx]).getNumber())); argIdx += 1 }
          fmt.formIndex(after: &i)
        } else { while i < fmt.endIndex && fmt[i] >= "0" && fmt[i] <= "9" { spec.append(fmt[i]); fmt.formIndex(after: &i) } }
      }
      // skip size modifiers
      while i < fmt.endIndex && "hjLlqtz".contains(fmt[i]) { fmt.formIndex(after: &i) }
      guard i < fmt.endIndex else { break }
      let type = fmt[i]; fmt.formIndex(after: &i)
      
      let arg: Cell = argIdx < args.count ? (try eval(args[argIdx])) : EmptyCell()
      argIdx += 1
      
      switch type {
        case "d", "i":
          result += cFormat( spec + "d", Int64(bitPattern: UInt64(arg.getNumber())))
        case "o": result += cFormat( spec + "o", UInt64(arg.getNumber()))
        case "x": result += cFormat( spec + "x", UInt64(arg.getNumber()))
        case "X": result += cFormat( spec + "X", UInt64(arg.getNumber()))
        case "u": result += cFormat( spec + "u", UInt64(arg.getNumber()))
        case "e": result += cFormat( spec + "e", arg.getNumber())
        case "E": result += cFormat( spec + "E", arg.getNumber())
        case "f": result += cFormat( spec + "f", arg.getNumber())
        case "g": result += cFormat( spec + "g", arg.getNumber())
        case "G": result += cFormat( spec + "G", arg.getNumber())
        case "a": result += cFormat( spec + "a", arg.getNumber())
        case "A": result += cFormat( spec + "A", arg.getNumber())
        case "s": result += cFormat( spec + "s", arg.asString(fmt: OFMT))
        case "c":
          if let n = Int(arg.asString()) {
            let nn = n & 0xFF
            if nn != 0 { result += cFormat(spec + "c", nn) }
          } else {
            let s = arg.asString()
            result += cFormat(spec + "c", s.first.flatMap { $0.asciiValue }.map(Int.init) ?? 0)
          }
        default: result.append(type)
      }
    }
    return result
  }
}
