// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/

import CMigration

extension RuntimeState {
  
  // MARK: - Statement execution
  
  // C: program() block loop — run.c
  func execBlock(_ stmts: [Statement]) async throws {
    for stmt in stmts { try await exec(stmt) }
  }
  
  // C: execute() — run.c  (ifstat / whilestat / dostat / forstat / instat / jump)
  func exec(_ stmt: Statement) async throws {
    switch stmt {
      case .empty: break
        
      case .expression(let e):
        _ = try await eval(e)
        
      case .block(let stmts):
        try await execBlock(stmts)

      case .print_(let kind, let args, let dest):
        try await execPrint(kind: kind, args: args, dest: dest)

      case .delete_(let lv):
        try await execDelete(lv)

      case .if_(let cond, let then, let else_):
        if try await eval(cond).isTrue {
          try await exec(then)
        } else if let e = else_ {
          try await exec(e)
        }
        
      case .while_(let cond, let body):
        while try await eval(cond).isTrue {
          do { try await exec(body) }
          catch AWKSignal.break_ { return }
          catch AWKSignal.continue_ { /* next iteration */ }
        }
        
      case .doWhile(let body, let cond):
        repeat {
          do { try await exec(body) }
          catch AWKSignal.break_ { return }
          catch AWKSignal.continue_ { /* next iteration */ }
        } while try await eval(cond).isTrue
        
      case .for_(let init_, let cond, let incr, let body):
        if let i = init_ { try await exec(i) }
        while true {
          if let c = cond, !(try await eval(c).isTrue) { break }
          do { try await exec(body) }
          catch AWKSignal.break_ { return }
          catch AWKSignal.continue_ { /* fall through to increment */ }
          if let inc = incr { try await exec(inc) }
        }
        
      case .forIn(let varName, let arrName, let body):
        let arrCell = try resolveVar(arrName, nil)
        guard arrCell is Dictionary else { return }
        
        // Snapshot keys to allow modification during iteration
        let aa = (arrCell as! Dictionary).dict
        let keys = Array(aa.keys)
        for key in keys {
          guard let _ = aa[key] else { continue }
          try await storeVar(varName, ValueCell(string: key))
          do { try await exec(body) }
          catch AWKSignal.break_ { return }
          catch AWKSignal.continue_ { /* next key */ }
        }
        
      case .next:
        throw AWKSignal.next
        
      case .nextFile:
        throw AWKSignal.nextFile
        
      case .exit_(let e):
        if let e {
          let code = try await eval(e).getNumber()
          throw AWKSignal.exit_(Int32(code))
        }
        throw AWKSignal.exit_(exitCode)
        
      case .return_(let e):
        let cell = e != nil ? (try await eval(e!)) : EmptyCell()
        throw AWKSignal.`return`(cell)
        
      case .break_:
        throw AWKSignal.break_
        
      case .continue_:
        throw AWKSignal.continue_
    }
  }
  
  // MARK: - Expression await evaluation
  
  // C: execute() — run.c  (arith / relop / boolop / matchop / condexpr / cat / incrdecr / etc.)
  func eval(_ expr: Expression) async throws -> Cell {
    switch expr {

        // --- Literals ---
      case .number(let n):
        return ValueCell(number: n)

      case .string(let s):
        return ValueCell(string: s)

      case .regexMatch(let pat):
        // Bare /re/ → match against $0
        let s = getField(0)
        let matched = (try? AWKRuntime.match(pattern: pat, in: s)) != nil
        return ValueCell(number: matched ? 1 : 0)

        // --- Variables ---
      case .variable(let name):
        return try resolveVar(name, nil)

      case .argument(let i):
        if let frame = callStack.last, i < frame.cells.count { return frame.cells[i] }
        throw AWKRuntimeError("function argument \(i) out of range")

        /*      case .varnf:
         // should be  fldbld()
         ensureFields()
         return symtab["NF"]!
         */

      case .field(let e):
        let n = Int(try await eval(e).getNumber())
        let s = getField(n)
        let c = ValueCell(field: s)
        //          if AWKRuntime.isNumber(s) { c.numVal = AWKRuntime.parseNum(s); c.hasNum = true }
        return c

      case .element(let name, let keys):
        return try await resolveElement(name: name, keys: keys, nil)

        // --- Assignment ---
      case .assign(let op, let lv, let rhs):
        return try await execAssign(op: op, lv: lv, rhs: rhs)

        // --- Ternary ---
      case .ternary(let cond, let then, let else_):
        return try await eval(cond).isTrue ? eval(then) : eval(else_)

        // --- Logical (short-circuit) ---
      case .logicalOr(let a, let b):
        let aa = try await eval(a).isTrue
        let cc = if aa { true } else { try await eval(b).isTrue }
        return ValueCell(number: cc ? 1 : 0)

      case .logicalAnd(let a, let b):
        let aa = try await eval(a).isTrue
        let cc = if aa { try await eval(b).isTrue } else { false }
        return ValueCell(number: cc ? 1 : 0)

        // --- Comparison ---
      case .equal(let a, let b):
        let x = try await eval(a), y = try await eval(b)
        return ValueCell(number: AWKRuntime.compare(x, y, convfmt: CONVFMT) == 0 ? 1 : 0)

      case .notNull(let a):
        let t = try await eval(a).isTrue
        return ValueCell(number: t ? 1 : 0)

      case .notEqual(let a, let b):
        let x = try await eval(a)
        let y = try await eval(b)
        return ValueCell(number: AWKRuntime.compare(x, y, convfmt: CONVFMT) != 0 ? 1 : 0)

      case .lessThan(let a, let b):
        let x = try await eval(a), y = try await eval(b)
        return ValueCell(number: AWKRuntime.compare(x, y, convfmt: CONVFMT) < 0 ? 1 : 0)

      case .lessEqual(let a, let b):
        let x = try await eval(a), y = try await eval(b)
        return ValueCell(number: AWKRuntime.compare(x, y, convfmt: CONVFMT) <= 0 ? 1 : 0)

      case .greaterThan(let a, let b):
        let x = try await eval(a), y = try await eval(b)
        return ValueCell(number: AWKRuntime.compare(x, y, convfmt: CONVFMT) > 0 ? 1 : 0)

      case .greaterEqual(let a, let b):
        let x = try await eval(a), y = try await eval(b)
        return ValueCell(number: AWKRuntime.compare(x, y, convfmt: CONVFMT) >= 0 ? 1 : 0)

      case .patternMatch(let e, let re):
        let s = try await eval(e).asString()
        let pat = try await regexPattern(re)
        let matched = (try? AWKRuntime.match(pattern: pat, in: s)) != nil
        return ValueCell(number: matched ? 1 : 0)

      case .patternNotMatch(let e, let re):
        let s = try await eval(e).asString()
        let pat = try await regexPattern(re)
        let matched = (try? AWKRuntime.match(pattern: pat, in: s)) != nil
        return ValueCell(number: matched ? 0 : 1)

      case .inArray(let e, let arrName):
        let key = try await eval(e).asString()
        // FIXME: make the nil optional
        let arr = try resolveVar(arrName, nil)
        if arr is Dictionary {
          return ValueCell(number: (arr as! Dictionary).dict[key] == nil ? 0 : 1)
        } else {
          return ValueCell(number: 0)
        }

      case .inArrayTuple(let exprs, let arrName):
        var parts = [String]()
        for x in exprs {
          parts.append(try await eval(x).asString())
        }

        let key = subscriptKey(parts)
        let arr = try resolveVar(arrName, nil)
        if arr is Dictionary {
          let k = (arr as! Dictionary).dict[key]
          return ValueCell(number: k != nil ? 1 : 0 )
        } else {
          return ValueCell(number: 0)
        } 

        // --- Getline ---
      case .getline(let lv):
        return try await execGetline(lv: lv)

      case .getlineFrom(let lv, let src):
        let path = try await eval(src).asString()
        let file = try await fileFor(name: path, mode: .read)
        return try await readLineInto(lv: lv, from: file, updates0: true)

      case .getlinePipe(let lv, let cmd):
        let cmdStr = try await eval(cmd).asString()
        let file = try await fileFor(name: cmdStr, mode: .inputPipe)
        return try await readLineInto(lv: lv, from: file, updates0: false)

        // --- Arithmetic ---
      case .concat(let a, let b):
        let sa = try await eval(a).asString()
        let sb = try await eval(b).asString()
        return ValueCell(string: sa + sb)
        
      case .add(let a, let b):
        return ValueCell(number: try await eval(a).getNumber() + eval(b).getNumber())
        
      case .subtract(let a, let b):
        return ValueCell(number: try await eval(a).getNumber() - eval(b).getNumber())
        
      case .multiply(let a, let b):
        return ValueCell(number: try await eval(a).getNumber() * eval(b).getNumber())
        
      case .divide(let a, let b):
        let denom = try await eval(b).getNumber()
        if denom == 0 { throw AWKRuntimeError("division by zero") }
        return ValueCell(number: try await eval(a).getNumber() / denom)
        
      case .modulo(let a, let b):
        let denom = try await eval(b).getNumber()
        if denom == 0 { throw AWKRuntimeError("division by zero in mod") }
        let num = try await eval(a).getNumber()
        var intPart = 0.0; modf(num / denom, &intPart)
        return ValueCell(number: num - denom * intPart)
        
      case .power(let a, let b):
        let base = try await eval(a).getNumber()
        let exp  = try await eval(b).getNumber()
        return ValueCell(number: ipow(base, exp))
        
      case .negate(let e):
        // 0-0 give me 0, but -0 gives me a negative 0
        let j = 0-(try await eval(e).getNumber())
        return ValueCell(number: j  	)

      case .unaryPlus(let e):
        return ValueCell(number: try await eval(e).getNumber())
        
      case .logicalNot(let e):
        return ValueCell(number: try await eval(e).isTrue ? 0 : 1)
        
        // --- Increment / decrement ---
      case .preIncrement(let lv):
        return try await evalLValue(lv) { c in
          return ValueCell(number: c.getNumber() + 1)
        }

      case .preDecrement(let lv):
        return try await evalLValue(lv) { c in
          return ValueCell(number: c.getNumber() - 1)
        }

      case .postIncrement(let lv):
        var old : Double = 0
        try await evalLValue(lv) { c in
          old = c.getNumber()
          return ValueCell(number: old + 1)
        }
        return ValueCell(number: old)

      case .postDecrement(let lv):
        var old : Double = 0
        return try await evalLValue(lv) { c in
          old = c.getNumber()
          return ValueCell(number: old - 1)
        }
        return ValueCell(number: old)

        // --- User-defined function call ---
      case .userCall(let name, let args):
        return try await execUserCall(name: name, argExprs: args)

        // --- Builtin function call ---
      case .builtinCall(let id, let args):
        return try await execBuiltin(id: id, args: args)

        // --- String operations ---
      case .sprintfExpr(let args):
        guard !args.isEmpty else { return EmptyCell() }
        let fmtStr = try await eval(args[0]).asString()
        return ValueCell(string: try await format(fmtStr, args: Array(args.dropFirst())))

      case .subExpr(let kind, let reExpr, let replExpr, let target):
        return try await execSub(kind: kind, reExpr: reExpr, replExpr: replExpr, target: target)

      case .substrExpr(let str, let start, let len):
        return try await execSubstr(str: str, start: start, len: len)

      case .splitExpr(let str, let arrName, let sep):
        return try await execSplit(str: str, arrName: arrName, sep: sep)

      case .indexExpr(let hay, let needle):
        let h = try await eval(hay).asString()
        let n = try await eval(needle).asString()
        // Weird, but that is the definition for AWK index
        if n.isEmpty { return ValueCell(number: 1) }
        if let r = h.range(of: n) {
          let off = h.distance(from: h.startIndex, to: r.lowerBound)
          return ValueCell(number: Double(off + 1))   // 1-based
        }
        return ValueCell(number: 0)
        
      case .matchFuncExpr(let str, let reExpr):
        let s = try await eval(str).asString()
        let pat = try await regexPattern(reExpr)
        if let range = try AWKRuntime.pmatch(pattern: pat, in: s) {
          let start = Double(s.distance(from: s.startIndex, to: range.lowerBound) + 1)
          let len   = Double(s.distance(from: range.lowerBound, to: range.upperBound))
          RSTART  = start
          RLENGTH = len
          return ValueCell(number: start)
        }
        RSTART = 0
        RLENGTH = -1
        return ValueCell(number: 0)
        
      case .closeExpr(let e):
        let name = try await eval(e).asString()
        await closeFile(name: name)
        return ValueCell(number: 0)

    }
  }
  
  // MARK: - Printf formatting
  
  // C: format() — run.c
  func format(_ fmt: String, args: [Expression]) async throws -> String {
    var result = ""
    var argIdx = 0
    var i = fmt.startIndex
    
    while i < fmt.endIndex {
      let c = fmt[i]
      guard c == "%" else { result.append(c); fmt.formIndex(after: &i); continue }
      fmt.formIndex(after: &i)
      guard i < fmt.endIndex else { result.append("%"); break }
      if fmt[i] == "%" { result.append("%"); fmt.formIndex(after: &i); continue }
      
      var spec = "%"
      // flags
      while i < fmt.endIndex && "-+0 #".contains(fmt[i]) {
        spec.append(fmt[i]); fmt.formIndex(after: &i)
      }
      // width (* or digits)
      if i < fmt.endIndex && fmt[i] == "*" {
        if argIdx < args.count { spec += String(Int(try await eval(args[argIdx]).getNumber())); argIdx += 1 }
        fmt.formIndex(after: &i)
      } else { while i < fmt.endIndex && fmt[i] >= "0" && fmt[i] <= "9" { spec.append(fmt[i]); fmt.formIndex(after: &i) } }
      // precision
      if i < fmt.endIndex && fmt[i] == "." {
        spec.append("."); fmt.formIndex(after: &i)
        if i < fmt.endIndex && fmt[i] == "*" {
          if argIdx < args.count { spec += String(Int(try await eval(args[argIdx]).getNumber())); argIdx += 1 }
          fmt.formIndex(after: &i)
        } else { while i < fmt.endIndex && fmt[i] >= "0" && fmt[i] <= "9" { spec.append(fmt[i]); fmt.formIndex(after: &i) } }
      }
      // skip size modifiers
      while i < fmt.endIndex && "hjLlqtz".contains(fmt[i]) { fmt.formIndex(after: &i) }
      guard i < fmt.endIndex else { break }
      let type = fmt[i]; fmt.formIndex(after: &i)
      
      let arg: Cell = argIdx < args.count ? (try await eval(args[argIdx])) : EmptyCell()
      argIdx += 1
      
      switch type {
        case "d", "i":
          result += cFormat( spec + "d", Int64(bitPattern: UInt64(arg.getNumber())))
        case "o": result += cFormat( spec + "o", UInt64(arg.getNumber()))
        case "x": result += cFormat( spec + "x", UInt64(arg.getNumber()))
        case "X": result += cFormat( spec + "X", UInt64(arg.getNumber()))
        case "u": result += cFormat( spec + "u", UInt64(arg.getNumber()))
        case "e": result += cFormat( spec + "e", arg.getNumber())
        case "E": result += cFormat( spec + "E", arg.getNumber())
        case "f": result += cFormat( spec + "f", arg.getNumber())
        case "g": result += cFormat( spec + "g", arg.getNumber())
        case "G": result += cFormat( spec + "G", arg.getNumber())
        case "a": result += cFormat( spec + "a", arg.getNumber())
        case "A": result += cFormat( spec + "A", arg.getNumber())
        case "s": result += cFormat( spec + "s", arg.asString(fmt: OFMT))
        case "c":
          if arg.isNumber && arg.getNumber().rounded() == arg.getNumber() {
            let nn = UInt(arg.getNumber()) & 0xFF
            if nn != 0 { result += cFormat(spec + "c", UInt8(nn)) }
          } else {
            let s = arg.asString()
            result += cFormat(spec + ".1s", s)
          }
        default: result.append(type)
      }
    }
    return result
  }

}
