// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/

import CMigration
import Foundation

// MARK: - I/O

enum AWKFileMode { case read, write, append, outputPipe, inputPipe }

final class AWKFile {
  let name: String
  let mode: AWKFileMode
  var handle: FileHandle
  var process: Process? = nil
  var buffer: String = ""     // unread input buffer for line-at-a-time reading
  
  init(name: String, mode: AWKFileMode, handle: FileHandle, process: Process? = nil) {
    self.name = name; self.mode = mode
    self.handle = handle; self.process = process
  }
  
  // Read the next record delimited by `rs`. Returns nil at EOF.
  // C: readrec() — lib.c
  func readRecord(rs: String) -> String? {
    // Refill buffer from handle
    func refill() {
      let data = handle.availableData
      guard !data.isEmpty, let s = String(data: data, encoding: .utf8) else { return }
      buffer += s
    }
    
    refill()
    if buffer.isEmpty { return nil }
    
    if rs.isEmpty {
      // RS="" → paragraph mode: split on blank lines
      while buffer.hasPrefix("\n") { buffer.removeFirst() }
      if buffer.isEmpty { return nil }
      if let range = buffer.range(of: "\n\n") {
        let record = String(buffer[buffer.startIndex..<range.lowerBound])
        buffer.removeSubrange(buffer.startIndex...range.upperBound)
        return record
      }
      let record = buffer; buffer = ""; return record
    }
    
    let sep: Character = rs.count == 1 ? Character(rs) : "\n"
    if let idx = buffer.firstIndex(of: sep) {
      let record = String(buffer[buffer.startIndex..<idx])
      buffer.removeSubrange(buffer.startIndex...idx)
      return record
    }
    // EOF: return remaining buffer
    let record = buffer; buffer = ""; return record
  }
  
  // C: (direct fwrite/fputs via FILE* in printstat() / redirect() — run.c)
  func write(_ s: String) throws {
    guard let data = s.data(using: .utf8) else { return }
    handle.write(data)
  }
  
  // C: fclose() / pclose() — run.c
  func close() {
    if let proc = process { proc.terminate(); proc.waitUntilExit() }
    if handle != .standardInput && handle != .standardOutput && handle != .standardError {
      try? handle.close()
    }
  }
}
