// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/

import CMigration

// MARK: - I/O

enum AWKFileMode { case read, write, append, outputPipe, inputPipe }

extension FileDescriptor {
  public var syncBytes : SyncByteStream { get  { SyncByteStream(fd: self) } }
}


public struct SyncByteStream: Sequence {
  public typealias Element = UInt8
  let fd: FileDescriptor
  let bufferSize: Int = 4096
  
  //  public var lines : AsyncLineReader { get { AsyncLineReader(byteStream: self) } }
  //  public func lines(_ withEOL : Bool = false, encoding: any Unicode.Encoding.Type = UTF8.self) -> AsyncLineReader {
  //    return AsyncLineReader(byteStream: self, retEOL:  withEOL, encoding: encoding)
  //  }
  //  public var linesNLX : AsyncLineSequenceX { get { AsyncLineSequenceX(base: self) } }
  
  public struct Iterator: IteratorProtocol {
    public typealias Element = UInt8
    
    let fd: FileDescriptor
    var buffer = [UInt8]()
    var index = 0
    let bufferSize: Int
    
    public mutating func next() -> UInt8? {
      if index >= buffer.count {
        var temp = [UInt8](repeating: 0, count: bufferSize)
        do {
          let bytesRead = try temp.withUnsafeMutableBytes {
            try fd.read(into: $0)
          }
          
          guard bytesRead > 0 else { return nil }
          buffer = Array(temp.prefix(bytesRead))
          index = 0
        } catch {
          // print("reading: \(e.localizedDescription)")
          return nil
        }
      }
      
      let byte = buffer[index]
      index += 1
      return byte
    }
  }
  
  public func makeIterator() -> Iterator {
    Iterator(fd: fd, bufferSize: bufferSize)
  }
  
  // C: RS classification — lib.c/main.c treat RS as: single char (line-at-a-time),
  // "" (paragraph mode: records separated by one-or-more blank lines, leading blank
  // lines skipped), or (a one-true-awk extension) a longer string used as an ERE.
  public func records(rs : String) -> SyncRecordReader {
    SyncRecordReader(byteStream: self, rs: rs, encoding: localeEncoding())
  }

}


enum RSMode {
  case char(UInt8)
  case paragraph
  case pattern(Regex<AnyRegexOutput>?)
}

// needs to be a class -- otherwise the struct gets copied and it doesn't work
public struct SyncRecordReader: Sequence {
  public typealias Element = String
  let byteStream: SyncByteStream
  var encoding : IEncoding = .utf8
  var mode : RSMode

  public init(byteStream: SyncByteStream, rs: String, encoding: IEncoding = .utf8) {
    self.byteStream = byteStream
    self.encoding = encoding
    if rs.isEmpty {
      self.mode = .paragraph
    } else if rs.count == 1 {
      self.mode = .char(rs.first!.asciiValue ?? 10)
    } else {
      self.mode = .pattern(try? Regex(fixre(rs)))
    }
  }

  public struct Iterator: IteratorProtocol {
    var byteIterator: SyncByteStream.Iterator
    var buffer = [UInt8]()
    var encoding : IEncoding = .utf8
    var mode : RSMode

    func decode(_ bytes: [UInt8]) -> String? {
      return try? encoding.toString(bytes)
    }

    mutating func nextLine(rs: UInt8) -> String? {
      var go = false
      while let byte = byteIterator.next() {
        go = true
        if byte == rs {
          break
        } else {
          buffer.append(byte)
        }
      }

      guard go else { return nil }
      guard let line = decode(buffer) else {
        buffer.removeAll()
        return nil
      }
      buffer.removeAll()
      return line
    }

    // C: RS == "" paragraph mode — lib.c
    mutating func nextParagraph() -> String? {
      var sawContent = false
      var newlineRun = 0
      while let byte = byteIterator.next() {
        if byte == 0x0A {
          if !sawContent { continue }  // skip leading/extra blank lines
          newlineRun += 1
          buffer.append(byte)
          if newlineRun >= 2 {
            while buffer.last == 0x0A { buffer.removeLast() }
            let record = decode(buffer)
            buffer.removeAll()
            return record
          }
        } else {
          sawContent = true
          newlineRun = 0
          buffer.append(byte)
        }
      }
      guard sawContent else { return nil }
      while buffer.last == 0x0A { buffer.removeLast() }
      guard !buffer.isEmpty else { return nil }
      let record = decode(buffer) 
      buffer.removeAll()
      return record
    }

    // C: RS as ERE — a one-true-awk extension for multi-character RS
    mutating func nextPatternDelimited(_ re: Regex<AnyRegexOutput>?) -> String? {
      guard let re else { return nextLine(rs: 0x0A) }
      while true {
        // A match whose range extends all the way to the end of what's buffered so far
        // could still grow with more input (e.g. "X+" against "aXX" might yet consume a
        // third X), so only finalize a match once it's followed by at least one
        // non-matching byte, confirming a greedy quantifier can't extend it further.
        if let s = decode(buffer),
           let m = try? re.firstMatch(in: s), !m.range.isEmpty, m.range.upperBound < s.endIndex {
          let record = String(s[s.startIndex..<m.range.lowerBound])
          buffer = Array(s[m.range.upperBound...].utf8)
          return record
        }
        guard let byte = byteIterator.next() else {
          // EOF: a match touching the buffer's end is now final since no more input can arrive.
          if let s = decode(buffer),
             let m = try? re.firstMatch(in: s), !m.range.isEmpty {
            let record = String(s[s.startIndex..<m.range.lowerBound])
            buffer = Array(s[m.range.upperBound...].utf8)
            return record
          }
          guard !buffer.isEmpty else { return nil }
          let record = decode(buffer)
          buffer.removeAll()
          return record
        }
        buffer.append(byte)
      }
    }

    public mutating func next() -> String? {
      switch mode {
        case .char(let rs): return nextLine(rs: rs)
        case .paragraph: return nextParagraph()
        case .pattern(let re): return nextPatternDelimited(re)
      }
    }
  }

  public func makeIterator() -> Iterator {
    Iterator(byteIterator: byteStream.makeIterator(), encoding: encoding, mode: mode)
  }
}



// FIXME: get rid of this 
final class AWKFile : @unchecked Sendable {
  let name: String
  let mode: AWKFileMode
  var handle: FileDescriptor
  var buffer: String = ""     // unread input buffer for line-at-a-time reading
  var proc : DarwinProcess?

  init(name: String, mode: AWKFileMode, handle: FileDescriptor, proc: DarwinProcess? = nil) {
    self.name = name; self.mode = mode
    self.handle = handle
    self.proc = proc
  }
  
  // Read the next record delimited by `rs`. Returns nil at EOF.
  // C: readrec() — lib.c
  func readRecord(rs: String) throws -> String? {
    // Refill buffer from handle
    func refill() throws {
      let data = try handle.readAvailableBytes()
      guard !data.isEmpty else { return }
      let s = try localeEncoding().toString(data)
      buffer += s
    }
    
    try refill()
    if buffer.isEmpty { return nil }
    
    if rs.isEmpty {
      // RS="" → paragraph mode: split on blank lines
      while buffer.hasPrefix("\n") { buffer.removeFirst() }
      if buffer.isEmpty { return nil }
      if let range = buffer.range(of: "\n\n") {
        let record = String(buffer[buffer.startIndex..<range.lowerBound])
        buffer.removeSubrange(buffer.startIndex...range.upperBound)
        return record
      }
      let record = buffer; buffer = ""; return record
    }
    
    if rs.count == 1 {
      let sep = Character(rs)
      if let idx = buffer.firstIndex(of: sep) {
        let record = String(buffer[buffer.startIndex..<idx])
        buffer.removeSubrange(buffer.startIndex...idx)
        return record
      }
      // EOF: return remaining buffer
      let record = buffer; buffer = ""; return record
    }

    // Multi-character RS: a one-true-awk extension treating it as an ERE.
    if let re = try? Regex(fixre(rs)), let m = try? re.firstMatch(in: buffer), !m.range.isEmpty {
      let record = String(buffer[buffer.startIndex..<m.range.lowerBound])
      buffer.removeSubrange(buffer.startIndex..<m.range.upperBound)
      return record
    }
    let record = buffer; buffer = ""; return record
  }
  
  // C: (direct fwrite/fputs via FILE* in printstat() / redirect() — run.c)
  func write(_ s: String) throws {
    let data = try localeEncoding().toBytes(s)
    try handle.write(data)
  }
  
  // C: fclose() / pclose() — run.c
  func close() async throws {
    if handle != .standardInput && handle != .standardOutput && handle != .standardError {
      try handle.close()
    }

    if let k = try await proc?.value() {
      if k.code != 0 {
        throw AWKRuntimeError("subprocess returned error: \(k.code)")
      }
    }
//    print(k)
//    if let proc = process {
//    }
  }
}

