// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/

import CMigration

// MARK: - I/O

enum AWKFileMode { case read, write, append, outputPipe, inputPipe }

extension FileDescriptor {
  public var syncBytes : SyncByteStream { get  { SyncByteStream(fd: self) } }
}


public struct SyncByteStream: Sequence {
  public typealias Element = UInt8
  let fd: FileDescriptor
  let bufferSize: Int = 4096
  
  //  public var lines : AsyncLineReader { get { AsyncLineReader(byteStream: self) } }
  //  public func lines(_ withEOL : Bool = false, encoding: any Unicode.Encoding.Type = UTF8.self) -> AsyncLineReader {
  //    return AsyncLineReader(byteStream: self, retEOL:  withEOL, encoding: encoding)
  //  }
  //  public var linesNLX : AsyncLineSequenceX { get { AsyncLineSequenceX(base: self) } }
  
  public struct Iterator: IteratorProtocol {
    public typealias Element = UInt8
    
    let fd: FileDescriptor
    var buffer = [UInt8]()
    var index = 0
    let bufferSize: Int
    
    public mutating func next() -> UInt8? {
      if index >= buffer.count {
        var temp = [UInt8](repeating: 0, count: bufferSize)
        do {
          let bytesRead = try temp.withUnsafeMutableBytes {
            try fd.read(into: $0)
          }
          
          guard bytesRead > 0 else { return nil }
          buffer = Array(temp.prefix(bytesRead))
          index = 0
        } catch {
          // print("reading: \(e.localizedDescription)")
          return nil
        }
      }
      
      let byte = buffer[index]
      index += 1
      return byte
    }
  }
  
  public func makeIterator() -> Iterator {
    Iterator(fd: fd, bufferSize: bufferSize)
  }
  
  public func records(rs : Character) -> SyncRecordReader {
    SyncRecordReader(byteStream: self, rs: rs.asciiValue!)
  }
  
}



// needs to be a class -- otherwise the struct gets copied and it doesn't work
public struct SyncRecordReader: Sequence {
  public typealias Element = String
  let byteStream: SyncByteStream
  var encoding : any Unicode.Encoding.Type = UTF8.self
  var rs : UInt8 = "\n".first!.asciiValue!

  public init(byteStream: SyncByteStream, rs: UInt8 = "\n".first!.asciiValue!) {
    self.byteStream = byteStream
    self.rs = rs
  }
  
  public struct Iterator: IteratorProtocol {
    var byteIterator: SyncByteStream.Iterator
    var buffer = [UInt8]()
    var encoding : any Unicode.Encoding.Type = UTF8.self
    var rs : UInt8 // = "\n".first!.asciiValue!

    public mutating func next() -> String? {
      var go = false
      while let byte = byteIterator.next() {
        go = true
        if byte == rs {
          break
        } else {
          buffer.append(byte)
        }
      }

      guard go else { return nil }
      var line : String?
      switch encoding {
        case is ISOLatin1.Type:
          line = String(validating: buffer, as: ISOLatin1.self )
        case is UTF16.Type:
          let buff = buffer.withUnsafeBytes { $0.load(as: [UInt16].self) }
          line = String(validating: buff, as: UTF16.self )
        case is UTF32.Type:
          let buff = buffer.withUnsafeBytes { $0.load(as: [UInt32].self) }
          line = String(validating: buff, as: UTF32.self )
        case is UTF8.Type:
          fallthrough
        default:
          line = String(validating: buffer, as: UTF8.self )
      }
      guard let line else {
        line = String(validating: buffer, as: ISOLatin1.self )
        buffer.removeAll()
        return line
      }
      buffer.removeAll()
      return line
    }
  }

  public func makeIterator() -> Iterator {
    Iterator(byteIterator: byteStream.makeIterator(), encoding: encoding, rs: rs)
  }
}



// FIXME: get rid of this 
final class AWKFile : @unchecked Sendable {
  let name: String
  let mode: AWKFileMode
  var handle: FileDescriptor
  var buffer: String = ""     // unread input buffer for line-at-a-time reading
  var proc : DarwinProcess?

  init(name: String, mode: AWKFileMode, handle: FileDescriptor, proc: DarwinProcess? = nil) {
    self.name = name; self.mode = mode
    self.handle = handle
    self.proc = proc
  }
  
  // Read the next record delimited by `rs`. Returns nil at EOF.
  // C: readrec() — lib.c
  func readRecord(rs: String) throws -> String? {
    // Refill buffer from handle
    func refill() throws {
      let data = try handle.readAvailableBytes()
      guard !data.isEmpty, let s = String(bytes: data, encoding: .utf8) else { return }
      buffer += s
    }
    
    try refill()
    if buffer.isEmpty { return nil }
    
    if rs.isEmpty {
      // RS="" → paragraph mode: split on blank lines
      while buffer.hasPrefix("\n") { buffer.removeFirst() }
      if buffer.isEmpty { return nil }
      if let range = buffer.range(of: "\n\n") {
        let record = String(buffer[buffer.startIndex..<range.lowerBound])
        buffer.removeSubrange(buffer.startIndex...range.upperBound)
        return record
      }
      let record = buffer; buffer = ""; return record
    }
    
    let sep: Character = rs.count == 1 ? Character(rs) : "\n"
    if let idx = buffer.firstIndex(of: sep) {
      let record = String(buffer[buffer.startIndex..<idx])
      buffer.removeSubrange(buffer.startIndex...idx)
      return record
    }
    // EOF: return remaining buffer
    let record = buffer; buffer = ""; return record
  }
  
  // C: (direct fwrite/fputs via FILE* in printstat() / redirect() — run.c)
  func write(_ s: String) throws {
    // FIzME: some tests (like t.printf2) yield different results because of latin1 vs utf8 encodings
//    guard let data = s.data(using: .utf8) else { return }
    guard let data = s.data(using: .isoLatin1) else { return }
    // FIXME: this works for isoLatin1, but not for .utf8 or localeEncoding()
// guard let data = s.data(using: localeEncoding() ) else { return }
    try handle.write(data)
  }
  
  // C: fclose() / pclose() — run.c
  func close() async throws {
    if handle != .standardInput && handle != .standardOutput && handle != .standardError {
      try handle.close()
    }

    if let k = try await proc?.value() {
      if k.code != 0 {
        throw AWKRuntimeError("subprocess returned error: \(k.code)")
      }
    }
//    print(k)
//    if let proc = process {
//    }
  }
}

