// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/

// AWK grammar expressed as parser combinators + a Pratt parser for expressions.

// Direct translation of awkgram.y (one-true-awk).
//
// Grammar rules appear as private functions returning Parser<T>.
// Expression parsing uses Pratt / top-down operator precedence, which handles
// AWK's rich precedence table without left-recursion issues.

// MARK: - Entry point

enum AWKParser {
  // C: yyparse() — awkgram.y
  static func parse(_ tokens: [AWKToken], lines: [Int]) throws -> AWKProgram {
    try program().run(on: tokens, lines: lines)
  }
}

// MARK: - Whitespace / separator helpers
// These correspond to: pst opt_pst nl opt_nl st lbrace rbrace rparen comma

// C: pst / opt_pst — awkgram.y
private func skipSep() -> Parser<Void> {
    oneOf(token(.newline), token(.semicolon)).many.map { _ in () }
}

// Statement terminator: nl | ';' opt_nl
// C: st — awkgram.y
private func stEnd() -> Parser<Void> {
    oneOf(
        token(.newline).many1.map { _ in () },
        token(.semicolon).then(token(.newline).many.map { _ in () })
    )
}

// Tokens that allow optional trailing newlines per the grammar
// C: lbrace — awkgram.y
private func lbrace() -> Parser<Void> {
    token(.lbrace).then(token(.newline).many.map { _ in () })
}
// C: rbrace — awkgram.y
private func rbrace() -> Parser<Void> {
    token(.rbrace).then(token(.newline).many.map { _ in () })
}
// C: rparen — awkgram.y
private func rparen_() -> Parser<Void> {
    token(.rparen).then(token(.newline).many.map { _ in () })
}
// C: comma — awkgram.y
private func comma_() -> Parser<Void> {
    token(.comma).then(token(.newline).many.map { _ in () })
}
// C: opt_nl — awkgram.y
private func skipNL() -> Parser<Void> {
    token(.newline).many.map { _ in () }
}

// C: statement-terminator detection — awkgram.y
private func isStEnd(_ tok: AWKToken?) -> Bool {
    switch tok {
    case .newline, .semicolon, .rbrace, .eof, nil: return true
    default: return false
    }
}

// MARK: - Top-level program
// program: pas   where  pas: opt_pst (pa_stat (opt_pst pa_stat)* opt_pst)?

// C: program rule — awkgram.y
private func program() -> Parser<AWKProgram> {
    Parser { stream in
        try skipSep().parse(&stream)

        var beginRules: [[Statement]] = []
        var rules:      [PatternAction] = []
        var endRules:   [[Statement]] = []
        var functions:  [FunctionDefinition] = []

        while let next = stream.first, next != .eof {
            if let rule = try paStat(
                &stream,
                beginRules: &beginRules,
                endRules:   &endRules,
                functions:  &functions
            ) {
                rules.append(rule)
            }
            try skipSep().parse(&stream)
        }

        return AWKProgram(
            beginRules: beginRules,
            rules:      rules,
            endRules:   endRules,
            functions:  functions
        )
    }
}

// MARK: - Pattern-action rules

// C: pa_stat — awkgram.y
private func paStat(
    _ stream: inout TokenStream,
    beginRules: inout [[Statement]],
    endRules:   inout [[Statement]],
    functions:  inout [FunctionDefinition]
) throws -> PatternAction? {
    switch stream.first {

    case .xbegin:
        stream = stream.dropFirst()
        let body = try stmtBlock().parse(&stream)
        beginRules.append(body)
        return nil

    case .xend:
        stream = stream.dropFirst()
        let body = try stmtBlock().parse(&stream)
        endRules.append(body)
        return nil

    case .funcKeyword:
        stream = stream.dropFirst()
        let fn = try parseFunctionDef().parse(&stream)
        functions.append(fn)
        return nil

    case .lbrace:
        // Always block — no pattern
        let body = try stmtBlock().parse(&stream)
        return PatternAction(pattern: .always, body: body)

    default:
        // Pattern, possibly followed by ',' pattern (range), possibly followed by block
        let pat = try paPat().parse(&stream)
        if stream.first == .comma {
            stream = stream.dropFirst()
            try skipNL().parse(&stream)
            let pat2 = try paPat().parse(&stream)
            let body = (stream.first == .lbrace) ? try stmtBlock().parse(&stream) : []
            return PatternAction(pattern: .range(pat, pat2), body: body)
        }
        let body = (stream.first == .lbrace) ? try stmtBlock().parse(&stream) : []
        return PatternAction(pattern: .expression(pat), body: body)
    }
}

// pa_pat: pattern wrapped in notnull
// C: pa_pat — awkgram.y
private func paPat() -> Parser<Expression> {
    pattern().map { $0.notnull() }
}

// MARK: - Function definitions

// C: funcdef — awkgram.y
private func parseFunctionDef() -> Parser<FunctionDefinition> {
    Parser { stream in
        let name: String
        switch stream.first {
        case .variable(let n): name = n; stream = stream.dropFirst()
        case .callRef(let n):  name = n; stream = stream.dropFirst()
        default: throw ParseError("Expected function name after 'func'")
        }
        guard stream.first == .lparen else { throw ParseError("Expected '(' in function definition") }
        stream = stream.dropFirst()
        let params = try varList().parse(&stream)
        try rparen_().parse(&stream)
        let body = try stmtBlock().parse(&stream)
        // C: awkgram.y — a fixed limit (50) on the number of function parameters.
        guard params.count <= 50 else {
            throw ParseError("function \(name) has \(params.count) arguments, limit 50")
        }
        // Check for duplicate parameter names (corresponds to checkdup in awkgram.y)
        var seen = Set<String>()
        for p in params {
            guard seen.insert(p).inserted else {
                throw ParseError("Duplicate parameter '\(p)' in function '\(name)'")
            }
        }
        return FunctionDefinition(name: name, params: params, body: body)
    }
}

// varlist: (nothing) | VAR (',' VAR)*
// C: var_list — awkgram.y
private func varList() -> Parser<[String]> {
    Parser { stream in
        var params: [String] = []
        while case .variable(let n) = stream.first {
            params.append(n)
            stream = stream.dropFirst()
            if stream.first == .comma {
                stream = stream.dropFirst()
                try skipNL().parse(&stream)
            } else {
                break
            }
        }
        return params
    }
}

// A block: lbrace stmtlist rbrace
// C: action — awkgram.y
private func stmtBlock() -> Parser<[Statement]> {
    Parser { stream in
        try lbrace().parse(&stream)
        let stmts = try stmtList().parse(&stream)
        // C: awkgram.y — a function definition can't appear inside a statement
        // block. `stmtList()`'s `.many` can't propagate this itself (a nested
        // parse failure there just looks like "no more statements"), so it's
        // detected here instead: `stmtList()` stopping with `funcKeyword` still
        // pending is only possible in this one situation.
        if stream.first == .funcKeyword {
            throw ParseError("illegal nested function")
        }
        // C: awkgram.y — sub/gsub's third argument must be an lvalue (it's the
        // grammar's `var` nonterminal, not a general expression); a literal there
        // (e.g. gsub(/re/, repl, "literal")) fails inside parsePrefix(), but that
        // failure is swallowed the same way as the funcKeyword case above, leaving
        // the sub/gsub token itself as the unconsumed leftover here.
        if stream.first == .kwSub || stream.first == .kwGsub {
            throw ParseError("syntax error")
        }
        try rbrace().parse(&stream)
        return stmts
    }
}

// MARK: - Statements

// stmtlist: stmt*  (left-recursive in yacc → iterative here)
// C: stmtlist — awkgram.y
private func stmtList() -> Parser<[Statement]> {
    lazy(stmt()).many.map { stmts in
        stmts.filter {
            if case .lineMarker(_, .empty) = $0 { return false }
            return true
        }
    }
}

// C: stmt — awkgram.y
private func stmt() -> Parser<Statement> {
    Parser { stream in
        let ln = stream.line ?? 1
        let result: Statement
        switch stream.first {
        case .kwBreak:
            stream = stream.dropFirst(); try stEnd().parse(&stream); result = .break_
        case .kwContinue:
            stream = stream.dropFirst(); try stEnd().parse(&stream); result = .continue_
        case .kwNext:
            stream = stream.dropFirst(); try stEnd().parse(&stream); result = .next
        case .kwNextfile:
            stream = stream.dropFirst(); try stEnd().parse(&stream); result = .nextFile
        case .kwDo:
            result = try parseDoWhile().parse(&stream)
        case .kwExit:
            result = try parseExit().parse(&stream)
        case .kwFor:
            result = try parseFor().parse(&stream)
        case .kwIf:
            result = try parseIf().parse(&stream)
        case .lbrace:
            result = .block(try stmtBlock().parse(&stream))
        case .kwReturn:
            result = try parseReturn().parse(&stream)
        case .kwWhile:
            result = try parseWhile().parse(&stream)
        case .semicolon:
            stream = stream.dropFirst(); try skipNL().parse(&stream); result = .empty
        default:
            let s = try simpleStmt().parse(&stream)
            try stEnd().parse(&stream)
            result = s
        }
        return .lineMarker(ln, result)
    }
}

// MARK: - Control-flow statements

// C: do-while case in stmt — awkgram.y
private func parseDoWhile() -> Parser<Statement> {
    Parser { stream in
        guard stream.first == .kwDo else { throw ParseError("Expected 'do'") }
        stream = stream.dropFirst()
        try skipNL().parse(&stream)
        let body = try lazy(stmt()).parse(&stream)
        guard stream.first == .kwWhile else { throw ParseError("Expected 'while' after do-body") }
        stream = stream.dropFirst()
        guard stream.first == .lparen else { throw ParseError("Expected '(' after 'while'") }
        stream = stream.dropFirst()
        let cond = try pattern().parse(&stream)
        // Note: plain ')' here, not rparen_() — the newline right after the
        // closing paren is the do-while's statement terminator (consumed by
        // stEnd() below), not an "optional nl before body" separator like
        // if/while/for use rparen_() for.
        guard stream.first == .rparen else { throw ParseError("Expected ')' after do-while condition") }
        stream = stream.dropFirst()
        try stEnd().parse(&stream)
        return .doWhile(body, cond.notnull())
    }
}

// C: exit case in stmt — awkgram.y
private func parseExit() -> Parser<Statement> {
    Parser { stream in
        guard stream.first == .kwExit else { throw ParseError("Expected 'exit'") }
        stream = stream.dropFirst()
        let expr: Expression? = isStEnd(stream.first) ? nil : try pattern().parse(&stream)
        try stEnd().parse(&stream)
        return .exit_(expr)
    }
}

// C: for case in stmt — awkgram.y
private func parseFor() -> Parser<Statement> {
    Parser { stream in
        guard stream.first == .kwFor else { throw ParseError("Expected 'for'") }
        stream = stream.dropFirst()
        guard stream.first == .lparen else { throw ParseError("Expected '(' after 'for'") }
        stream = stream.dropFirst()

        // Try for-in: VAR in ARRAY
        if case .variable(let vname) = stream.first {
            let peek2 = stream.dropFirst().first
            if peek2 == .kwIn {
                stream = stream.dropFirst()  // consume VAR
                stream = stream.dropFirst()  // consume in
                guard case .variable(let arrName) = stream.first else {
                    throw ParseError("Expected array name in for-in")
                }
                stream = stream.dropFirst()
                try rparen_().parse(&stream)
                try skipNL().parse(&stream)
                let body = try lazy(stmt()).parse(&stream)
                return .forIn(vname, arrName, body)
            }
        }

        // C-style: for (init; cond; incr)
        let init_: Statement? = stream.first == .semicolon
            ? nil : try simpleStmt().opt.parse(&stream)
        guard stream.first == .semicolon else { throw ParseError("Expected ';' in for") }
        stream = stream.dropFirst()
        try skipNL().parse(&stream)
        let cond: Expression? = stream.first == .semicolon
            ? nil : try pattern().opt.parse(&stream)
        guard stream.first == .semicolon else { throw ParseError("Expected ';' in for") }
        stream = stream.dropFirst()
        try skipNL().parse(&stream)
        let incr_: Statement? = stream.first == .rparen
            ? nil : try simpleStmt().opt.parse(&stream)
        try rparen_().parse(&stream)
        try skipNL().parse(&stream)
        let body = try lazy(stmt()).parse(&stream)
        return .for_(init_, cond?.notnull(), incr_, body)
    }
}

// C: if case in stmt — awkgram.y
private func parseIf() -> Parser<Statement> {
    Parser { stream in
        guard stream.first == .kwIf else { throw ParseError("Expected 'if'") }
        stream = stream.dropFirst()
        guard stream.first == .lparen else { throw ParseError("Expected '(' after 'if'") }
        stream = stream.dropFirst()
        let cond = try pattern().parse(&stream)
        try rparen_().parse(&stream)
        let then = try lazy(stmt()).parse(&stream)
        // optional else — must skip separators to find 'else'
        let saved = stream
        try skipSep().parse(&stream)
        if stream.first == .kwElse {
            stream = stream.dropFirst()
            try skipNL().parse(&stream)
            let else_ = try lazy(stmt()).parse(&stream)
            return .if_(cond.notnull(), then, else_)
        }
        stream = saved
        return .if_(cond.notnull(), then, nil)
    }
}

// C: return case in stmt — awkgram.y
private func parseReturn() -> Parser<Statement> {
    Parser { stream in
        guard stream.first == .kwReturn else { throw ParseError("Expected 'return'") }
        stream = stream.dropFirst()
        let expr: Expression? = isStEnd(stream.first) ? nil : try pattern().parse(&stream)
        try stEnd().parse(&stream)
        return .return_(expr)
    }
}

private func parseWhile() -> Parser<Statement> {
    Parser { stream in
        guard stream.first == .kwWhile else { throw ParseError("Expected 'while'") }
        stream = stream.dropFirst()
        guard stream.first == .lparen else { throw ParseError("Expected '(' after 'while'") }
        stream = stream.dropFirst()
        let cond = try pattern().parse(&stream)
        try rparen_().parse(&stream)
        try skipNL().parse(&stream)
        let body = try lazy(stmt()).parse(&stream)
        return .while_(cond.notnull(), body)
    }
}

// MARK: - Simple statements
// simple_stmt: print | delete | pattern-as-expression

private func simpleStmt() -> Parser<Statement> {
    Parser { stream in
        switch stream.first {
        case .kwPrint, .kwPrintf:
            return try parsePrintStmt().parse(&stream)
        case .kwDelete:
            stream = stream.dropFirst()
            return try parseDeleteStmt().parse(&stream)
        default:
            let expr = try pattern().parse(&stream)
            return .expression(expr)
        }
    }
}

// print prarg (| >> > term)?
private func parsePrintStmt() -> Parser<Statement> {
    Parser { stream in
        let kind: PrintKind
        switch stream.first {
        case .kwPrint:  kind = .print;  stream = stream.dropFirst()
        case .kwPrintf: kind = .printf; stream = stream.dropFirst()
        default: throw ParseError("Expected 'print' or 'printf'")
        }

        // prarg: empty | pplist | '(' plist ')'
        let args: [Expression]
        if stream.first == .lparen {
            // Ambiguous — could be grouped args or redirect target.
            // Try (plist) as the full argument list first.
            let saved = stream
            stream = stream.dropFirst()
            do {
                let list = try sepBy1(lazy(ppattern()), sep: comma_()).parse(&stream)
                if stream.first == .rparen {
                    stream = stream.dropFirst()
                    if isRedirectOp(stream.first) || isStEnd(stream.first) {
                        // (plist) > redirect  or  (plist) at end of statement
                        args = list
                    } else {
                        // Something like (a > b) ? x : y — the ')' closed a grouped
                        // expression, not a print-arg list.  Fall back and re-parse
                        // from before the '(' so the whole thing is one expression.
                        throw ParseError("not a grouped arg list")
                    }
                } else {
                    throw ParseError("not a simple plist")
                }
            } catch {
                stream = saved
                args = try sepBy(lazy(printArgPattern()), sep: comma_()).parse(&stream)
            }
        } else {
            args = try sepBy(lazy(printArgPattern()), sep: comma_()).parse(&stream)
        }

        // Optional redirect
        let dest: PrintDest?
        switch stream.first {
        case .pipe:
            stream = stream.dropFirst()
            dest = .pipe(try term().parse(&stream))
        case .appendOp:
            stream = stream.dropFirst()
            dest = .append(try term().parse(&stream))
        case .gtOp:
            stream = stream.dropFirst()
            dest = .redirect(try term().parse(&stream))
        default:
            dest = nil
        }

        return .print_(kind, args, dest)
    }
}

private func isRedirectOp(_ tok: AWKToken?) -> Bool {
    switch tok {
    case .pipe, .appendOp, .gtOp: return true
    default: return false
    }
}

// delete varname [ '[' patlist ']' ]
private func parseDeleteStmt() -> Parser<Statement> {
    Parser { stream in
        guard case .variable(let name) = stream.first else {
            throw ParseError("Expected variable name after 'delete'")
        }
        stream = stream.dropFirst()
        if stream.first == .lbracket {
            stream = stream.dropFirst()
            let keys = try sepBy1(lazy(pattern()), sep: comma_()).parse(&stream)
            guard stream.first == .rbracket else { throw ParseError("Expected ']' after subscript") }
            stream = stream.dropFirst()
            return .delete_(.element(name, keys))
        }
        return .delete_(.variable(name))
    }
}

// MARK: - Variable / varname parsers

// varname: VAR | ARG | VARNF
private func varname() -> Parser<Expression> {
    Parser { stream in
        switch stream.first {
        case .variable(let n): stream = stream.dropFirst(); return .variable(n)
//        case .arg(let i):      stream = stream.dropFirst(); return .argument(i)
//        case .varnf:           stream = stream.dropFirst(); return .varnf
        default: throw ParseError("Expected variable name")
        }
    }
}

// var: varname | varname '[' patlist ']' | IVAR | '@' term | '$' term
//
// The field case ('$' term) isn't in the original "var" nonterminal by that
// name, but every caller of var_() here wants a general lvalue (getline's
// target, sub/gsub's target, ...), and field references like $0 or $1 are
// valid lvalues in awk (e.g. `sub(/x/, "y", $2)`, `getline $1`).
private func var_() -> Parser<Expression> {
    Parser { stream in
        if stream.first == .dollar {
            stream = stream.dropFirst()
            return try parseDollarOperand(&stream, getlinePipe: false)
        }
        let base = try varname().parse(&stream)
        if stream.first == .lbracket {
            stream = stream.dropFirst()
            let keys = try sepBy1(lazy(pattern()), sep: comma_()).parse(&stream)
            guard stream.first == .rbracket else { throw ParseError("Expected ']'") }
            stream = stream.dropFirst()
            guard case .variable(let n) = base else {
                throw ParseError("Array subscript requires a named variable")
            }
            return .element(n, keys)
        }
        return base
    }
}

// Parses the operand of a '$' (the token has already been consumed) and
// applies the one-true-awk grammar quirk around postfix ++/--.
//
// In awkgram.y, `var: INDIRECT term` sits alongside `term: var INCR | var DECR`.
// For an array element (`varname '[' patlist ']'`), the yacc parser reduces
// that array-element `var` and then faces a shift/reduce choice on a
// following INCR/DECR: shift (attach to the array element, since `var INCR`
// is available immediately) wins over reducing it up through `term` into the
// pending `$`. That makes `$f[1]++` mean `$(f[1]++)` — the *subscript
// variable* is incremented, not the field. Plain variables/NF and bare
// field numbers (`$i++`, `$NF++`, `$1++`) don't hit that reduction point the
// same way and keep the intuitive `($x)++` reading, and parenthesizing the
// subscript expression (`$(arr[1])++`) also forces the plain reading since
// parens close off the array element as its own `term` before `$` sees it —
// so only a *literal* `$name[key,...]` gets the special treatment here.
private func parseDollarOperand(_ stream: inout TokenStream, getlinePipe: Bool) throws -> Expression {
    if case .variable(let name) = stream.first {
        var probe = stream.dropFirst()
        if probe.first == .lbracket {
            stream = probe.dropFirst()
            let keys = try sepBy1(lazy(pattern()), sep: comma_()).parse(&stream)
            guard stream.first == .rbracket else { throw ParseError("Expected ']'") }
            stream = stream.dropFirst()
            if stream.first == .incrOp {
                stream = stream.dropFirst()
                return .field(.postIncrement(.element(name, keys)))
            }
            if stream.first == .decrOp {
                stream = stream.dropFirst()
                return .field(.postDecrement(.element(name, keys)))
            }
            return .field(.element(name, keys))
        }
    }
    let inner = try parseExpr(&stream, minBP: BP.postfix + 1, getlinePipe: getlinePipe)
    return .field(inner)
}

// MARK: - Expression parser (Pratt / top-down operator precedence)
//
// Covers pattern, ppattern, and term from the original grammar.
// `getlinePipe` controls whether `cmd | getline` is permitted (false in print args).
//
// Binding powers — higher number = tighter binding.
// Derived from the %left/%right/%nonassoc declarations in awkgram.y
// (declarations listed from lowest to highest precedence in yacc).

private enum BP {
    static let assignment  = 10  // right-associative: rbp = 9
    static let ternary     = 20  // right-associative: rbp = 19
    static let logicalOr   = 30
    static let logicalAnd  = 40
    static let getlinePipe = 55  // '|' followed by getline
    static let comparison  = 60  // ==, !=, <, <=, >, >=, ~, !~, in
    static let concat      = 100 // implicit concatenation
    static let addSub      = 110
    static let mulDiv      = 120
    static let power       = 140 // right-associative: rbp = 139
    static let postfix     = 160 // postfix ++ --
}

private func pattern() -> Parser<Expression> {
    Parser { s in try parseExpr(&s, minBP: 0, getlinePipe: true) }
}

private func ppattern() -> Parser<Expression> {
    Parser { s in try parseExpr(&s, minBP: 0, getlinePipe: false) }
}

private func term() -> Parser<Expression> { ppattern() }

// Bare (unparenthesized) print/printf arguments: a top-level '>' always
// means output redirection, never a greater-than comparison — this mirrors
// one-true-awk's resolution of the print-statement grammar ambiguity.
// `allowGT: false` propagates through the same unparenthesized chain
// (concatenation, arithmetic, &&/||, unary ops) but is reset to true by any
// bounded sub-context (parens, ternary branches, function-call args, etc.),
// where a literal '>' can only mean comparison.
private func printArgPattern() -> Parser<Expression> {
    Parser { s in try parseExpr(&s, minBP: 0, getlinePipe: false, allowGT: false) }
}

// MARK: Pratt parser core

private func parseExpr(_ stream: inout TokenStream, minBP: Int, getlinePipe: Bool, allowGT: Bool = true) throws -> Expression {
    var lhs = try parsePrefix(&stream, getlinePipe: getlinePipe)
    while true {
        let lhsIsLValue = lhs.asLValue() != nil
        guard let lbp = infixBP(stream.first, getlinePipe: getlinePipe, allowGT: allowGT, lhsIsLValue: lhsIsLValue), lbp >= minBP else { break }
        lhs = try parseInfix(&stream, lhs: lhs, lbp: lbp, getlinePipe: getlinePipe, allowGT: allowGT)
    }
    return lhs
}

/// Left binding power of the current token when used as an infix operator.
/// Returns nil if the token is not an infix operator at the current context.
private func infixBP(_ tok: AWKToken?, getlinePipe: Bool, allowGT: Bool = true, lhsIsLValue: Bool = true) -> Int? {
    guard let tok else { return nil }
    switch tok {
    case .assignOp, .addEqOp, .subEqOp, .mulEqOp, .divEqOp, .modEqOp, .powEqOp:
        return BP.assignment
    case .question:
        return BP.ternary
    case .borOp:
        return BP.logicalOr
    case .andOp:
        return BP.logicalAnd
    case .pipe where getlinePipe:
        return BP.getlinePipe  // only if | getline is allowed
    case .gtOp:
        return allowGT ? BP.comparison : nil  // bare '>' in print args means redirect
    case .eqOp, .neOp, .ltOp, .leOp, .geOp, .matchOp, .notMatchOp, .kwIn:
        return BP.comparison
    case .plus, .minus:
        return BP.addSub
    case .star, .percent:
        return BP.mulDiv
    case .slash:
        return BP.mulDiv        // division (vs. regex is resolved by the lexer)
    case .powerOp:
        return BP.power
    case .incrOp, .decrOp:
        // A trailing ++/-- is only a postfix operator on an assignable lhs
        // (e.g. `i++`); otherwise (e.g. after another postfix already
        // consumed the only valid target, as in `i++ ++j`) it can't apply
        // again, so treat it like any other term-starting token and let it
        // begin a new implicitly-concatenated term instead.
        return lhsIsLValue ? BP.postfix : (canStartTerm(tok) ? BP.concat : nil)
    default:
        // Implicit concatenation: if this token can start a term, it "infix-concatenates"
        return canStartTerm(tok) ? BP.concat : nil
    }
}

private func parseInfix(
    _ stream: inout TokenStream,
    lhs: Expression,
    lbp: Int,
    getlinePipe: Bool,
    allowGT: Bool = true
) throws -> Expression {
    let tok = stream.first!          // caller verified lbp is non-nil ∴ tok exists

    switch tok {
    // Assignment (right-associative)
    case .assignOp, .addEqOp, .subEqOp, .mulEqOp, .divEqOp, .modEqOp, .powEqOp:
        let op = assignOp(tok)!
        stream = stream.dropFirst()
        guard let lv = lhs.asLValue() else { throw ParseError("Left side of '\(op.rawValue)' must be assignable") }
        let rhs = try parseExpr(&stream, minBP: BP.assignment - 1, getlinePipe: true)
        return .assign(op, lv, rhs)

    // Ternary ?:
    case .question:
        stream = stream.dropFirst()
        let then = try parseExpr(&stream, minBP: 0, getlinePipe: true)
        guard stream.first == .colon else { throw ParseError("Expected ':' in ternary expression") }
        stream = stream.dropFirst()
        let else_ = try parseExpr(&stream, minBP: BP.ternary - 1, getlinePipe: true)
        return .ternary(lhs.notnull(), then, else_)

    // Logical OR
    case .borOp:
        stream = stream.dropFirst(); try skipNL().parse(&stream)
        let rhs = try parseExpr(&stream, minBP: BP.logicalOr + 1, getlinePipe: getlinePipe, allowGT: allowGT)
        return .logicalOr(lhs.notnull(), rhs.notnull())

    // Logical AND
    case .andOp:
        stream = stream.dropFirst(); try skipNL().parse(&stream)
        let rhs = try parseExpr(&stream, minBP: BP.logicalAnd + 1, getlinePipe: getlinePipe, allowGT: allowGT)
        return .logicalAnd(lhs.notnull(), rhs.notnull())

    // Pipe to getline: cmd | getline [var]
    case .pipe:
        guard stream.dropFirst().first == .kwGetline else {
            // '|' in this position with getlinePipe=true but not followed by getline
            // fall through to implicit concat (shouldn't happen in well-formed input)
            throw ParseError("'|' requires 'getline' in expression context")
        }
        stream = stream.dropFirst()  // consume '|'
        stream = stream.dropFirst()  // consume 'getline'
        let lval: LValue? = try var_().opt.parse(&stream).flatMap { $0.asLValue() }
        return .getlinePipe(lval, lhs)

    // Comparison operators (non-associative)
    case .eqOp:
        stream = stream.dropFirst()
        return .equal(lhs, try parseExpr(&stream, minBP: BP.comparison + 1, getlinePipe: getlinePipe, allowGT: allowGT))
    case .neOp:
        stream = stream.dropFirst()
        return .notEqual(lhs, try parseExpr(&stream, minBP: BP.comparison + 1, getlinePipe: getlinePipe, allowGT: allowGT))
    case .ltOp:
        stream = stream.dropFirst()
        return .lessThan(lhs, try parseExpr(&stream, minBP: BP.comparison + 1, getlinePipe: getlinePipe, allowGT: allowGT))
    case .leOp:
        stream = stream.dropFirst()
        return .lessEqual(lhs, try parseExpr(&stream, minBP: BP.comparison + 1, getlinePipe: getlinePipe, allowGT: allowGT))
    case .gtOp:
        stream = stream.dropFirst()
        return .greaterThan(lhs, try parseExpr(&stream, minBP: BP.comparison + 1, getlinePipe: getlinePipe, allowGT: allowGT))
    case .geOp:
        stream = stream.dropFirst()
        return .greaterEqual(lhs, try parseExpr(&stream, minBP: BP.comparison + 1, getlinePipe: getlinePipe, allowGT: allowGT))
    case .matchOp:
        stream = stream.dropFirst()
        return .patternMatch(lhs, try regexOrExpr(&stream, getlinePipe: getlinePipe))
    case .notMatchOp:
        stream = stream.dropFirst()
        return .patternNotMatch(lhs, try regexOrExpr(&stream, getlinePipe: getlinePipe))
    case .kwIn:
        stream = stream.dropFirst()
        guard case .variable(let arrName) = stream.first else {
            throw ParseError("Expected array name after 'in'")
        }
        stream = stream.dropFirst()
        return .inArray(lhs, arrName)

    // Arithmetic
    case .plus:
        stream = stream.dropFirst()
        return .add(lhs, try parseExpr(&stream, minBP: BP.addSub + 1, getlinePipe: getlinePipe, allowGT: allowGT))
    case .minus:
        stream = stream.dropFirst()
        return .subtract(lhs, try parseExpr(&stream, minBP: BP.addSub + 1, getlinePipe: getlinePipe, allowGT: allowGT))
    case .star:
        stream = stream.dropFirst()
        return .multiply(lhs, try parseExpr(&stream, minBP: BP.mulDiv + 1, getlinePipe: getlinePipe, allowGT: allowGT))
    case .slash:
        stream = stream.dropFirst()
        // Disambiguate /= (division-assign) from plain division
        if stream.first == .assignOp {
            stream = stream.dropFirst()
            guard let lv = lhs.asLValue() else { throw ParseError("Left side of '/=' must be assignable") }
            return .assign(.divSet, lv, try parseExpr(&stream, minBP: BP.assignment - 1, getlinePipe: true))
        }
        return .divide(lhs, try parseExpr(&stream, minBP: BP.mulDiv + 1, getlinePipe: getlinePipe, allowGT: allowGT))
    case .percent:
        stream = stream.dropFirst()
        return .modulo(lhs, try parseExpr(&stream, minBP: BP.mulDiv + 1, getlinePipe: getlinePipe, allowGT: allowGT))
    case .powerOp:
        stream = stream.dropFirst()
        return .power(lhs, try parseExpr(&stream, minBP: BP.power - 1, getlinePipe: getlinePipe, allowGT: allowGT)) // right-assoc

    // Postfix ++ / --. infixBP only assigns this token BP.postfix when lhs is
    // a valid lvalue; when lhs isn't one (e.g. the lhs in `i++ ++j`, after
    // the first `++` already consumed `i` as its target), it's routed here
    // with lbp == BP.concat instead, so fall through to implicit concat.
    case .incrOp where lhs.asLValue() != nil:
        stream = stream.dropFirst()
        return .postIncrement(lhs.asLValue()!)
    case .decrOp where lhs.asLValue() != nil:
        stream = stream.dropFirst()
        return .postDecrement(lhs.asLValue()!)

    default:
        // Implicit concatenation
        let rhs = try parseExpr(&stream, minBP: BP.concat + 1, getlinePipe: getlinePipe)
        return .concat(lhs, rhs)
    }
}

// MARK: Prefix (nud) parser

private func parsePrefix(_ stream: inout TokenStream, getlinePipe: Bool) throws -> Expression {
    guard let tok = stream.first else { throw ParseError("Unexpected end of input") }
    switch tok {

    // Literals
    case .number(let n):
        stream = stream.dropFirst()
        return .number(n)

    case .string(let s):
        stream = stream.dropFirst()
        // Adjacent STRING tokens are concatenated at parse time (string rule in grammar)
        var result = s
        while case .string(let s2) = stream.first { result += s2; stream = stream.dropFirst() }
        return .string(result)

    case .regexLiteral(let s):
        stream = stream.dropFirst()
        return .regexMatch(s)    // bare /re/ matches against $0

    // Variables
//    case .varnf:
//                  stream = stream.dropFirst(); return .varnf
      case .variable:  //, .arg: //, .ivar: // , .atSign:
        return try var_().parse(&stream)

    // Function call: CALL '(' args ')'
    case .callRef(let name):
        stream = stream.dropFirst()
        guard stream.first == .lparen else { throw ParseError("Expected '(' after function '\(name)'") }
        stream = stream.dropFirst()
        let args: [Expression] = stream.first == .rparen
            ? [] : try sepBy1(lazy(pattern()), sep: comma_()).parse(&stream)
        guard stream.first == .rparen else { throw ParseError("Expected ')' in call to '\(name)'") }
        stream = stream.dropFirst()
        return .userCall(name, args)

    // Field access: $expr
    case .dollar:
        stream = stream.dropFirst()
        return try parseDollarOperand(&stream, getlinePipe: getlinePipe)

    // Grouping or (plist) in array
    case .lparen:
        stream = stream.dropFirst()
        let first = try parseExpr(&stream, minBP: 0, getlinePipe: true)
        if stream.first == .comma {
            // Collect a comma-separated list — only valid before 'in'
            var items = [first]
            while stream.first == .comma {
                stream = stream.dropFirst(); try skipNL().parse(&stream)
                items.append(try parseExpr(&stream, minBP: 0, getlinePipe: true))
            }
            guard stream.first == .rparen else { throw ParseError("Expected ')' closing tuple") }
            stream = stream.dropFirst()
            guard stream.first == .kwIn else { throw ParseError("'(list)' must be followed by 'in'") }
            stream = stream.dropFirst()
            guard case .variable(let arrName) = stream.first else {
                throw ParseError("Expected array name after 'in'")
            }
            stream = stream.dropFirst()
            return .inArrayTuple(items, arrName)
        }
        guard stream.first == .rparen else { throw ParseError("Expected ')' in grouped expression") }
        stream = stream.dropFirst()
        return first

    // Unary operators
    case .minus:
        stream = stream.dropFirst()
        return .negate(try parseExpr(&stream, minBP: BP.mulDiv, getlinePipe: getlinePipe))
    case .plus:
        stream = stream.dropFirst()
        return .unaryPlus(try parseExpr(&stream, minBP: BP.mulDiv, getlinePipe: getlinePipe))
    case .notOp:
        stream = stream.dropFirst()
        if case .regexLiteral(let s) = stream.first {
            stream = stream.dropFirst()
            return .logicalNot(.regexMatch(s))
        }
        let operand = try parseExpr(&stream, minBP: BP.mulDiv, getlinePipe: getlinePipe)
        return .logicalNot(operand.notnull())

    // Prefix ++ / --
    case .incrOp:
        stream = stream.dropFirst()
        let lv = try parseLValue(&stream, getlinePipe: getlinePipe)
        return .preIncrement(lv)
    case .decrOp:
        stream = stream.dropFirst()
        let lv = try parseLValue(&stream, getlinePipe: getlinePipe)
        return .preDecrement(lv)

    // Getline
    case .kwGetline:
        return try parseGetline(&stream)

    // Builtin functions (BLTIN token)
    case .bltin(let id):
        stream = stream.dropFirst()
        if stream.first == .lparen {
            stream = stream.dropFirst()
            let args: [Expression] = stream.first == .rparen
                ? [] : try sepBy1(lazy(pattern()), sep: comma_()).parse(&stream)
            guard stream.first == .rparen else { throw ParseError("Expected ')' in builtin call") }
            stream = stream.dropFirst()
            return .builtinCall(id, args)
        }
        // Builtin with no parens: takes $0 implicitly
        return .builtinCall(id, [.field(.number(0))])

    // Named builtin keywords
    case .kwClose:
        stream = stream.dropFirst()
        let target = try parseExpr(&stream, minBP: BP.postfix, getlinePipe: false)
        return .closeExpr(target)

    case .kwIndex:
        stream = stream.dropFirst()
        guard stream.first == .lparen else { throw ParseError("Expected '(' after index") }
        stream = stream.dropFirst()
        let haystack = try parseExpr(&stream, minBP: 0, getlinePipe: false)
        try comma_().parse(&stream)
        let needle = try parseExpr(&stream, minBP: 0, getlinePipe: false)
        guard stream.first == .rparen else { throw ParseError("Expected ')' in index()") }
        stream = stream.dropFirst()
        return .indexExpr(haystack, needle)

    case .kwMatch:
        stream = stream.dropFirst()
        guard stream.first == .lparen else { throw ParseError("Expected '(' after match") }
        stream = stream.dropFirst()
        let str = try parseExpr(&stream, minBP: 0, getlinePipe: false)
        try comma_().parse(&stream)
        let re = try regexOrExpr(&stream, getlinePipe: false)
        guard stream.first == .rparen else { throw ParseError("Expected ')' in match()") }
        stream = stream.dropFirst()
        return .matchFuncExpr(str, re)

    case .kwSplit:
        stream = stream.dropFirst()
        guard stream.first == .lparen else { throw ParseError("Expected '(' after split") }
        stream = stream.dropFirst()
        let str = try parseExpr(&stream, minBP: 0, getlinePipe: false)
        try comma_().parse(&stream)
        guard case .variable(let arrName) = stream.first else {
            throw ParseError("Expected array variable in split()")
        }
        stream = stream.dropFirst()
        let sep: Expression?
        if stream.first == .comma {
            stream = stream.dropFirst(); try skipNL().parse(&stream)
            sep = try regexOrExpr(&stream, getlinePipe: false)
        } else { sep = nil }
        guard stream.first == .rparen else { throw ParseError("Expected ')' in split()") }
        stream = stream.dropFirst()
        return .splitExpr(str, arrName, sep)

      case .kwSprintf:
        stream = stream.dropFirst()
        guard stream.first == .lparen else { throw ParseError("Expected '(' after sprintf") }
        stream = stream.dropFirst()
        let args = try sepBy1(lazy(pattern()), sep: comma_()).parse(&stream)
        guard stream.first == .rparen else { throw ParseError("Expected ')' in sprintf()") }
        stream = stream.dropFirst()
        return .sprintfExpr(args)

    case .kwSub, .kwGsub:
        let kind: SubKind = (tok == .kwSub) ? .sub : .gsub
        stream = stream.dropFirst()
        guard stream.first == .lparen else { throw ParseError("Expected '(' after sub/gsub") }
        stream = stream.dropFirst()
        let re = try regexOrExpr(&stream, getlinePipe: false)
        try comma_().parse(&stream)
        let repl = try parseExpr(&stream, minBP: 0, getlinePipe: false)
        let target: LValue
        if stream.first == .comma {
            stream = stream.dropFirst(); try skipNL().parse(&stream)
            let tExpr = try var_().parse(&stream)
            guard let lv = tExpr.asLValue() else { throw ParseError("sub/gsub target must be an lvalue") }
            target = lv
        } else {
            target = .field(.number(0))   // default target is $0
        }
        guard stream.first == .rparen else { throw ParseError("Expected ')' in sub/gsub()") }
        stream = stream.dropFirst()
        return .subExpr(kind, re, repl, target)

    case .kwSubstr:
        stream = stream.dropFirst()
        guard stream.first == .lparen else { throw ParseError("Expected '(' after substr") }
        stream = stream.dropFirst()
        let str = try parseExpr(&stream, minBP: 0, getlinePipe: false)
        try comma_().parse(&stream)
        let start = try parseExpr(&stream, minBP: 0, getlinePipe: false)
        let len: Expression?
        if stream.first == .comma {
            stream = stream.dropFirst(); try skipNL().parse(&stream)
            len = try parseExpr(&stream, minBP: 0, getlinePipe: false)
        } else { len = nil }
        guard stream.first == .rparen else { throw ParseError("Expected ')' in substr()") }
        stream = stream.dropFirst()
        return .substrExpr(str, start, len)

    default:
        throw ParseError("Unexpected token in expression: \(tok)")
    }
}

// MARK: Helper parsers used in the Pratt parser

// Regex literal or arbitrary expression (used after ~ and !~, and in sub/match args)
private func regexOrExpr(_ stream: inout TokenStream, getlinePipe: Bool) throws -> Expression {
    if case .regexLiteral(let s) = stream.first {
        stream = stream.dropFirst()
        return .regexMatch(s)
    }
    return try parseExpr(&stream, minBP: BP.comparison + 1, getlinePipe: getlinePipe)
}

// getline: GETLINE [var] [< file]
private func parseGetline(_ stream: inout TokenStream) throws -> Expression {
    guard stream.first == .kwGetline else { throw ParseError("Expected 'getline'") }
    stream = stream.dropFirst()
    let lval: LValue? = try var_().opt.parse(&stream).flatMap { $0.asLValue() }
    if stream.first == .ltOp {
        stream = stream.dropFirst()
        let src = try parseExpr(&stream, minBP: BP.comparison + 1, getlinePipe: false)
        return .getlineFrom(lval, src)
    }
    return .getline(lval)
}

private func parseLValue(_ stream: inout TokenStream, getlinePipe: Bool) throws -> LValue {
    // Use postfix+1 so that ++$a grabs $a as the lvalue, not ($a)++
    let expr = try parseExpr(&stream, minBP: BP.postfix + 1, getlinePipe: getlinePipe)
    guard let lv = expr.asLValue() else { throw ParseError("Expected an assignable location") }
    return lv
}

// Map a token to its AssignOp
private func assignOp(_ tok: AWKToken) -> AssignOp? {
    switch tok {
    case .assignOp: return .set
    case .addEqOp:  return .addSet
    case .subEqOp:  return .subSet
    case .mulEqOp:  return .mulSet
    case .divEqOp:  return .divSet
    case .modEqOp:  return .modSet
    case .powEqOp:  return .powSet
    default:        return nil
    }
}

// Returns true if this token can begin a prefix expression (term), enabling implicit concat.
private func canStartTerm(_ tok: AWKToken) -> Bool {
  switch tok {
    case .number, .string, .regexLiteral,
        .variable, .callRef, .bltin,
        .lparen, .dollar, .minus, .plus, .notOp, .incrOp, .decrOp,
        .kwGetline, .kwClose, .kwIndex, .kwMatch, .kwSplit,
        .kwSprintf, .kwSub, .kwGsub, .kwSubstr: // , .atSign:
      return true
    default:
      return false
  }
}
