// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/

// Runtime value type and global environment for the AWK interpreter.
// Corresponds to tran.c, the Cell/Array infrastructure from awk.h,
// and the I/O management from run.c.

import CMigration

/// Swift equivalent of the C setjmp/longjmp control-flow mechanism.
/// Each case is thrown and caught by the appropriate executor level.
enum AWKSignal: Error {
  case break_
  case continue_
  case next
  case nextFile
  case `return`
  case exit_(Int32)
}

struct AWKRuntimeError: Error, CustomStringConvertible {
  let message: String
  var line: Int?
  init(_ msg: String, line: Int? = nil) { message = msg; self.line = line }
  var description: String {
    guard let line else { return message }
    return "\(message) at source line \(line)"
  }
}

  // MARK: - AWK Runtime Utilities
  
enum AWKRuntime {
  
  // MARK: Number parsing — mirrors C's atof with leading-junk-stop behaviour.
  // C: strtod() / atof() pattern used in getfval() — tran.c
  static func parseNum(_ s: String) -> Double {
    var s = s
    while let c = s.first, c == " " || c == "\t" || c == "\n" || c == "\r" { s.removeFirst() }
    if s.isEmpty { return 0.0 }
    // Fast path
    if let d = Double(s) { return d }
    // Longest valid numeric prefix
    var i = s.startIndex
    if s[i] == "+" || s[i] == "-" { s.formIndex(after: &i) }
    var hasDot = false, hasExp = false, hasDigit = false
    while i < s.endIndex {
      let c = s[i]
      if c >= "0" && c <= "9" { hasDigit = true; s.formIndex(after: &i) }
      else if c == "." && !hasDot && !hasExp { hasDot = true; s.formIndex(after: &i) }
      else if (c == "e" || c == "E") && !hasExp && hasDigit {
        hasExp = true
        s.formIndex(after: &i)
        if i < s.endIndex && (s[i] == "+" || s[i] == "-") { s.formIndex(after: &i) }
      } else { break }
    }
    return Double(String(s[s.startIndex..<i])) ?? 0.0
  }
  
  // C: qstring() — lib.c — decodes backslash escapes in a command-line var=value
  // assignment (used for both -v and bare ARGV assignments) the same way a
  // double-quoted string constant is scanned. A bare, unescaped newline is fatal;
  // an unrecognized \X escape just drops the backslash and keeps X, matching the
  // real awk's observed behavior (verified against /usr/bin/awk).
  static func qstringDecode(_ s: String) throws -> String {
    var result = ""
    var rest = Substring(s)
    while let c = rest.first {
      rest.removeFirst()
      if c == "\n" {
        throw AWKRuntimeError("newline in string \(s.prefix(20))...")
      }
      guard c == "\\" else { result.append(c); continue }
      guard let esc = rest.first else { result.append(c); break }
      rest.removeFirst()
      switch esc {
        case "\n", "\r": break      // line continuation — skip
        case "\"": result.append("\"")
        case "n":  result.append("\n")
        case "t":  result.append("\t")
        case "f":  result.append("\u{0C}")
        case "r":  result.append("\r")
        case "b":  result.append("\u{08}")
        case "v":  result.append("\u{0B}")
        case "a":  result.append("\u{07}")
        case "\\": result.append("\\")
        case "0","1","2","3","4","5","6","7":   // octal
          var n = esc.wholeNumberValue!
          if let h = rest.first, h >= "0" && h <= "7" { n = 8 * n + h.wholeNumberValue!; rest.removeFirst() }
          if let h = rest.first, h >= "0" && h <= "7" { n = 8 * n + h.wholeNumberValue!; rest.removeFirst() }
          result.append(Character(Unicode.Scalar(UInt8(n & 0xFF))))
        default:
          result.append(esc)
      }
    }
    return result
  }

  // Number → string using printf format.  Integers use %.30g for exact output.
  // C: get_str_val() — tran.c (the CONVFMT/OFMT formatting path)
  static func numToStr(_ n: Double, fmt: String) -> String {
    guard n.isFinite else {
      return n.isNaN ? "nan" : (n > 0 ? "inf" : "-inf")
    }
    var intPart = 0.0
    if modf(n, &intPart) == 0.0 {
      return "%.30g".cFormat(n)
    }
    return fmt.cFormat(n)
  }
  
  // Returns true when the string is entirely numeric (per POSIX is_number).
  // C: is_number() — lib.c
  static func isNumber(_ s: String) -> Bool {
    let trimmed = s.trimmingCharacters(in: .whitespaces)
    guard isNumericSyntax(trimmed) else { return false }
    // one-true-awk's is_number() also rejects a syntactically valid number
    // whose magnitude overflows strtod's range (r == HUGE_VAL / errno ==
    // ERANGE) — e.g. "2e1000" is *not* a number, so it stays a plain string
    // and compares lexically rather than numerically.
    if let d = Double(trimmed), d.isInfinite { return false }
    return true
  }

  private static func isNumericSyntax(_ trimmed: String) -> Bool {
    var s = trimmed
    if s.isEmpty { return false }
    if s.first == "+" || s.first == "-" { s.removeFirst() }
    var hasDot = false, hasDigit = false
    var i = s.startIndex
    while i < s.endIndex {
      let c = s[i]
      if c >= "0" && c <= "9" { hasDigit = true }
      else if c == "." && !hasDot { hasDot = true }
      else if (c == "e" || c == "E") && hasDigit {
        s.formIndex(after: &i)
        if i < s.endIndex && (s[i] == "+" || s[i] == "-") { s.formIndex(after: &i) }
        var hasExpDigit = false
        while i < s.endIndex, s[i] >= "0" && s[i] <= "9" {
          hasExpDigit = true; s.formIndex(after: &i)
        }
        return hasExpDigit && i == s.endIndex
      } else { return false }
      s.formIndex(after: &i)
    }
    return hasDigit
  }
  
  // Compare two cells: negative / zero / positive.
  // Numeric comparison when both have numeric values; string comparison otherwise.
  // C: comparison logic in relop() — run.c
  static func compare(_ x: Cell, _ y: Cell, convfmt: String = "%.6g") -> Int {
    // FIXME: was passing convfmt
    if x.isNumber && y.isNumber {
      let xx = x.getNumber()
      let yy = y.getNumber()
      let d = xx - yy
      return d < 0 ? -1 : (d > 0 ? 1 : 0)
    }
    let xs = x.asString(fmt: convfmt), ys = y.asString(fmt: convfmt)
    return xs < ys ? -1 : (xs > ys ? 1 : 0)
  }
  
  // Compile an AWK regex and match against a string. Returns match range or nil.
  // C: matchop() — run.c  (regex execution via pmatch() — b.c)
  static func match(pattern: String, in str: String) throws -> Range<String.Index>? {
    let re = try makeRegex(pattern)
    return try re.firstMatch(in: str)?.range //  .flatMap { Range($0.range, in: str) }
  }
  
  // Like match() but returns the range of the full match (for RSTART/RLENGTH).
  // C: pmatch() — b.c
  static func pmatch(pattern: String, in str: String) throws
  -> Range<String.Index>?
  {
    let re = try makeRegex(pattern)
    guard let match = str.firstMatch(of: re) else {
        return nil
    }
    return match.range

/*    let ns = str as NSString
    let nsRange = NSRange(location: 0, length: ns.length)
    guard let m = re.firstMatch(in: str, range: nsRange) else { return nil }
    guard let r = Range(m.range, in: str) else { return nil }
    return (r, m.range)
 */
  }
  
  // C: makedfa() — b.c
  static func makeRegex(_ pattern: String) throws -> Regex<AnyRegexOutput> {
    // C: b.c's own regex compiler gives specific wording ("illegal primary in
    // regular expression" / "syntax error in regular expression") for a couple of
    // paren-balance mistakes that Swift's Regex compiler doesn't distinguish (it
    // just says "expected ')'" for both an empty group and an unclosed group).
    // Bracket-expression contents are skipped since parens inside a class (e.g.
    // `[()]`) are literal members, not grouping.
    var depth = 0
    var lastOpenHasNothingAfter = false
    var i = pattern.startIndex
    while i < pattern.endIndex {
      let c = pattern[i]
      if c == "\\" {
        i = pattern.index(after: i)
        if i < pattern.endIndex { i = pattern.index(after: i) }
        lastOpenHasNothingAfter = false
        continue
      }
      if c == "[" {
        var j = pattern.index(after: i)
        if j < pattern.endIndex, pattern[j] == "^" { j = pattern.index(after: j) }
        var first = true
        while j < pattern.endIndex {
          if pattern[j] == "]" && !first { j = pattern.index(after: j); break }
          if pattern[j] == "\\" { j = pattern.index(after: j) }
          if j < pattern.endIndex { j = pattern.index(after: j) }
          first = false
        }
        i = j
        lastOpenHasNothingAfter = false
        continue
      }
      if c == "(" {
        depth += 1
        let next = pattern.index(after: i)
        lastOpenHasNothingAfter = (next == pattern.endIndex) || pattern[next] == ")"
      } else if c == ")" {
        depth -= 1
        lastOpenHasNothingAfter = false
      } else {
        lastOpenHasNothingAfter = false
      }
      i = pattern.index(after: i)
    }
    if lastOpenHasNothingAfter {
      throw AWKRuntimeError("illegal primary in regular expression \(pattern)")
    }
    if depth != 0 {
      throw AWKRuntimeError("syntax error in regular expression \(pattern)")
    }
    do {
      // one-true-awk matches individual (wide) characters, not grapheme clusters — e.g. a
      // combining/joining mark like ZWNJ is its own character, not fused with its neighbor.
      // Swift's default grapheme-cluster semantics would otherwise let a class like
      // [[:alpha:]] consume a ZWNJ that happens to follow a letter.
      return try Regex(fixre(pattern)).matchingSemantics(.unicodeScalar)
    } catch {
      // Interpolating the error (not .localizedDescription, which is a useless
      // generic string for regex parse errors) surfaces Swift's own diagnostic,
      // e.g. "expected ')'" or "expected custom character class members".
      throw AWKRuntimeError("invalid regex /\(pattern)/: \(error)")
    }
  }

  // Returns (pattern with any unknown [:name:] POSIX classes stripped out, the
  // unknown names found). An unrecognized class name is a non-fatal warning in
  // real awk, not a compile error, so it can't just be left for Regex to reject.
  static func extractUnknownPosixClasses(_ pattern: String) -> (String, [String]) {
    let known: Set<String> = ["alpha", "digit", "alnum", "upper", "lower", "space",
                               "punct", "print", "graph", "cntrl", "blank", "xdigit"]
    var result = ""
    var unknown: [String] = []
    let chars = Array(pattern)
    var i = 0
    while i < chars.count {
      if chars[i] == "[", i + 1 < chars.count, chars[i + 1] == ":" {
        var j = i + 2
        var name = ""
        while j < chars.count, chars[j].isLetter { name.append(chars[j]); j += 1 }
        if !name.isEmpty, j + 1 < chars.count, chars[j] == ":", chars[j + 1] == "]" {
          if known.contains(name) {
            result.append(contentsOf: chars[i...(j + 1)])
          } else {
            unknown.append(name)
          }
          i = j + 2
          continue
        }
      }
      result.append(chars[i])
      i += 1
    }
    return (result, unknown)
  }


  // Apply the AWK sub/gsub replacement string (& = matched text, \& = literal &, etc.)
  // C: backsub() — run.c
  static func applyReplacement(_ repl: String, matched: Substring) -> String {
    var result = ""
    var i = repl.startIndex
    while i < repl.endIndex {
      let c = repl[i]
      if c == "\\" {
        let next = repl.index(after: i)
        if next >= repl.endIndex { result.append("\\"); break }
        switch repl[next] {
          case "&":
            result.append("&")
            i = repl.index(after: next)
          case "\\":
            let next2 = repl.index(after: next)
            if next2 < repl.endIndex && repl[next2] == "\\" {
              let next3 = repl.index(after: next2)
              if next3 < repl.endIndex && repl[next3] == "&" {
                // \\\& → \&
                result += "\\&"
                i = repl.index(after: next3)
              } else {
                result += "\\\\"
                i = next2
              }
            } else if next2 < repl.endIndex && repl[next2] == "&" {
              // \\& → \ + matched
              result.append("\\")
              result += matched
              i = repl.index(after: next2)
            } else {
              result += "\\\\"
              i = next2
            }
          default:
            result.append("\\")
            result.append(repl[next])
            i = repl.index(after: next)
        }
      } else if c == "&" {
        result += matched
        i = repl.index(after: i)
      } else {
        result.append(c)
        i = repl.index(after: i)
      }
    }
    return result
  }
}
