// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/

// C: awk classifies each variable name as scalar or array while parsing the whole
// program (tran.c / awkgram.y), then rejects a scalar assignment to a name that's
// used as an array anywhere else — e.g. `j = 4` followed later by `"x" in j` fails
// with "can't assign to j; it's an array name.", regardless of statement order.
// This walks the parsed AST once, up front, to reconstruct that global classification.

extension AWKProgram {
  /// Names used as an array anywhere in the program (subscripted, `in`, `split()`'s
  /// destination, `for (k in arr)`, `delete arr[...]`), excluding uses of a function's
  /// own parameter name within that function's body (those are local, not global).
  func staticArrayVariableNames() -> Set<String> {
    var names = Set<String>()

    func addIfGlobal(_ n: String, excluding params: Set<String>) {
      if !params.contains(n) { names.insert(n) }
    }

    func visitLValue(_ lv: LValue, _ params: Set<String>) {
      switch lv {
        case .variable:
          break
        case .field(let e):
          visitExpr(e, params)
        case .element(let n, let keys):
          addIfGlobal(n, excluding: params)
          keys.forEach { visitExpr($0, params) }
        case .indirect(let e):
          visitExpr(e, params)
      }
    }

    func visitExpr(_ e: Expression, _ params: Set<String>) {
      switch e {
        case .number, .string, .regexMatch, .variable:
          break
        case .field(let e1):
          visitExpr(e1, params)
        case .element(let n, let keys):
          addIfGlobal(n, excluding: params)
          keys.forEach { visitExpr($0, params) }
        case .assign(_, let lv, let rhs):
          visitLValue(lv, params); visitExpr(rhs, params)
        case .ternary(let a, let b, let c):
          visitExpr(a, params); visitExpr(b, params); visitExpr(c, params)
        case .logicalOr(let a, let b), .logicalAnd(let a, let b),
             .equal(let a, let b), .notEqual(let a, let b),
             .lessThan(let a, let b), .lessEqual(let a, let b),
             .greaterThan(let a, let b), .greaterEqual(let a, let b),
             .patternMatch(let a, let b), .patternNotMatch(let a, let b),
             .concat(let a, let b), .add(let a, let b), .subtract(let a, let b),
             .multiply(let a, let b), .divide(let a, let b), .modulo(let a, let b),
             .power(let a, let b), .indexExpr(let a, let b), .matchFuncExpr(let a, let b):
          visitExpr(a, params); visitExpr(b, params)
        case .notNull(let a), .negate(let a), .unaryPlus(let a), .logicalNot(let a), .closeExpr(let a):
          visitExpr(a, params)
        case .inArray(let e1, let n):
          addIfGlobal(n, excluding: params)
          visitExpr(e1, params)
        case .inArrayTuple(let es, let n):
          addIfGlobal(n, excluding: params)
          es.forEach { visitExpr($0, params) }
        case .getline(let lv):
          if let lv { visitLValue(lv, params) }
        case .getlineFrom(let lv, let e1):
          if let lv { visitLValue(lv, params) }
          visitExpr(e1, params)
        case .getlinePipe(let lv, let e1):
          if let lv { visitLValue(lv, params) }
          visitExpr(e1, params)
        case .preIncrement(let lv), .preDecrement(let lv), .postIncrement(let lv), .postDecrement(let lv):
          visitLValue(lv, params)
        case .userCall(_, let args), .builtinCall(_, let args), .sprintfExpr(let args):
          args.forEach { visitExpr($0, params) }
        case .subExpr(_, let re, let repl, let target):
          visitExpr(re, params); visitExpr(repl, params); visitLValue(target, params)
        case .substrExpr(let s, let start, let len):
          visitExpr(s, params); visitExpr(start, params)
          if let len { visitExpr(len, params) }
        case .splitExpr(let s, let n, let fs):
          visitExpr(s, params)
          addIfGlobal(n, excluding: params)
          if let fs { visitExpr(fs, params) }
      }
    }

    func visitStmt(_ s: Statement, _ params: Set<String>) {
      switch s {
        case .lineMarker(_, let inner):
          visitStmt(inner, params)
        case .expression(let e):
          visitExpr(e, params)
        case .print_(_, let args, let dest):
          args.forEach { visitExpr($0, params) }
          if let dest {
            switch dest {
              case .pipe(let e), .append(let e), .redirect(let e): visitExpr(e, params)
            }
          }
        case .delete_(let lv):
          visitLValue(lv, params)
        case .if_(let cond, let then, let els):
          visitExpr(cond, params); visitStmt(then, params)
          if let els { visitStmt(els, params) }
        case .while_(let cond, let body):
          visitExpr(cond, params); visitStmt(body, params)
        case .doWhile(let body, let cond):
          visitStmt(body, params); visitExpr(cond, params)
        case .for_(let initS, let cond, let post, let body):
          if let initS { visitStmt(initS, params) }
          if let cond { visitExpr(cond, params) }
          if let post { visitStmt(post, params) }
          visitStmt(body, params)
        case .forIn(_, let arrName, let body):
          addIfGlobal(arrName, excluding: params)
          visitStmt(body, params)
        case .block(let stmts):
          stmts.forEach { visitStmt($0, params) }
        case .next, .nextFile, .break_, .continue_, .empty:
          break
        case .exit_(let e), .return_(let e):
          if let e { visitExpr(e, params) }
      }
    }

    for b in beginRules { b.forEach { visitStmt($0, []) } }
    for r in rules {
      switch r.pattern {
        case .always: break
        case .expression(let e): visitExpr(e, [])
        case .range(let a, let b): visitExpr(a, []); visitExpr(b, [])
      }
      r.body.forEach { visitStmt($0, []) }
    }
    for e in endRules { e.forEach { visitStmt($0, []) } }
    for f in functions {
      let paramSet = Set(f.params)
      f.body.forEach { visitStmt($0, paramSet) }
    }

    return names
  }
}
