// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/

// Token types produced by the AWK lexer.
// Corresponds to the %token declarations in awkgram.y and the keyword table in lex.c.

// MARK: - Builtin function identifiers (FXXX constants from awk.h)

enum AWKBuiltinID: Int, Equatable {
    case length  = 1
    case sqrt    = 2
    case exp     = 3
    case log     = 4
    case int_    = 5
    case system  = 6
    case rand    = 7
    case srand   = 8
    case sin     = 9
    case cos     = 10
    case atan2   = 11
    case toupper = 12
    case tolower = 13
    case fflush  = 14
}

// MARK: - Token

enum AWKToken: Equatable {
  // --- Literal values ---
  case number(Double)           // NUMBER
  case string(String)           // STRING  (escape-processed)
  case regexLiteral(String)     // REGEXPR (contents of /.../
  
  // --- Named entities resolved by the lexer ---
  case variable(String)         // VAR   — plain variable reference
  case ivar(String)             // IVAR  — indirect variable ($$n form)
  case varnf                    // VARNF — special $NF reference
  case callRef(String)          // CALL  — function name in call position
  case arg(Int)                 // ARG   — formal parameter (0-based index)
  case bltin(AWKBuiltinID)      // BLTIN — builtin function identifier
  
  // --- Program structure ---
  case xbegin                   // XBEGIN  (BEGIN)
  case xend                     // XEND    (END)
  case funcKeyword              // FUNC / function
  
  // --- Control-flow keywords ---
  case kwIf                     // IF
  case kwElse                   // ELSE
  case kwWhile                  // WHILE
  case kwFor                    // FOR
  case kwDo                     // DO
  case kwBreak                  // BREAK
  case kwContinue               // CONTINUE
  case kwNext                   // NEXT
  case kwNextfile               // NEXTFILE
  case kwReturn                 // RETURN
  case kwExit                   // EXIT
  case kwDelete                 // DELETE
  case kwIn                     // IN
  
  // --- I/O keywords ---
  case kwPrint                  // PRINT
  case kwPrintf                 // PRINTF
  case kwGetline                // GETLINE
  
  // --- String-function keywords ---
  case kwSprintf                // SPRINTF
  case kwSub                    // SUB
  case kwGsub                   // GSUB
  case kwIndex                  // INDEX
  case kwSplit                  // SPLIT
  case kwSubstr                 // SUBSTR
  case kwMatch                  // MATCHFCN
  case kwClose                  // CLOSE
  
  // --- Operators ---
  case andOp                    // AND   (&&)
  case borOp                    // BOR   (||)
  case appendOp                 // APPEND (>>)
  case matchOp                  // MATCHOP  (~)
  case notMatchOp               // MATCHOP  (!~)
  case eqOp                     // EQ   (==)
  case neOp                     // NE   (!=)
  case ltOp                     // LT   (<)
  case leOp                     // LE   (<=)
  case gtOp                     // GT   (>)
  case geOp                     // GE   (>=)
  case assignOp                 // ASSIGN (=)
  case addEqOp                  // ADDEQ  (+=)
  case subEqOp                  // SUBEQ  (-=)
  case mulEqOp                  // MULTEQ (*=)
  case divEqOp                  // DIVEQ  (/=)
  case modEqOp                  // MODEQ  (%=)
  case powEqOp                  // POWEQ  (^=)
  case powerOp                  // POWER  (^ or **)
  case incrOp                   // INCR   (++)
  case decrOp                   // DECR   (--)
  
  // --- Punctuation ---
  case newline                  // NL   (\n significant in AWK)
  case semicolon                // ';'
  case comma                    // ','
  case lbrace                   // '{'
  case rbrace                   // '}'
  case lparen                   // '('
  case rparen                   // ')'
  case lbracket                 // '['
  case rbracket                 // ']'
  case pipe                     // '|'
  case slash                    // '/'  (division; regex literals → .regexLiteral)
  case question                 // '?'
  case colon                    // ':'
  case dollar                   // '$'
  case plus                     // '+'
  case minus                    // '-'
  case star                     // '*'
  case percent                  // '%'
  case notOp                    // '!'  (NOT / logical-not)
  case atSign                   // '@'  (INDIRECT — gawk/one-true-awk extension)
  
  case eof
}
