// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/

import CMigration
import stdlib_h

typealias Awkfloat = Double

enum CellValue {
  case sval(String)
  case fval(Awkfloat)
  case arr([Cell])
  case dict([String:Cell])
  //  case rec(String)
  case fld(String, Int)
  //  case fcn([Node])
  case builtinString(()->String, (String)->())
  case builtinNumber(()->Double, (Double)->())
}

nonisolated(unsafe) public var GlobalCONVFMT : String = "%.6g"


protocol Cell {
  func asNumber() -> Double?
  func getNumber() -> Double
  func asString() -> String
  func asString(fmt: String) -> String
  var isTrue : Bool { get }
  func length() -> Int
}

extension Cell {

  func asString() -> String {
    return asString(fmt: GlobalCONVFMT)
  }


  func asNumber() -> Double? {
    return nil
  }

  func getNumber() -> Double {
    return asNumber() ?? 0
  }

  func asString(fmt: String) -> String {
    return ""
  }

  var isTrue : Bool { false }
}

class ValueCell : Cell {
  var nval : Double?
  var sval : String?

  func asNumber() -> Double? {
    if let nval { return nval }
    if let sval {

      // FIXME: do this business upon creation of the cell
      if let n = (sval.withCString { c in
        let cc = UnsafeMutablePointer(mutating: c)
        var k : UnsafeMutablePointer<CChar>? = cc
        let r = strtod(c, &k)
        return k == cc ? nil : r
      })
//      if let n = Double(sval.trimmed())
      {
        // if this were mutating ...
        nval = n
        return n
      }
    }
    return nil
  }

  func asString(fmt: String = GlobalCONVFMT) -> String {
    if let sval { return sval }
    if let nval { return cFormat(fmt, nval) }
    return ""
  }

  init(string: String) {
    self.sval = string
  }

  init(number: Double) {
    self.nval = number
  }

  init(number: Int) {
    self.nval = Double(number)
  }

  var isTrue : Bool {
    if let nval, nval != 0 { return true }
    if let sval, !sval.isEmpty, sval != "0" { return true }
    return false
  }

  func length() -> Int {
    return asString().count
  }
}

class EmptyCell : Cell {
  init() {}
  func asNumber() -> Double? { return 0 }
  func asString() -> String { return "" }
  func asString(fmt: String) -> String { return "" }
  var isTrue = false
  func length() -> Int { return 0 }
}

class Dictionary : Cell {
  var dict : [String : Cell] = [:]

  init() {}

  init(dict: [String:Cell]) {
    self.dict = dict
  }

  init(array: [Cell]) {
    for (i,j) in array.enumerated() {
      dict[String(i)]=j
    }
  }

  func length() -> Int {
    return dict.count
  }
}

class BuiltInString : Cell {
  var getter : () -> String
  var setter : (String) -> ()

  init( _ getter: @escaping ()->String, _ setter: @escaping (String)->() ) {
    self.getter = getter
    self.setter = setter
  }

  var isTrue : Bool {
    if let n = asNumber(), n != 0 { return true }
    let s = asString()
    if !s.isEmpty, s != "0" { return true }
    return false
  }

  func asString(fmt: String) -> String {
    return getter()
  }

  func asNumber() -> Double? {
    let k = getter()
    return Double(k)
  }

  func length() -> Int {
    return getter().count
  }
}

struct BuiltInNumber : Cell {
  var getter : () -> Double
  var setter : (Double) -> ()

  init( _ getter: @escaping ()->Double, _ setter: @escaping (Double)->() ) {
    self.getter = getter
    self.setter = setter
  }

    func asNumber() -> Double? { return getter() }
    func asString(fmt: String) -> String { return cFormat( fmt, getter()) }

  func length() -> Int {
    return asString().count
  }
}


/* Cell:  all information about a variable or constant */

extension awk {
  
  /*
  func funnyvar(_ vp : Cell, _ rw : String) {
    if vp.isarr {
      FATAL("can't \(rw) \(vp.nval); it's an array name.")
    }
    if vp.tval.contains(.FCN) {
      FATAL("can't \(rw) \(vp.nval); it's a function.")
    }
    WARNING("funny variable: n=\(vp.nval) s=\"\(vp.sval)\" f=\(vp.fval) t=\(vp.tval)")
  }

 func setsval(_ vp : inout Cell, _ s : String) -> String {  // set string val of a Cell

    DPRINTF("starting setsval: \(vp.nval) = \"\(s)\", t=\(vp.tval), r,f=\(runtime.donerec),\(runtime.donefld)\n")
    if !vp.tval.containsAny(of: [.NUM , .STR] ) {
      funnyvar(vp, "assign to");
    }
    if vp.isfld {
      runtime.donerec = false;  /* mark $0 invalid */
      let fldno = Int(vp.nval)!
      if fldno > runtime.fldtab.count {
        newfld(fldno)
      }
      DPRINTF("setting field \(fldno) to \(s)\n")
    } else if vp.isrec {
      runtime.donefld = false;  /* mark $1... invalid */
      runtime.donerec = true;
      savefs();
    } else if vp.nval == "OFS" {
      if (!runtime.donerec) {
        recbld();
      }
    }
    let t = s
    // FIXME: does this need to be kept?
    /*
    if (freeable(vp)) {
      xfree(vp->sval);
    }
     */

    vp.tval.remove([.NUM, .CONVC, .CONVO])
    vp.tval.insert(.STR)
    vp.fmt = nil
 //   setfree(vp);
    DPRINTF("setsval: \(vp.nval) = \"\(t) (%p) \", t=\(vp.tval) r,f=\(runtime.donerec),\(runtime.donefld)\n")
    vp.sval = t
    if vp.nval == "NF" {
      runtime.donerec = false;  // mark $0 invalid
      let f = getfval(&vp)
      setlastfld(Int(f))
      DPRINTF("setting NF to \(f)\n")
    }

    return vp.sval
  }
   */

  /*
  func getfval(_ vp : inout Cell) -> Awkfloat { // get float val of a Cell 
    if !vp.tval.containsAny(of: [.NUM, .STR]) {
      funnyvar(vp, "read value of");
    }
    if vp.isfld && !runtime.donefld {
      fldbld();
    }
    else if vp.isrec && !runtime.donerec {
      recbld();
    }
    if !vp.isnum {  // not a number
      if let ff = Double(vp.sval), !vp.tval.contains(.CON) { // best guess
        vp.tval.insert(.NUM)  // make NUM only sparingly
        vp.fval = ff
      }
    }
    DPRINTF("getfval: \(vp.nval) = \(vp.fval), t=\(vp.tval)\n")
    return vp.fval
   }


  func update_str_val(_ vp : inout Cell) {
    let s = if vp.fval == vp.fval.rounded(.towardZero) { // it's integral
      String(Int(vp.fval))
    } else {
      // FIXME: what does fmtcheck do?
      String(vp.fval)
//      snprintf(s, sizeof (s), fmtcheck(*fmt, "%g"), vp->fval);
    }
    vp.sval = s
    vp.tval.subtract(.DONTFREE)
    vp.tval.insert(.STR)
  }
*/

/*
  func get_str_val(_ vp : inout Cell, _ fmt : Cell) -> String { // get string val of a Cell
    if !vp.tval.containsAny(of: [.NUM, .STR]) {
      funnyvar(vp, "read value of");
    }
    if vp.isfld && !runtime.donefld {
      fldbld()
    }
    else if vp.isrec && !runtime.donerec {
      recbld()
    }

    /*
     * ADR: This is complicated and more fragile than is desirable.
     * Retrieving a string value for a number associates the string
     * value with the scalar.  Previously, the string value was
     * sticky, meaning if converted via OFMT that became the value
     * (even though POSIX wants it to be via CONVFMT). Or if CONVFMT
     * changed after a string value was retrieved, the original value
     * was maintained and used.  Also not per POSIX.
     *
     * We work around this design by adding two additional flags,
     * CONVC and CONVO, indicating how the string value was
     * obtained (via CONVFMT or OFMT) and _also_ maintaining a copy
     * of the pointer to the xFMT format string used for the
     * conversion.  This pointer is only read, **never** dereferenced.
     * The next time we do a conversion, if it's coming from the same
     * xFMT as last time, and the pointer value is different, we
     * know that the xFMT format string changed, and we need to
     * redo the conversion. If it's the same, we don't have to.
     *
     * There are also several cases where we don't do a conversion,
     * such as for a field (see the checks below).
     */

    /* Don't duplicate the code for actually updating the value */

    if !vp.isstr {
      update_str_val(&vp)
      if fmt.nval == "OFMT" {
        vp.tval.subtract(.CONVC)
        vp.tval.insert(.CONVO)
      } else {
        /* CONVFMT */
        vp.tval.subtract(.CONVO)
        vp.tval.insert(.CONVC)
      }
      vp.fmt = fmt.sval;
    } else if vp.tval.contains(.DONTFREE) || !vp.isnum || vp.isfld {

//      goto done;
    } else if vp.isstr {
      if fmt.nval == "OFMT" {
        if (vp.tval.contains(.CONVC) || vp.tval.contains(.CONVO))
            && vp.fmt != fmt.sval {
              update_str_val(&vp)
              vp.tval.subtract(.CONVC)
              vp.tval.insert(.CONVO)
          vp.fmt = fmt.sval;
            }
      } else {
        // CONVFMT
        if (vp.tval.contains(.CONVO)
            || vp.tval.contains(.CONVC))
            && vp.fmt != fmt.sval {
              update_str_val(&vp)
              vp.tval.subtract(.CONVO)
              vp.tval.insert(.CONVC)
          vp.fmt = fmt.sval;
            }
      }
    }
// done:
    DPRINTF("getsval: \(vp.nval) = \"\(vp.val)\"\n")
    return vp.sval
  }
*/

  /*
  func getsval(_ vp : inout Cell) -> String { // get string val of a Cell
    return get_str_val(&vp, runtime.symtab["CONVFMT"]!)
  }
*/




  /*
   Awkfloat setfval(Cell *vp, Awkfloat f)  /* set float val of a Cell */
   {
   int fldno;

   f += 0.0;    /* normalise negative zero to positive zero */
   if ((vp->tval & (NUM | STR)) == 0)
   funnyvar(vp, "assign to");
   if (isfld(vp)) {
   donerec = false;  /* mark $0 invalid */
   fldno = atoi(vp->nval);
   if (fldno > *NF)
   newfld(fldno);
   DPRINTF("setting field %d to %g\n", fldno, f);
   } else if (&vp->fval == NF) {
   donerec = false;  /* mark $0 invalid */
   setlastfld(f);
   DPRINTF("setting NF to %g\n", f);
   } else if (isrec(vp)) {
   donefld = false;  /* mark $1... invalid */
   donerec = true;
   savefs();
   } else if (vp == ofsloc) {
   if (!donerec)
   recbld();
   }
   if (freeable(vp))
   xfree(vp->sval); /* free any previous string */
   vp->tval &= ~(STR|CONVC|CONVO); /* mark string invalid */
   vp->fmt = NULL;
   vp->tval |= NUM;  /* mark number ok */
   if (f == -0)  /* who would have thought this possible? */
   f = 0;
   DPRINTF("setfval %p: %s = %g, t=%o\n", (void*)vp, NN(vp->nval), f, vp->tval);
   return vp->fval = f;
   }
*/




  /*
   char *getpssval(Cell *vp)     /* get string val of a Cell for print */
   {
   return get_str_val(vp, OFMT);
   }


   char *tostring(const char *s)  /* make a copy of string s */
   {
   char *p = strdup(s);
   if (p == NULL)
   FATAL("out of space in tostring on %s", s);
   return(p);
   }

   wchar_t towc(int* outlen, const char *s, int slen) {
   wchar_t wc = L'\0';
   if (*s) {
   if ((*outlen = mbtowc(&wc, s, slen)) > 0) {
   if (wc > UCHAR_MAX) {
   DPRINTF("pmatch: converted wchar_t is out of uchar range: %s -> %d\n", s, wc);
   }
   } else {
   FATAL("towc: multibyte conversion failure on: '%s'\n", s);
   }
   } else {
   /* Technically wrong */
   *outlen = 1;
   }
   return wc;
   }

   char *tostringN(const char *s, size_t n)  /* make a copy of string s */
   {
   char *p;

   p = malloc(n);
   if (p == NULL)
   FATAL("out of space in tostring on %s", s);
   strcpy(p, s);
   return(p);
   }

   Cell *catstr(Cell *a, Cell *b) /* concatenate a and b */
   {
   Cell *c;
   char *p;
   char *sa = getsval(a);
   char *sb = getsval(b);
   size_t l = strlen(sa) + strlen(sb) + 1;
   p = malloc(l);
   if (p == NULL)
   FATAL("out of space concatenating %s and %s", sa, sb);
   snprintf(p, l, "%s%s", sa, sb);

   l++;  // add room for ' '
   char *newbuf = malloc(l);
   if (newbuf == NULL)
   FATAL("out of space concatenating %s and %s", sa, sb);
   // See string() in lex.c; a string "xx" is stored in the symbol
   // table as "xx ".
   snprintf(newbuf, l, "%s ", p);
   c = setsymtab(newbuf, p, 0.0, CON|STR|DONTFREE, symtab);
   free(p);
   free(newbuf);
   return c;
   }
*/


}


extension String {
  func trimmed() -> String {
    String(drop(while: \.isWhitespace)
      .reversed()
      .drop(while: \.isWhitespace)
      .reversed())
  }
}
