// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/

import CMigration
import Darwin

extension RuntimeState {

  func cleanfld(_ n1 : Int, _ n2 : Int)	{ // clean out fields n1 .. n2 inclusive
                                          // nvals remain intact
    for i in n1 ..< n2 {
      fldtab[i] = ""
    }
  }

  func newfld(_ n : Int) { // add field n after end of existing lastfld
    while fldtab.count <= n {
//      let k = Cell(ctype: .OCELL, csub: .CFLD, nval: String(runtime.fldtab.count), tval: [.FLD, .STR, .DONTFREE])
//      let k = Cell(field: "", at: fldtab.count)
      fldtab.append("")
    }
   }


   func refldbld(_ rec : String, _ fs : String)	-> Int { // build fields from reg expr in FS
     fatalError("refldbld not yet implemented")
     /*
   /* this relies on having fields[] the same length as $0 */
   /* the fields are all stored in this one array with \0's */
   char *fr;
   int i, tempstat, n;
   fa *pfa;
   
   n = strlen(rec);
   if (n > fieldssize) {
   xfree(fields);
   if ((fields = malloc(n+1)) == NULL)
   FATAL("out of space for fields in refldbld %d", n);
   fieldssize = n;
   }
   fr = fields;
   *fr = '\0';
   if (*rec == '\0')
   return 0;
   pfa = makedfa(fs, 1);
   DPRINTF("into refldbld, rec = <%s>, pat = <%s>\n", rec, fs);
   tempstat = pfa->initstat;
   for (i = 1; ; i++) {
   if (i > nfields)
   growfldtab(i);
   if (freeable(fldtab[i]))
   xfree(fldtab[i]->sval);
   fldtab[i]->tval = FLD | STR | DONTFREE;
   fldtab[i]->sval = fr;
   DPRINTF("refldbld: i=%d\n", i);
   if (nematch(pfa, rec)) {
   pfa->initstat = 2;	/* horrible coupling to b.c */
   DPRINTF("match %s (%d chars)\n", patbeg, patlen);
   strncpy(fr, rec, patbeg-rec);
   fr += patbeg - rec + 1;
   *(fr-1) = '\0';
   rec = patbeg + patlen;
   } else {
   DPRINTF("no match %s\n", rec);
   strcpy(fr, rec);
   pfa->initstat = tempstat;
   break;
   }
   }
   return i;
      */
   }

  func FATAL(_ fmt : String) {
    var se = FileDescriptor.standardError
    print("\(options.programName): \(fmt)", to: &se)
    // FIXME: error wasn't implemented
//    error();
    if (options.dbg > 1)	{ // core dump if serious debugging on
      abort();
    }
    exit(2)
  }
  
  func WARNING(_ fmt : String) {
    var se = FileDescriptor.standardError
    print("\(options.programName): \(fmt)", to: &se)
    // FIXME: error wasn't ported
//    error();
  }

}


func localeEncoding() -> IEncoding {
    let codeset = String(cString: nl_langinfo(CODESET))
  return IEncoding(codeset) ?? .utf8
}

// Maps the process locale's codeset to the Unicode.Encoding used when
// decoding/encoding byte streams (SyncRecordReader, AWKFile). Keeping this in
// sync with localeEncoding() ensures reads and writes round-trip bytes
// losslessly instead of opportunistically guessing UTF-8 per record.
/*
func localeUnicodeEncoding() -> any Unicode.Encoding.Type {
    switch localeEncoding() {
    case .isoLatin1:
        return ISOLatin1.self
    default:
        return UTF8.self
    }
}
*/
