// Generated by Robert M. Lefkowitz <code@liberally.net> in 2026 using an LLM
// from a file containing the following notice:

/****************************************************************
Copyright (C) Lucent Technologies 1997
All Rights Reserved

Permission to use, copy, modify, and distribute this software and
its documentation for any purpose and without fee is hereby
granted, provided that the above copyright notice appear in all
copies and that both that the copyright notice and this
permission notice and warranty disclaimer appear in supporting
documentation, and that the name Lucent Technologies or any of
its entities not be used in advertising or publicity pertaining
to distribution of the software without specific, written prior
permission.

LUCENT DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
IN NO EVENT SHALL LUCENT OR ANY OF ITS ENTITIES BE LIABLE FOR ANY
SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
THIS SOFTWARE.
****************************************************************/

import CMigration
import Darwin

extension RuntimeState {




   /*
    * POSIX specifies that fields are supposed to be evaluated as if they were
    * split using the value of FS at the time that the record's value ($0) was
    * read.
    *
    * Since field-splitting is done lazily, we save the current value of FS
    * whenever a new record is read in (implicitly or via getline), or when
    * a new value is assigned to $0.
    */
  /*
   var firsttime = true
   
   func getrec(char **pbuf, int *pbufsize, bool isrecord) -> Int { // get next input record
   // note: cares whether buf == record
   int c;
   char *buf = *pbuf;
   uschar saveb0;
   int bufsize = *pbufsize, savebufsize = bufsize;
   
   if (firsttime) {
   firsttime = false;
   initgetrec();
   }
   DPRINTF("RS=<%s>, FS=<%s>, ARGC=%g, FILENAME=%s\n",
   *RS, *FS, *ARGC, *FILENAME);
   if (isrecord) {
   donefld = false;
   donerec = true;
   }
   
   if (!donefld) {
   savefs();
   }
   
   saveb0 = buf[0];
   buf[0] = 0;
   while (argno < *ARGC || infile == stdin) {
   DPRINTF("argno=%d, file=|%s|\n", argno, file);
   if (infile == NULL) {	/* have to open a new file */
   file = getargv(argno);
   if (file == NULL || *file == '\0') {	/* deleted or zapped */
   argno++;
   continue;
   }
   if (isclvar(file)) {	/* a var=value arg */
   setclvar(file);
   argno++;
   continue;
   }
   *FILENAME = file;
   DPRINTF("opening file %s\n", file);
   if (*file == '-' && *(file+1) == '\0') {
   infile = stdin;
   }
   else if ((infile = fopen(file, "r")) == NULL) {
   FATAL("can't open file \(file)")
   }
   setfval(fnrloc, 0.0);
   }
   c = readrec(&buf, &bufsize, infile, innew);
   if (innew) {
   innew = false;
   }
   if (c != 0 || buf[0] != '\0') {	/* normal record */
   if (isrecord) {
   if (freeable(fldtab[0])) {
   xfree(fldtab[0]->sval);
   }
   fldtab[0]->sval = buf;	/* buf == record */
   fldtab[0]->tval = REC | STR | DONTFREE;
   if (is_number(fldtab[0]->sval)) {
   fldtab[0]->fval = atof(fldtab[0]->sval);
   fldtab[0]->tval |= NUM;
   }
   }
   setfval(nrloc, nrloc->fval+1);
   setfval(fnrloc, fnrloc->fval+1);
   if (donefld == 0) {
   fldbld();
   }
   *pbuf = buf;
   *pbufsize = bufsize;
   return 1;
   }
   /* EOF arrived on this file; set up next */
   if (infile != stdin) {
   fclose(infile);
   }
   infile = NULL;
   argno++;
   }
   buf[0] = saveb0;
   *pbuf = buf;
   *pbufsize = savebufsize;
   return 0;	/* true end of file */
   }
   
   func nextfile() {
   if (infile != NULL && infile != stdin) {
   fclose(infile);
   }
   infile = NULL;
   argno++;
   }
   
   func readrec(char **pbuf, int *pbufsize, FILE *inf, bool newflag)	{ // read one record into buf
   int sep, c, isrec;
   char *rr, *buf = *pbuf;
   int bufsize = *pbufsize;
   char *rs = getsval(rsloc);
   
   if (*rs && rs[1]) {
   bool found;
   
   fa *pfa = makedfa(rs, 1);
   if (newflag)
   found = fnematch(pfa, inf, &buf, &bufsize, recsize);
   else {
   int tempstat = pfa->initstat;
   pfa->initstat = 2;
   found = fnematch(pfa, inf, &buf, &bufsize, recsize);
   pfa->initstat = tempstat;
   }
   if (found) {
   setptr(patbeg, '\0');
   }
   isrec = *buf || !feof(inf);
   } else {
   if ((sep = *rs) == 0) {
   sep = '\n';
   while ((c=getc(inf)) == '\n' && c != EOF)	{ // skip leading \n's
   ;
   }
   if (c != EOF) {
   ungetc(c, inf);
   }
   }
   for (rr = buf; ; ) {
   for (; (c=getc(inf)) != sep && c != EOF; ) {
   if (rr-buf+1 > bufsize) {
   if (!adjbuf(&buf, &bufsize, 1+rr-buf,
   recsize, &rr, "readrec 1")) {
   FATAL("input record `%.30s...' too long", buf);
   }
   }
   *rr++ = c;
   }
   if (*rs == sep || c == EOF) {
   break;
   }
   if ((c = getc(inf)) == '\n' || c == EOF)	{ // 2 in a row
   break;
   }
   if (!adjbuf(&buf, &bufsize, 2+rr-buf, recsize, &rr,
   "readrec 2")) {
   FATAL("input record `%.30s...' too long", buf);
   }
   *rr++ = '\n';
   *rr++ = c;
   }
   if (!adjbuf(&buf, &bufsize, 1+rr-buf, recsize, &rr, "readrec 3")) {
   FATAL("input record `%.30s...' too long", buf);
   }
   *rr = 0;
   isrec = (c == EOF && rr == buf) ? 0 : 1;
   }
   *pbuf = buf;
   *pbufsize = bufsize;
   DPRINTF("readrec saw <%s>, returns %d\n", buf, isrec);
   return isrec;
   }
   
   func getargv(_ n : Int) -> String { // get ARGV[n]
   Cell *x;
   char *s, temp[50];
   extern Array *ARGVtab;
   
   snprintf(temp, sizeof(temp), "%d", n);
   if (lookup(temp, ARGVtab) == NULL) {
   return NULL;
   }
   x = setsymtab(temp, "", 0.0, STR, ARGVtab);
   s = getsval(x);
   DPRINTF("getargv(%d) returns |%s|\n", n, s);
   return s;
   }
   */

  func cleanfld(_ n1 : Int, _ n2 : Int)	{ // clean out fields n1 .. n2 inclusive
                                          // nvals remain intact
    for i in n1 ..< n2 {
      fldtab[i] = ""
    }
  }

  func newfld(_ n : Int) { // add field n after end of existing lastfld
    while fldtab.count <= n {
//      let k = Cell(ctype: .OCELL, csub: .CFLD, nval: String(runtime.fldtab.count), tval: [.FLD, .STR, .DONTFREE])
//      let k = Cell(field: "", at: fldtab.count)
      fldtab.append("")
    }
   }


  func setlastfld(_ n : Int)  { // set lastfld cleaning fldtab cells if necessary
    if (n < 0) {
      FATAL("cannot set NF to a negative value")
    }
    newfld(n)
    // FIXME: do I need to delete excess fields if there are any?
  }



  /*
   func fieldadr(_ n : Int) -> Cell {	// get nth field
   if (n < 0) {
   FATAL("trying to access out of range field %d", n);
   }
   if (n > nfields) { // fields after NF are empty
   growfldtab(n);	// but does not increase NF
   }
   return(fldtab[n]);
   }
   */


   func refldbld(_ rec : String, _ fs : String)	-> Int { // build fields from reg expr in FS
     fatalError("refldbld not yet implemented")
     /*
   /* this relies on having fields[] the same length as $0 */
   /* the fields are all stored in this one array with \0's */
   char *fr;
   int i, tempstat, n;
   fa *pfa;
   
   n = strlen(rec);
   if (n > fieldssize) {
   xfree(fields);
   if ((fields = malloc(n+1)) == NULL)
   FATAL("out of space for fields in refldbld %d", n);
   fieldssize = n;
   }
   fr = fields;
   *fr = '\0';
   if (*rec == '\0')
   return 0;
   pfa = makedfa(fs, 1);
   DPRINTF("into refldbld, rec = <%s>, pat = <%s>\n", rec, fs);
   tempstat = pfa->initstat;
   for (i = 1; ; i++) {
   if (i > nfields)
   growfldtab(i);
   if (freeable(fldtab[i]))
   xfree(fldtab[i]->sval);
   fldtab[i]->tval = FLD | STR | DONTFREE;
   fldtab[i]->sval = fr;
   DPRINTF("refldbld: i=%d\n", i);
   if (nematch(pfa, rec)) {
   pfa->initstat = 2;	/* horrible coupling to b.c */
   DPRINTF("match %s (%d chars)\n", patbeg, patlen);
   strncpy(fr, rec, patbeg-rec);
   fr += patbeg - rec + 1;
   *(fr-1) = '\0';
   rec = patbeg + patlen;
   } else {
   DPRINTF("no match %s\n", rec);
   strcpy(fr, rec);
   pfa->initstat = tempstat;
   break;
   }
   }
   return i;
      */
   }

  func FATAL(_ fmt : String) {
    var se = FileDescriptor.standardError
    print("\(options.programName): \(fmt)", to: &se)
    // FIXME: error wasn't implemented
//    error();
    if (options.dbg > 1)	{ // core dump if serious debugging on
      abort();
    }
    exit(2)
  }
  
  func WARNING(_ fmt : String) {
    var se = FileDescriptor.standardError
    print("\(options.programName): \(fmt)", to: &se)
    // FIXME: error wasn't ported
//    error();
  }

}
